//! MXL112: explicit lifetime parameter on `#[miniextendr]` function or impl block.
//!
//! The C wrapper generated by the proc-macro is `#[no_mangle] extern "C-unwind"`,
//! which is incompatible with any generic parameter — including lifetimes.
//! `&[T]` and `&str` arguments work without explicit lifetime annotations because
//! the macro handles them internally via `TryFromSexp`.

use crate::crate_index::CrateIndex;
use crate::diagnostic::Diagnostic;
use crate::lint_code::LintCode;

pub fn check(index: &CrateIndex, diagnostics: &mut Vec<Diagnostic>) {
    for (path, data) in &index.file_data {
        for (name, line) in &data.lifetime_param_items {
            diagnostics.push(
                Diagnostic::new(
                    LintCode::MXL112,
                    path,
                    *line,
                    format!(
                        "`{name}` has an explicit lifetime parameter on a `#[miniextendr]` \
                         item; lifetime parameters are not supported at the FFI boundary",
                    ),
                )
                .with_help(
                    "use owned types (`Vec<T>` instead of `&[T]`, `String` instead of `&str`) \
                     or remove the explicit lifetime annotation — `&[T]` and `&str` arguments \
                     work without explicit lifetime params",
                ),
            );
        }
    }
}
