#!/bin/bash
# Post-tool-use hook: warn when miniextendr-wrappers.R is modified directly.
#
# The wrappers file is auto-generated by the cdylib build step. If Claude
# edits it directly (e.g., fixing a roxygen issue in the generated output),
# the fix needs to go in the proc-macro source instead, and then
# `just devtools-document` must be re-run to regenerate.

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [[ "$FILE_PATH" == *"miniextendr-wrappers.R" ]]; then
  echo "miniextendr-wrappers.R was modified — this file is auto-generated." >&2
  echo "If you changed roxygen/wrapper codegen in the proc macros, run:" >&2
  echo "  just configure && just rcmdinstall && just devtools-document" >&2
  echo "to regenerate it from source." >&2
fi

exit 0
