// document.rs.in - Template for the R wrapper generator binary.
//
// This file is processed by ./configure to produce document.rs, replacing
// PIGWORLD with the actual crate name in upper-snake-case
// and pigworld with the Rust crate name.
//
// The generated binary reads proc-macro-emitted R wrapper constants and writes
// them to <package>-wrappers.R. Run via `just devtools-document`.

use pigworld::R_WRAPPERS_DEPS_PIGWORLD as DEPS;
use pigworld::R_WRAPPERS_IMPL_DEPS_PIGWORLD as IMPL_DEPS;
use pigworld::R_WRAPPERS_IMPLS_PIGWORLD as IMPLS;
use pigworld::R_WRAPPERS_PARTS_PIGWORLD as PARTS;

fn main() {
    use std::io::Write;

    let dep_flat: Vec<&'static str> = DEPS.concat();
    let impl_dep_flat: Vec<&'static str> = IMPL_DEPS.concat();
    let roots: [&[&'static str]; 4] = [PARTS, IMPLS, &dep_flat, &impl_dep_flat];

    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .truncate(true)
        .create(true)
        .open("pigworld-wrappers.R")
        .unwrap();

    // Write "do not edit" header with lintr guards
    f.write_all(
        b"# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: run `just devtools-document` or rebuild the package.
# nolint start
# nocov start

",
    )
    .unwrap();

    let mut seen = std::collections::HashSet::<&str>::new();
    for group in roots {
        for &s in group {
            if seen.insert(s) {
                let s = s.trim();
                let s: String = s
                    .lines()
                    .map(|line| line.strip_prefix("    ").unwrap_or(line))
                    .collect::<Vec<_>>()
                    .join("\n");
                f.write_all(s.as_bytes()).unwrap();
                f.write_all(b"\n\n").unwrap();
            }
        }
    }

    // Write closing guards
    f.write_all(b"# nocov end\n# nolint end\n").unwrap();
}
