//! Macro for the REALSXP-backed date/time conversion matrix.
//!
//! **`REALSXP` literal is the source of truth (#882).** Datetime newtypes are
//! *defined* to ride on R's `REALSXP` (`f64` days/seconds + a class attribute);
//! they are not `RNativeType` themselves, so there is no generic `T::SEXP_TYPE`
//! to fold this into. The literal is the R↔Rust mapping, not a redundant copy
//! of one — leave it in place.
//!
//! Generates all 8 `TryFromSexp` + `IntoR` impls (scalar / `Option<T>` / `Vec<T>` /
//! `Vec<Option<T>>`, both directions) for types that:
//! - are backed by a single REALSXP `f64` value,
//! - apply a uniform NA policy across all four shapes, and
//! - set a static class attribute via a caller-supplied setter.
//!
//! # Usage
//!
//! ```ignore
//! impl_realsxp_datetime!(
//!     MyType,                // Rust type
//!     "POSIXct",             // R label used in error messages
//!     |v: f64| -> Result<MyType, SexpError> { ... },   // scalar decode
//!     |t: MyType| -> f64    { ... },                   // scalar encode
//!     |sexp: SEXP|          { ... },                   // class setter
//! );
//! ```
//!
//! ## NA policy (identical to the hand-rolled originals)
//!
//! | Shape | NA input | Behaviour |
//! |---|---|---|
//! | `T` scalar | NaN | `Err(SexpError::Na)` |
//! | `Option<T>` scalar | NaN | `Ok(None)` |
//! | `Vec<T>` | NaN at index `i` | `Err(InvalidValue("NA at index {i} not allowed for Vec<T>"))` |
//! | `Vec<Option<T>>` | NaN at index `i` | `None` element |
//!
//! ## Not applicable (stay hand-rolled)
//!
//! - `jiff::Zoned`: scalar decode reads the `tzone` attr from the SEXP itself, and
//!   `Vec<Zoned>` uses the first element's timezone for the `tzone` attribute. These
//!   paths depend on the SEXP object, not just its single f64 value, so they are not
//!   a base-map and cannot be generated by this macro.

/// Generate all 8 `TryFromSexp` + `IntoR` impls for a REALSXP-backed datetime type.
///
/// Parameters:
/// - `$ty`: the Rust type.
/// - `$label`: a string literal used in scalar-length error messages (e.g. `"POSIXct"`).
/// - `$decode`: a closure expression `|v: f64| -> Result<$ty, SexpError> { ... }`.
///   Called once per element; `v` is guaranteed not-NaN at call time.
/// - `$encode`: a closure expression `|t: $ty| -> f64 { ... }`.
/// - `$set_class`: a closure expression `|sexp: SEXP| { ... }` that sets the R class
///   attribute (e.g. `set_posixct_utc`, `|s| s.set_class(date_class_sexp())`).
macro_rules! impl_realsxp_datetime {
    ($ty:ty, $label:literal, $decode:expr, $encode:expr, $set_class:expr) => {
        // region: $ty scalar TryFromSexp

        impl $crate::from_r::TryFromSexp for $ty {
            type Error = $crate::from_r::SexpError;

            fn try_from_sexp(sexp: $crate::SEXP) -> Result<Self, Self::Error> {
                use $crate::SexpExt as _;
                let actual = sexp.type_of();
                if actual != $crate::SEXPTYPE::REALSXP {
                    return Err($crate::from_r::SexpTypeError {
                        expected: $crate::SEXPTYPE::REALSXP,
                        actual,
                    }
                    .into());
                }
                if sexp.len() != 1 {
                    return Err($crate::from_r::SexpError::InvalidValue(format!(
                        concat!("expected scalar ", $label, ", got length {}"),
                        sexp.len()
                    )));
                }
                let v = sexp.real_elt(0);
                if v.is_nan() {
                    return Err($crate::from_r::SexpError::Na($crate::from_r::SexpNaError {
                        sexp_type: $crate::SEXPTYPE::REALSXP,
                    }));
                }
                ($decode)(v)
            }

            unsafe fn try_from_sexp_unchecked(sexp: $crate::SEXP) -> Result<Self, Self::Error> {
                Self::try_from_sexp(sexp)
            }
        }

        // endregion

        // region: Option<$ty> scalar TryFromSexp

        impl $crate::from_r::TryFromSexp for Option<$ty> {
            type Error = $crate::from_r::SexpError;

            fn try_from_sexp(sexp: $crate::SEXP) -> Result<Self, Self::Error> {
                use $crate::SexpExt as _;
                let actual = sexp.type_of();
                if actual == $crate::SEXPTYPE::NILSXP {
                    return Ok(None);
                }
                if actual != $crate::SEXPTYPE::REALSXP {
                    return Err($crate::from_r::SexpTypeError {
                        expected: $crate::SEXPTYPE::REALSXP,
                        actual,
                    }
                    .into());
                }
                if sexp.len() != 1 {
                    return Err($crate::from_r::SexpError::InvalidValue(format!(
                        concat!("expected scalar ", $label, ", got length {}"),
                        sexp.len()
                    )));
                }
                let v = sexp.real_elt(0);
                if v.is_nan() {
                    return Ok(None);
                }
                ($decode)(v).map(Some)
            }

            unsafe fn try_from_sexp_unchecked(sexp: $crate::SEXP) -> Result<Self, Self::Error> {
                Self::try_from_sexp(sexp)
            }
        }

        // endregion

        // region: Vec<$ty> TryFromSexp

        impl $crate::from_r::TryFromSexp for Vec<$ty> {
            type Error = $crate::from_r::SexpError;

            fn try_from_sexp(sexp: $crate::SEXP) -> Result<Self, Self::Error> {
                use $crate::SexpExt as _;
                let actual = sexp.type_of();
                if actual != $crate::SEXPTYPE::REALSXP {
                    return Err($crate::from_r::SexpTypeError {
                        expected: $crate::SEXPTYPE::REALSXP,
                        actual,
                    }
                    .into());
                }
                let src: &[f64] = unsafe { sexp.as_slice() };
                let mut result = Vec::with_capacity(src.len());
                for (i, &v) in src.iter().enumerate() {
                    if v.is_nan() {
                        return Err($crate::from_r::SexpError::InvalidValue(format!(
                            concat!("NA at index {} not allowed for Vec<", stringify!($ty), ">"),
                            i
                        )));
                    }
                    result.push(($decode)(v)?);
                }
                Ok(result)
            }

            unsafe fn try_from_sexp_unchecked(sexp: $crate::SEXP) -> Result<Self, Self::Error> {
                Self::try_from_sexp(sexp)
            }
        }

        // endregion

        // region: Vec<Option<$ty>> TryFromSexp

        impl $crate::from_r::TryFromSexp for Vec<Option<$ty>> {
            type Error = $crate::from_r::SexpError;

            fn try_from_sexp(sexp: $crate::SEXP) -> Result<Self, Self::Error> {
                use $crate::SexpExt as _;
                let actual = sexp.type_of();
                if actual != $crate::SEXPTYPE::REALSXP {
                    return Err($crate::from_r::SexpTypeError {
                        expected: $crate::SEXPTYPE::REALSXP,
                        actual,
                    }
                    .into());
                }
                let src: &[f64] = unsafe { sexp.as_slice() };
                let mut result = Vec::with_capacity(src.len());
                for &v in src.iter() {
                    if v.is_nan() {
                        result.push(None);
                    } else {
                        result.push(Some(($decode)(v)?));
                    }
                }
                Ok(result)
            }

            unsafe fn try_from_sexp_unchecked(sexp: $crate::SEXP) -> Result<Self, Self::Error> {
                Self::try_from_sexp(sexp)
            }
        }

        // endregion

        // region: $ty IntoR (via into_r_infallible!)

        $crate::into_r::into_r_infallible!($ty, |this| {
            unsafe {
                let vec = $crate::sys::Rf_allocVector($crate::SEXPTYPE::REALSXP, 1);
                let _guard = $crate::OwnedProtect::new(vec);
                vec.set_real_elt(0, ($encode)(this));
                ($set_class)(vec);
                vec
            }
        });

        // endregion

        // region: Option<$ty> IntoR (via into_r_infallible!)

        $crate::into_r::into_r_infallible!(Option<$ty>, |this| {
            unsafe {
                let vec = $crate::sys::Rf_allocVector($crate::SEXPTYPE::REALSXP, 1);
                let _guard = $crate::OwnedProtect::new(vec);
                match this {
                    Some(t) => vec.set_real_elt(0, ($encode)(t)),
                    None => vec.set_real_elt(0, f64::NAN),
                }
                ($set_class)(vec);
                vec
            }
        });

        // endregion

        // region: Vec<$ty> IntoR (via into_r_infallible!)

        $crate::into_r::into_r_infallible!(Vec<$ty>, |this| {
            unsafe {
                let (vec, dst) = $crate::into_r::alloc_r_vector::<f64>(this.len());
                let _guard = $crate::OwnedProtect::new(vec);
                for (slot, t) in dst.iter_mut().zip(this) {
                    *slot = ($encode)(t);
                }
                ($set_class)(vec);
                vec
            }
        });

        // endregion

        // region: Vec<Option<$ty>> IntoR (via into_r_infallible!)

        $crate::into_r::into_r_infallible!(Vec<Option<$ty>>, |this| {
            unsafe {
                let (vec, dst) = $crate::into_r::alloc_r_vector::<f64>(this.len());
                let _guard = $crate::OwnedProtect::new(vec);
                for (slot, opt) in dst.iter_mut().zip(this) {
                    *slot = match opt {
                        Some(t) => ($encode)(t),
                        None => f64::NAN,
                    };
                }
                ($set_class)(vec);
                vec
            }
        });

        // endregion
    };
}

pub(crate) use impl_realsxp_datetime;
