#' @source Generated by miniextendr from Rust fn `rpkg_constant_int`
#' @export
unsafe_rpkg_constant_int <- function() {
    .Call(rpkg_constant_int)
}

#' @source Generated by miniextendr from Rust fn `rpkg_constant_real`
#' @export
unsafe_rpkg_constant_real <- function() {
    .Call(rpkg_constant_real)
}

#' @source Generated by miniextendr from Rust fn `arith_seq`
arith_seq <- function(from, to, length_out) {
    .Call(C_arith_seq, .call = match.call(), from, to, length_out)
}

#' @source Generated by miniextendr from Rust fn `lazy_int_seq`
#' @export
lazy_int_seq <- function(from, to, by) {
    .Call(C_lazy_int_seq, .call = match.call(), from, to, by)
}

#' @source Generated by miniextendr from Rust fn `rpkg_lazy_int_seq_is_materialized`
#' @export
unsafe_rpkg_lazy_int_seq_is_materialized <- function(x) {
    .Call(rpkg_lazy_int_seq_is_materialized, x)
}

#' @source Generated by miniextendr from Rust fn `constant_logical`
constant_logical <- function(value, n) {
    .Call(C_constant_logical, .call = match.call(), value, n)
}

#' @source Generated by miniextendr from Rust fn `lazy_string`
lazy_string <- function(prefix, n) {
    .Call(C_lazy_string, .call = match.call(), prefix, n)
}

#' @source Generated by miniextendr from Rust fn `repeating_raw`
repeating_raw <- function(pattern, n) {
    .Call(C_repeating_raw, .call = match.call(), pattern, n)
}

#' @source Generated by miniextendr from Rust fn `unit_circle`
#' @export
unit_circle <- function(n) {
    .Call(C_unit_circle, .call = match.call(), n)
}

#' @source Generated by miniextendr from Rust fn `rpkg_simple_vec_int`
#' @export
unsafe_rpkg_simple_vec_int <- function(x) {
    .Call(rpkg_simple_vec_int, x)
}

#' @source Generated by miniextendr from Rust fn `rpkg_inferred_vec_real`
#' @export
unsafe_rpkg_inferred_vec_real <- function(x) {
    .Call(rpkg_inferred_vec_real, x)
}

#' @source Generated by miniextendr from Rust fn `boxed_ints`
#' @export
boxed_ints <- function(n) {
    .Call(C_boxed_ints, .call = match.call(), n)
}

#' @source Generated by miniextendr from Rust fn `static_ints`
#' @export
static_ints <- function() {
    .Call(C_static_ints, .call = match.call())
}

#' @source Generated by miniextendr from Rust fn `leaked_ints`
#' @export
leaked_ints <- function(n) {
    .Call(C_leaked_ints, .call = match.call(), n)
}

#' @source Generated by miniextendr from Rust fn `static_strings`
#' @export
static_strings <- function() {
    .Call(C_static_strings, .call = match.call())
}

#' @source Generated by miniextendr from Rust fn `add`
#' @export
add <- function(left, right) {
    .Call(C_add, .call = match.call(), left, right)
}

#' @source Generated by miniextendr from Rust fn `add2`
#' @export
add2 <- function(left, right, unused_dummy = NULL) {
    .Call(C_add2, .call = match.call(), left, right, unused_dummy)
}

#' @source Generated by miniextendr from Rust fn `add3`
#' @export
add3 <- function(left, right, unused_dummy = NULL) {
    .Call(C_add3, .call = match.call(), left, right, unused_dummy)
}

#' @source Generated by miniextendr from Rust fn `add4`
#' @export
add4 <- function(left, right) {
    .Call(C_add4, .call = match.call(), left, right)
}

#' @source Generated by miniextendr from Rust fn `nested_panic`
#' @export
nested_panic <- function() {
    invisible(.Call(C_nested_panic, .call = match.call()))
}

#' @source Generated by miniextendr from Rust fn `add_panic`
#' @export
add_panic <- function(unused_left, unused_right) {
    .Call(C_add_panic, .call = match.call(), unused_left, unused_right)
}

#' @source Generated by miniextendr from Rust fn `add_r_error`
#' @export
add_r_error <- function(unused_left, unused_right) {
    .Call(C_add_r_error, .call = match.call(), unused_left, unused_right)
}

#' @source Generated by miniextendr from Rust fn `add_panic_heap`
#' @export
add_panic_heap <- function(unused_left, unused_right) {
    .Call(C_add_panic_heap, .call = match.call(), unused_left, unused_right)
}

#' @source Generated by miniextendr from Rust fn `add_r_error_heap`
#' @export
add_r_error_heap <- function(unused_left, unused_right) {
    .Call(C_add_r_error_heap, .call = match.call(), unused_left, unused_right)
}

#' @source Generated by miniextendr from Rust fn `add_left_mut`
#' @export
add_left_mut <- function(left, right) {
    .Call(C_add_left_mut, .call = match.call(), left, right)
}

#' @source Generated by miniextendr from Rust fn `add_right_mut`
#' @export
add_right_mut <- function(left, right) {
    .Call(C_add_right_mut, .call = match.call(), left, right)
}

#' @source Generated by miniextendr from Rust fn `add_left_right_mut`
#' @export
add_left_right_mut <- function(left, right) {
    .Call(C_add_left_right_mut, .call = match.call(), left, right)
}

#' @source Generated by miniextendr from Rust fn `take_and_return_nothing`
#' @export
take_and_return_nothing <- function() {
    invisible(.Call(C_take_and_return_nothing, .call = match.call()))
}

#' @source Generated by miniextendr from Rust fn `C_just_panic`
#' @export
unsafe_C_just_panic <- function() {
    .Call(C_just_panic)
}

#' @source Generated by miniextendr from Rust fn `C_panic_and_catch`
#' @export
unsafe_C_panic_and_catch <- function() {
    .Call(C_panic_and_catch)
}

#' @source Generated by miniextendr from Rust fn `drop_message_on_success`
#' @export
drop_message_on_success <- function() {
    .Call(C_drop_message_on_success, .call = match.call())
}

#' @source Generated by miniextendr from Rust fn `drop_on_panic`
#' @export
drop_on_panic <- function() {
    invisible(.Call(C_drop_on_panic, .call = match.call()))
}

#' @source Generated by miniextendr from Rust fn `drop_on_panic_with_move`
#' @export
drop_on_panic_with_move <- function() {
    invisible(.Call(C_drop_on_panic_with_move, .call = match.call()))
}

#' @source Generated by miniextendr from Rust fn `C_r_error`
#' @export
unsafe_C_r_error <- function() {
    .Call(C_r_error)
}

#' @source Generated by miniextendr from Rust fn `C_r_error_in_catch`
#' @export
unsafe_C_r_error_in_catch <- function() {
    .Call(C_r_error_in_catch)
}

#' @source Generated by miniextendr from Rust fn `C_r_error_in_thread`
#' @export
unsafe_C_r_error_in_thread <- function() {
    .Call(C_r_error_in_thread)
}

#' @source Generated by miniextendr from Rust fn `C_r_print_in_thread`
#' @export
unsafe_C_r_print_in_thread <- function() {
    .Call(C_r_print_in_thread)
}

#' @source Generated by miniextendr from Rust fn `C_unwind_protect_normal`
#' @export
unsafe_C_unwind_protect_normal <- function() {
    .Call(C_unwind_protect_normal)
}

#' @source Generated by miniextendr from Rust fn `C_unwind_protect_r_error`
#' @export
unsafe_C_unwind_protect_r_error <- function() {
    .Call(C_unwind_protect_r_error)
}

#' @source Generated by miniextendr from Rust fn `C_unwind_protect_lowlevel_test`
#' @export
unsafe_C_unwind_protect_lowlevel_test <- function() {
    .Call(C_unwind_protect_lowlevel_test)
}

#' @source Generated by miniextendr from Rust fn `greetings_with_named_dots`
#' @export
greetings_with_named_dots <- function(dots = ...) {
    invisible(.Call(C_greetings_with_named_dots, .call = match.call(), list(dots)))
}

#' @source Generated by miniextendr from Rust fn `greetings_with_named_and_unused_dots`
#' @export
greetings_with_named_and_unused_dots <- function(unused_dots = ...) {
    invisible(.Call(C_greetings_with_named_and_unused_dots, .call = match.call(), list(unused_dots)))
}

#' @source Generated by miniextendr from Rust fn `greetings_with_nameless_dots`
#' @export
greetings_with_nameless_dots <- function(...) {
    invisible(.Call(C_greetings_with_nameless_dots, .call = match.call(), list(...)))
}

#' @source Generated by miniextendr from Rust fn `greetings_last_as_named_dots`
#' @export
greetings_last_as_named_dots <- function(unused_exclamations, dots = ...) {
    invisible(.Call(C_greetings_last_as_named_dots, .call = match.call(), unused_exclamations, list(dots)))
}

#' @source Generated by miniextendr from Rust fn `greetings_last_as_named_and_unused_dots`
#' @export
greetings_last_as_named_and_unused_dots <- function(unused_exclamations, unused_dots = ...) {
    invisible(.Call(C_greetings_last_as_named_and_unused_dots, .call = match.call(), unused_exclamations, list(unused_dots)))
}

#' @source Generated by miniextendr from Rust fn `greetings_last_as_nameless_dots`
#' @export
greetings_last_as_nameless_dots <- function(unused_exclamations, ...) {
    invisible(.Call(C_greetings_last_as_nameless_dots, .call = match.call(), unused_exclamations, list(...)))
}

#' @source Generated by miniextendr from Rust fn `C_check_interupt_after`
#' @export
unsafe_C_check_interupt_after <- function() {
    .Call(C_check_interupt_after)
}

#' @source Generated by miniextendr from Rust fn `C_check_interupt_unwind`
#' @export
unsafe_C_check_interupt_unwind <- function() {
    .Call(C_check_interupt_unwind)
}

#' @source Generated by miniextendr from Rust fn `test_i32_identity`
#' @export
test_i32_identity <- function(x) {
    .Call(C_test_i32_identity, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_i32_add_one`
#' @export
test_i32_add_one <- function(x) {
    .Call(C_test_i32_add_one, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_i32_sum`
#' @export
test_i32_sum <- function(a, b, c) {
    .Call(C_test_i32_sum, .call = match.call(), a, b, c)
}

#' @source Generated by miniextendr from Rust fn `test_f64_identity`
#' @export
test_f64_identity <- function(x) {
    .Call(C_test_f64_identity, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_f64_add_one`
#' @export
test_f64_add_one <- function(x) {
    .Call(C_test_f64_add_one, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_f64_multiply`
#' @export
test_f64_multiply <- function(a, b) {
    .Call(C_test_f64_multiply, .call = match.call(), a, b)
}

#' @source Generated by miniextendr from Rust fn `test_u8_identity`
#' @export
test_u8_identity <- function(x) {
    .Call(C_test_u8_identity, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_u8_add_one`
#' @export
test_u8_add_one <- function(x) {
    .Call(C_test_u8_add_one, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_logical_identity`
#' @export
test_logical_identity <- function(x) {
    .Call(C_test_logical_identity, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_logical_not`
#' @export
test_logical_not <- function(x) {
    .Call(C_test_logical_not, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_logical_and`
#' @export
test_logical_and <- function(a, b) {
    .Call(C_test_logical_and, .call = match.call(), a, b)
}

#' @source Generated by miniextendr from Rust fn `test_i32_to_f64`
#' @export
test_i32_to_f64 <- function(x) {
    .Call(C_test_i32_to_f64, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_f64_to_i32`
#' @export
test_f64_to_i32 <- function(x) {
    .Call(C_test_f64_to_i32, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_i32_slice_len`
#' @export
test_i32_slice_len <- function(x) {
    .Call(C_test_i32_slice_len, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_i32_slice_sum`
#' @export
test_i32_slice_sum <- function(x) {
    .Call(C_test_i32_slice_sum, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_i32_slice_first`
#' @export
test_i32_slice_first <- function(x) {
    .Call(C_test_i32_slice_first, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_i32_slice_last`
#' @export
test_i32_slice_last <- function(x) {
    .Call(C_test_i32_slice_last, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_f64_slice_len`
#' @export
test_f64_slice_len <- function(x) {
    .Call(C_test_f64_slice_len, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_f64_slice_sum`
#' @export
test_f64_slice_sum <- function(x) {
    .Call(C_test_f64_slice_sum, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_f64_slice_mean`
#' @export
test_f64_slice_mean <- function(x) {
    .Call(C_test_f64_slice_mean, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_u8_slice_len`
#' @export
test_u8_slice_len <- function(x) {
    .Call(C_test_u8_slice_len, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_u8_slice_sum`
#' @export
test_u8_slice_sum <- function(x) {
    .Call(C_test_u8_slice_sum, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_logical_slice_len`
#' @export
test_logical_slice_len <- function(x) {
    .Call(C_test_logical_slice_len, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_logical_slice_any_true`
#' @export
test_logical_slice_any_true <- function(x) {
    .Call(C_test_logical_slice_any_true, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_logical_slice_all_true`
#' @export
test_logical_slice_all_true <- function(x) {
    .Call(C_test_logical_slice_all_true, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `extptr_counter_new`
#' @export
extptr_counter_new <- function(initial) {
    .Call(C_extptr_counter_new, .call = match.call(), initial)
}

#' @source Generated by miniextendr from Rust fn `C_extptr_counter_get`
#' @export
unsafe_C_extptr_counter_get <- function(ptr) {
    .Call(C_extptr_counter_get, ptr)
}

#' @source Generated by miniextendr from Rust fn `C_extptr_counter_increment`
#' @export
unsafe_C_extptr_counter_increment <- function(ptr) {
    .Call(C_extptr_counter_increment, ptr)
}

#' @source Generated by miniextendr from Rust fn `extptr_point_new`
#' @export
extptr_point_new <- function(x, y) {
    .Call(C_extptr_point_new, .call = match.call(), x, y)
}

#' @source Generated by miniextendr from Rust fn `C_extptr_point_get_x`
#' @export
unsafe_C_extptr_point_get_x <- function(ptr) {
    .Call(C_extptr_point_get_x, ptr)
}

#' @source Generated by miniextendr from Rust fn `C_extptr_point_get_y`
#' @export
unsafe_C_extptr_point_get_y <- function(ptr) {
    .Call(C_extptr_point_get_y, ptr)
}

#' @source Generated by miniextendr from Rust fn `C_extptr_type_mismatch_test`
#' @export
unsafe_C_extptr_type_mismatch_test <- function(ptr) {
    .Call(C_extptr_type_mismatch_test, ptr)
}

#' @source Generated by miniextendr from Rust fn `C_extptr_null_test`
#' @export
unsafe_C_extptr_null_test <- function(ptr) {
    .Call(C_extptr_null_test, ptr)
}

#' @source Generated by miniextendr from Rust fn `C_extptr_is_counter`
#' @export
unsafe_C_extptr_is_counter <- function(ptr) {
    .Call(C_extptr_is_counter, ptr)
}

#' @source Generated by miniextendr from Rust fn `C_extptr_is_point`
#' @export
unsafe_C_extptr_is_point <- function(ptr) {
    .Call(C_extptr_is_point, ptr)
}

#' @source Generated by miniextendr from Rust fn `C_worker_drop_on_success`
#' @export
unsafe_C_worker_drop_on_success <- function() {
    .Call(C_worker_drop_on_success)
}

#' @source Generated by miniextendr from Rust fn `C_worker_drop_on_panic`
#' @export
unsafe_C_worker_drop_on_panic <- function() {
    .Call(C_worker_drop_on_panic)
}

#' @source Generated by miniextendr from Rust fn `C_test_worker_simple`
#' @export
unsafe_C_test_worker_simple <- function() {
    .Call(C_test_worker_simple)
}

#' @source Generated by miniextendr from Rust fn `C_test_worker_with_r_thread`
#' @export
unsafe_C_test_worker_with_r_thread <- function() {
    .Call(C_test_worker_with_r_thread)
}

#' @source Generated by miniextendr from Rust fn `C_test_worker_multiple_r_calls`
#' @export
unsafe_C_test_worker_multiple_r_calls <- function() {
    .Call(C_test_worker_multiple_r_calls)
}

#' @source Generated by miniextendr from Rust fn `C_test_worker_panic_simple`
#' @export
unsafe_C_test_worker_panic_simple <- function() {
    .Call(C_test_worker_panic_simple)
}

#' @source Generated by miniextendr from Rust fn `C_test_worker_panic_with_drops`
#' @export
unsafe_C_test_worker_panic_with_drops <- function() {
    .Call(C_test_worker_panic_with_drops)
}

#' @source Generated by miniextendr from Rust fn `C_test_worker_panic_in_r_thread`
#' @export
unsafe_C_test_worker_panic_in_r_thread <- function() {
    .Call(C_test_worker_panic_in_r_thread)
}

#' @source Generated by miniextendr from Rust fn `C_test_worker_panic_in_r_thread_with_drops`
#' @export
unsafe_C_test_worker_panic_in_r_thread_with_drops <- function() {
    .Call(C_test_worker_panic_in_r_thread_with_drops)
}

#' @source Generated by miniextendr from Rust fn `C_test_worker_r_error_in_r_thread`
#' @export
unsafe_C_test_worker_r_error_in_r_thread <- function() {
    .Call(C_test_worker_r_error_in_r_thread)
}

#' @source Generated by miniextendr from Rust fn `C_test_worker_r_error_with_drops`
#' @export
unsafe_C_test_worker_r_error_with_drops <- function() {
    .Call(C_test_worker_r_error_with_drops)
}

#' @source Generated by miniextendr from Rust fn `C_test_worker_r_calls_then_error`
#' @export
unsafe_C_test_worker_r_calls_then_error <- function() {
    .Call(C_test_worker_r_calls_then_error)
}

#' @source Generated by miniextendr from Rust fn `C_test_worker_r_calls_then_panic`
#' @export
unsafe_C_test_worker_r_calls_then_panic <- function() {
    .Call(C_test_worker_r_calls_then_panic)
}

#' @source Generated by miniextendr from Rust fn `test_worker_return_i32`
#' @export
test_worker_return_i32 <- function() {
    .Call(C_test_worker_return_i32, .call = match.call())
}

#' @source Generated by miniextendr from Rust fn `test_worker_return_string`
#' @export
test_worker_return_string <- function() {
    .Call(C_test_worker_return_string, .call = match.call())
}

#' @source Generated by miniextendr from Rust fn `test_worker_return_f64`
#' @export
test_worker_return_f64 <- function() {
    .Call(C_test_worker_return_f64, .call = match.call())
}

#' @source Generated by miniextendr from Rust fn `C_test_extptr_from_worker`
#' @export
unsafe_C_test_extptr_from_worker <- function() {
    .Call(C_test_extptr_from_worker)
}

#' @source Generated by miniextendr from Rust fn `C_test_multiple_extptrs_from_worker`
#' @export
unsafe_C_test_multiple_extptrs_from_worker <- function() {
    .Call(C_test_multiple_extptrs_from_worker)
}

#' @source Generated by miniextendr from Rust fn `test_main_thread_r_api`
#' @export
test_main_thread_r_api <- function() {
    .Call(C_test_main_thread_r_api, .call = match.call())
}

#' @source Generated by miniextendr from Rust fn `test_main_thread_r_error`
#' @export
test_main_thread_r_error <- function() {
    .Call(C_test_main_thread_r_error, .call = match.call())
}

#' @source Generated by miniextendr from Rust fn `test_main_thread_r_error_with_drops`
#' @export
test_main_thread_r_error_with_drops <- function() {
    .Call(C_test_main_thread_r_error_with_drops, .call = match.call())
}

#' @source Generated by miniextendr from Rust fn `C_test_wrong_thread_r_api`
#' @export
unsafe_C_test_wrong_thread_r_api <- function() {
    .Call(C_test_wrong_thread_r_api)
}

#' @source Generated by miniextendr from Rust fn `C_test_nested_helper_from_worker`
#' @export
unsafe_C_test_nested_helper_from_worker <- function() {
    .Call(C_test_nested_helper_from_worker)
}

#' @source Generated by miniextendr from Rust fn `C_test_nested_multiple_helpers`
#' @export
unsafe_C_test_nested_multiple_helpers <- function() {
    .Call(C_test_nested_multiple_helpers)
}

#' @source Generated by miniextendr from Rust fn `C_test_nested_with_r_thread`
#' @export
unsafe_C_test_nested_with_r_thread <- function() {
    .Call(C_test_nested_with_r_thread)
}

#' @source Generated by miniextendr from Rust fn `C_test_call_worker_fn_from_main`
#' @export
unsafe_C_test_call_worker_fn_from_main <- function() {
    .Call(C_test_call_worker_fn_from_main)
}

#' @source Generated by miniextendr from Rust fn `C_test_nested_worker_calls`
#' @export
unsafe_C_test_nested_worker_calls <- function() {
    .Call(C_test_nested_worker_calls)
}

#' @source Generated by miniextendr from Rust fn `C_test_nested_with_error`
#' @export
unsafe_C_test_nested_with_error <- function() {
    .Call(C_test_nested_with_error)
}

#' @source Generated by miniextendr from Rust fn `C_test_nested_with_panic`
#' @export
unsafe_C_test_nested_with_panic <- function() {
    .Call(C_test_nested_with_panic)
}

#' @source Generated by miniextendr from Rust fn `C_test_deep_with_r_thread_sequence`
#' @export
unsafe_C_test_deep_with_r_thread_sequence <- function() {
    .Call(C_test_deep_with_r_thread_sequence)
}

#' @source Generated by miniextendr from Rust fn `test_coerce_identity`
#' @export
test_coerce_identity <- function(x) {
    .Call(C_test_coerce_identity, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_coerce_widen`
#' @export
test_coerce_widen <- function(x) {
    .Call(C_test_coerce_widen, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_coerce_bool_to_int`
#' @export
test_coerce_bool_to_int <- function(x) {
    .Call(C_test_coerce_bool_to_int, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_coerce_via_helper`
#' @export
test_coerce_via_helper <- function(x) {
    .Call(C_test_coerce_via_helper, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_try_coerce_f64_to_i32`
#' @export
test_try_coerce_f64_to_i32 <- function(x) {
    .Call(C_test_try_coerce_f64_to_i32, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_rnative_newtype`
#' @export
test_rnative_newtype <- function(id) {
    .Call(C_test_rnative_newtype, .call = match.call(), id)
}

#' @source Generated by miniextendr from Rust fn `test_rnative_named_field`
#' @export
test_rnative_named_field <- function(temp) {
    .Call(C_test_rnative_named_field, .call = match.call(), temp)
}

#' @source Generated by miniextendr from Rust fn `test_coerce_attr_u16`
#' @export
test_coerce_attr_u16 <- function(x) {
    .Call(C_test_coerce_attr_u16, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_coerce_attr_i16`
#' @export
test_coerce_attr_i16 <- function(x) {
    .Call(C_test_coerce_attr_i16, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_coerce_attr_vec_u16`
#' @export
test_coerce_attr_vec_u16 <- function(x) {
    .Call(C_test_coerce_attr_vec_u16, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_coerce_attr_f32`
#' @export
test_coerce_attr_f32 <- function(x) {
    .Call(C_test_coerce_attr_f32, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `test_coerce_attr_with_invisible`
#' @export
test_coerce_attr_with_invisible <- function(x) {
    invisible(.Call(C_test_coerce_attr_with_invisible, .call = match.call(), x))
}

#' @source Generated by miniextendr from Rust fn `test_per_arg_coerce_first`
#' @export
test_per_arg_coerce_first <- function(x, y) {
    .Call(C_test_per_arg_coerce_first, .call = match.call(), x, y)
}

#' @source Generated by miniextendr from Rust fn `test_per_arg_coerce_second`
#' @export
test_per_arg_coerce_second <- function(x, y) {
    .Call(C_test_per_arg_coerce_second, .call = match.call(), x, y)
}

#' @source Generated by miniextendr from Rust fn `test_per_arg_coerce_both`
#' @export
test_per_arg_coerce_both <- function(x, y) {
    .Call(C_test_per_arg_coerce_both, .call = match.call(), x, y)
}

#' @source Generated by miniextendr from Rust fn `test_per_arg_coerce_vec`
#' @export
test_per_arg_coerce_vec <- function(x, y) {
    .Call(C_test_per_arg_coerce_vec, .call = match.call(), x, y)
}

#' @source Generated by miniextendr from Rust fn `invisibly_return_no_arrow`
#' @export
invisibly_return_no_arrow <- function() {
    invisible(.Call(C_invisibly_return_no_arrow, .call = match.call()))
}

#' @source Generated by miniextendr from Rust fn `invisibly_return_arrow`
#' @export
invisibly_return_arrow <- function() {
    invisible(.Call(C_invisibly_return_arrow, .call = match.call()))
}

#' @source Generated by miniextendr from Rust fn `invisibly_option_return_none`
#' @export
invisibly_option_return_none <- function() {
    invisible(.Call(C_invisibly_option_return_none, .call = match.call()))
}

#' @source Generated by miniextendr from Rust fn `invisibly_option_return_some`
#' @export
invisibly_option_return_some <- function() {
    invisible(.Call(C_invisibly_option_return_some, .call = match.call()))
}

#' @source Generated by miniextendr from Rust fn `invisibly_result_return_ok`
#' @export
invisibly_result_return_ok <- function() {
    invisible(.Call(C_invisibly_result_return_ok, .call = match.call()))
}

#' @source Generated by miniextendr from Rust fn `force_invisible_i32`
#' @export
force_invisible_i32 <- function() {
    invisible(.Call(C_force_invisible_i32, .call = match.call()))
}

#' @source Generated by miniextendr from Rust fn `force_visible_unit`
#' @export
force_visible_unit <- function() {
    .Call(C_force_visible_unit, .call = match.call())
}

#' @source Generated by miniextendr from Rust fn `with_interrupt_check`
#' @export
with_interrupt_check <- function(x) {
    .Call(C_with_interrupt_check, .call = match.call(), x)
}

#' @source Generated by miniextendr from Rust fn `C_test_r_thread_builder`
#' @export
unsafe_C_test_r_thread_builder <- function() {
    .Call(C_test_r_thread_builder)
}

#' @source Generated by miniextendr from Rust fn `C_test_r_thread_builder_spawn_join`
#' @export
unsafe_C_test_r_thread_builder_spawn_join <- function() {
    .Call(C_test_r_thread_builder_spawn_join)
}

#' @source Generated by miniextendr from Rust fn `underscore_it_all`
#' @export
underscore_it_all <- function(private__unused0, private__unused1) {
    invisible(.Call(C_underscore_it_all, .call = match.call(), private__unused0, private__unused1))
}

#' @source Generated by miniextendr from Rust fn `C_test_spawn_with_r_lean_stack`
#' @export
unsafe_C_test_spawn_with_r_lean_stack <- function() {
    .Call(C_test_spawn_with_r_lean_stack)
}

#' @source Generated by miniextendr from Rust fn `C_test_stack_check_guard_lean`
#' @export
unsafe_C_test_stack_check_guard_lean <- function() {
    .Call(C_test_stack_check_guard_lean)
}

#' @source Generated by miniextendr from Rust type `ReceiverCounter`
#' @export
ReceiverCounter <- new.env(parent = emptyenv())

ReceiverCounter$new <- function(initial) {
    self <- .Call(C_ReceiverCounter__new, initial)
    class(self) <- "ReceiverCounter"
    self
}

ReceiverCounter$value <- function() {
    .Call(C_ReceiverCounter__value, self)
}

ReceiverCounter$inc <- function() {
    .Call(C_ReceiverCounter__inc, self)
}

ReceiverCounter$add <- function(amount) {
    .Call(C_ReceiverCounter__add, self, amount)
}

ReceiverCounter$default_counter <- function() {
    self <- .Call(C_ReceiverCounter__default_counter)
    class(self) <- "ReceiverCounter"
    self
}

#' @export
`$.ReceiverCounter` <- function(self, name) {
    func <- ReceiverCounter[[name]]
    environment(func) <- environment()
    func
}
#' @export
`[[.ReceiverCounter` <- `$.ReceiverCounter`

#' @source Generated by miniextendr from Rust type `R6Counter`
#' @export
R6Counter <- R6::R6Class("R6Counter",
    public = list(
        initialize = function(initial, .ptr = NULL) {
            if (!is.null(.ptr)) {
                private$.ptr <- .ptr
            } else {
                private$.ptr <- .Call(C_R6Counter__new, initial)
            }
        },
        value = function() {
            .Call(C_R6Counter__value, private$.ptr)
        },
        inc = function() {
            .Call(C_R6Counter__inc, private$.ptr)
        },
        add = function(amount) {
            .Call(C_R6Counter__add, private$.ptr, amount)
        }
    ),
    private = list(
        .ptr = NULL
    ),
    lock_objects = TRUE,
    lock_class = FALSE,
    cloneable = FALSE
)

R6Counter$default_counter <- function() {
    R6Counter$new(.ptr = .Call(C_R6Counter__default_counter))
}

#' @source Generated by miniextendr from `S3Counter::new`
#' @export
new_s3counter <- function(initial) {
    structure(.Call(C_S3Counter__new, initial), class = "S3Counter")
}

#' @source Generated by miniextendr from `S3Counter::value`
#' @export
value.S3Counter <- function(x, ...) {
    .Call(C_S3Counter__value, x)
}

#' @source Generated by miniextendr from `S3Counter::inc`
#' @export
inc.S3Counter <- function(x, ...) {
    .Call(C_S3Counter__inc, x)
}

#' @source Generated by miniextendr from `S3Counter::add`
#' @export
add.S3Counter <- function(x, amount, ...) {
    .Call(C_S3Counter__add, x, amount)
}

#' @source Generated by miniextendr from `S3Counter::default_counter`
#' @export
s3counter_default_counter <- function() {
    structure(.Call(C_S3Counter__default_counter), class = "S3Counter")
}

