#!/usr/bin/env bash
# Tests for the mx-regen merge driver (scripts/merge-driver-regen.sh) and the
# `just merge-drivers-install` recipe, in throwaway repositories that carry
# this checkout's attributes files and driver script.
#
# Covered:
#   - with the driver: a rebase over both-sides changes to an llm-docs file,
#     a pin-only Cargo.lock conflict and rpkg/NAMESPACE (-merge, routed by the
#     install recipe) continues, keeps the current side (our pins, plus the
#     other side's non-conflicting lock edit), and lists each path in
#     $(git rev-parse --git-dir)/mx-regenerate;
#   - a Cargo.lock conflict beyond the pins still stops the rebase, with
#     conflict markers, and is not listed;
#   - without the driver, the llm-docs conflict gets git's default text merge
#     (markers, rebase stops);
#   - without the recipe's info/attributes block, rpkg/NAMESPACE keeps its
#     tracked -merge behaviour (rebase stops, no markers);
#   - in a linked worktree the list lands in that worktree's git dir, and the
#     install recipe is idempotent;
#   - regenerate-merged is a no-op without a list and refuses unknown paths.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

failures=0
pass() { echo "ok - $1"; }
fail() { echo "not ok - $1" >&2; failures=$((failures + 1)); }
check() {
  local name=$1
  shift
  if "$@"; then pass "$name"; else fail "$name"; fi
}

sha_base=1111111111111111111111111111111111111111
sha_main=2222222222222222222222222222222222222222
sha_feature=3333333333333333333333333333333333333333

write_lock() { # <file> <pin> <libc version>
  cat > "$1" <<EOF
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "libc"
version = "$3"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "memchr"
version = "2.7.4"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "miniextendr-api"
version = "0.1.0"
source = "git+https://github.com/A2-ai/miniextendr#$2"
dependencies = [
 "libc",
 "memchr",
]
EOF
}

# Repository with a base commit, then `main` and `feature` commits that both
# change the llm-docs file, the pins in Cargo.lock and rpkg/NAMESPACE.
# <feature libc> lets a scenario add a lock edit beyond the pins on feature.
make_repo() { # <dir> <feature libc version>
  local repo=$1
  git init -q -b main "$repo"
  cd "$repo"
  git config user.email test@example.invalid
  git config user.name test
  git config commit.gpgsign false
  mkdir -p scripts rpkg/src/rust rust-llm-docs/generated
  cp "$root/.gitattributes" .gitattributes
  cp "$root/rpkg/.gitattributes" rpkg/.gitattributes
  cp "$root/scripts/merge-driver-regen.sh" scripts/
  printf 'intro\ngenerated from base\noutro\n' > rust-llm-docs/generated/api.md
  write_lock rpkg/src/rust/Cargo.lock "$sha_base" 0.2.170
  printf 'export(a)\n' > rpkg/NAMESPACE
  printf 'source\n' > src.txt
  git add -A && git commit -qm base

  git checkout -qb feature
  printf 'intro\ngenerated on feature\noutro\n' > rust-llm-docs/generated/api.md
  write_lock rpkg/src/rust/Cargo.lock "$sha_feature" "$2"
  printf 'export(a)\nexport(feature)\n' > rpkg/NAMESPACE
  printf 'source\nfeature change\n' > src.txt
  git commit -qam feature

  git checkout -q main
  printf 'intro\ngenerated on main\noutro\n' > rust-llm-docs/generated/api.md
  write_lock rpkg/src/rust/Cargo.lock "$sha_main" 0.2.170
  printf 'export(a)\nexport(main)\n' > rpkg/NAMESPACE
  git commit -qam main
  git checkout -q feature
}

install_driver() {
  just --justfile "$root/justfile" --working-directory "$PWD" merge-drivers-install > /dev/null
}

regen_list() { cat "$(git rev-parse --git-dir)/mx-regenerate" 2>/dev/null || true; }
listed() { regen_list | grep -qxF -- "$1"; }
not_listed() { ! listed "$1"; }
rebase_ok() { git rebase main > "$tmp/rebase.log" 2>&1; }
rebase_stops() { ! git rebase main > "$tmp/rebase.log" 2>&1; }
has_markers() { grep -q '^<<<<<<< ' "$1"; }
no_markers() { ! has_markers "$1"; }
unmerged() { git ls-files -u -- "$1" | grep -q .; }
same_as_main() { git diff --quiet main -- "$1"; }

# region: driver installed
make_repo "$tmp/installed" 0.2.171
install_driver
check "check-attr routes the -merge paths to the driver after install" \
  test "$(git check-attr merge -- rpkg/NAMESPACE)" = "rpkg/NAMESPACE: merge: mx-regen"
check "rebase continues over generated-file conflicts" rebase_ok
check "llm-docs file keeps the current side" same_as_main rust-llm-docs/generated/api.md
check "NAMESPACE keeps the current side" same_as_main rpkg/NAMESPACE
check "Cargo.lock keeps the current side's pin" \
  grep -qF "miniextendr#$sha_main\"" rpkg/src/rust/Cargo.lock
check "Cargo.lock keeps the other side's non-conflicting edit" \
  grep -qxF 'version = "0.2.171"' rpkg/src/rust/Cargo.lock
check "Cargo.lock has no conflict markers" no_markers rpkg/src/rust/Cargo.lock
check "the replayed source change survives" grep -qxF 'feature change' src.txt
for path in rust-llm-docs/generated/api.md rpkg/NAMESPACE rpkg/src/rust/Cargo.lock; do
  check "$path is listed for regeneration" listed "$path"
done
check "each path is listed once" test "$(regen_list | wc -l | tr -d ' ')" = 3

# Idempotent install, and a linked worktree gets its own list.
install_driver
check "install is idempotent" \
  test "$(grep -c '^# mx-regen: begin' "$(git rev-parse --git-path info/attributes)")" = 1
git branch -q feature2 main~1
git worktree add -q "$tmp/installed-wt" feature2
cd "$tmp/installed-wt"
printf 'intro\ngenerated on feature2\noutro\n' > rust-llm-docs/generated/api.md
printf 'source\nfeature2 change\n' > src.txt
git commit -qam feature2
check "worktree sees the driver for -merge paths" \
  test "$(git check-attr merge -- rpkg/configure)" = "rpkg/configure: merge: mx-regen"
check "worktree rebase continues" rebase_ok
check "worktree list names the llm-docs file" listed rust-llm-docs/generated/api.md
check "worktree list lives in the worktree git dir" \
  test -s "$(git rev-parse --git-common-dir)/worktrees/installed-wt/mx-regenerate"
cd "$tmp/installed"
check "main worktree list is untouched by the worktree rebase" \
  test "$(regen_list | wc -l | tr -d ' ')" = 3
cd "$root"
# endregion

# region: real Cargo.lock conflict
make_repo "$tmp/real-lock" 0.2.171
install_driver
# Change the same libc line differently on main.
git checkout -q main
write_lock rpkg/src/rust/Cargo.lock "$sha_main" 0.2.999
git commit -qam "main libc"
git checkout -q feature
check "rebase stops on a Cargo.lock conflict beyond the pins" rebase_stops
check "Cargo.lock is unmerged" unmerged rpkg/src/rust/Cargo.lock
check "Cargo.lock has conflict markers" has_markers rpkg/src/rust/Cargo.lock
check "Cargo.lock is not listed for regeneration" not_listed rpkg/src/rust/Cargo.lock
git rebase --abort
cd "$root"
# endregion

# region: no driver installed
make_repo "$tmp/no-driver" 0.2.170
check "check-attr names the driver" \
  test "$(git check-attr merge -- rust-llm-docs/generated/api.md)" = "rust-llm-docs/generated/api.md: merge: mx-regen"
check "without the driver the rebase stops" rebase_stops
check "llm-docs file gets default text-merge markers" has_markers rust-llm-docs/generated/api.md
check "NAMESPACE keeps its -merge behaviour (no markers)" no_markers rpkg/NAMESPACE
check "NAMESPACE is unmerged" unmerged rpkg/NAMESPACE
check "nothing is listed" test -z "$(regen_list)"
git rebase --abort
cd "$root"
# endregion

# region: driver without the info/attributes block
make_repo "$tmp/no-override" 0.2.170
install_driver
attributes="$(git rev-parse --git-path info/attributes)"
sed -i.bak '/^# mx-regen: begin/,/^# mx-regen: end/d' "$attributes"
check "check-attr is back to -merge for NAMESPACE" \
  test "$(git check-attr merge -- rpkg/NAMESPACE)" = "rpkg/NAMESPACE: merge: unset"
check "rebase stops on the -merge NAMESPACE" rebase_stops
check "NAMESPACE is unmerged without markers" unmerged rpkg/NAMESPACE
check "NAMESPACE has no markers" no_markers rpkg/NAMESPACE
check "the llm-docs file still went through the driver" listed rust-llm-docs/generated/api.md
git rebase --abort
cd "$root"
# endregion

# region: regenerate-merged bookkeeping
git init -q "$tmp/regen"
cd "$tmp/regen"
regenerate() {
  just --justfile "$root/justfile" --working-directory "$PWD" regenerate-merged > "$tmp/regen.log" 2>&1
}
check "regenerate-merged with no list is a no-op" regenerate
printf 'unknown/generated.txt\n' > "$(git rev-parse --git-dir)/mx-regenerate"
check "regenerate-merged refuses a path it has no step for" eval '! regenerate'
check "the list is kept after a refusal" listed unknown/generated.txt
cd "$root"
# endregion

if [ "$failures" -gt 0 ]; then
  echo "$failures check(s) failed" >&2
  exit 1
fi
echo "all merge-driver checks passed"
