# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: rebuild the package (R CMD INSTALL or devtools::install).
# nolint start
# nocov start

# Internal helper: re-raise a tagged Rust error/condition value as an R condition.
# Generated wrappers call this whenever `.Call()` returns a `rust_condition_value`.
# `.call_default` is the wrapper's `sys.call()`, used as the fallback when the
# Rust panic payload didn't carry a captured call (e.g. lambda contexts that
# pass `.call = NULL` to `.Call`). For error/panic kinds `stop()` longjmps;
# for warning/message/condition the helper signals and returns invisible(NULL),
# which the wrapper's surrounding `return(...)` propagates as its result.
.miniextendr_raise_condition <- function(.val, .call_default) {
  .msg <- .val$error
  .call <- .val$call %||% .call_default
  .class <- .val$class
  switch(.val$kind,
    error = stop(structure(list(message = .msg, call = .call, kind = "error"),
      class = c(.class, "rust_error", "simpleError", "error", "condition"))),
    warning = warning(structure(list(message = .msg, call = .call, kind = "warning"),
      class = c(.class, "rust_warning", "simpleWarning", "warning", "condition"))),
    message = message(structure(list(message = paste0(.msg, "\n"), call = NULL, kind = "message"),
      class = c(.class, "rust_message", "simpleMessage", "message", "condition"))),
    condition = signalCondition(structure(list(message = .msg, call = .call, kind = "condition"),
      class = c(.class, "rust_condition", "simpleCondition", "condition"))),
    panic = stop(structure(list(message = .msg, call = .call, kind = "panic"),
      class = c("rust_error", "simpleError", "error", "condition"))),
    stop(structure(list(message = .msg, call = .call, kind = .val$kind),
      class = c("rust_error", "simpleError", "error", "condition")))
  )
  invisible(NULL)
}

# Generated from Rust impl `R6Point` (lib.rs:130:6)
#' @rdname R6Point
#' @title R6Point (R6-style)
#' @name R6Point
#' @description A 2D point using R6-style class system.
#' @source Generated by miniextendr from Rust type `R6Point`
#' @importFrom R6 R6Class
#' @param .ptr Internal pointer (used by static methods, not for direct use).
#' @export
R6Point <- R6::R6Class("R6Point",
  public = list(
    # R6Point::new (134:12)
    #' @description Create a new point
    #' @param x X coordinate.
    #' @param y Y coordinate.
    initialize = function(x, y, .ptr = NULL) {
      if (is.null(.ptr)) {
        stopifnot(
          "'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x),
          "'x' must have length 1" = length(x) == 1L,
          "'y' must be numeric, logical, or raw" = is.numeric(y) || is.logical(y) || is.raw(y),
          "'y' must have length 1" = length(y) == 1L
        )
      }
      if (!is.null(.ptr)) {
        private$.ptr <- .ptr
      } else {
        .val <- .Call(C_R6Point__new, .call = match.call(), x, y)
        if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
        private$.ptr <- .val
      }
    },
    # R6Point::x (139:12)
    #' @description Get x coordinate
    x = function() {
      .val <- .Call(C_R6Point__x, .call = match.call(), private$.ptr)
      if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
      .val
    },
    # R6Point::y (144:12)
    #' @description Get y coordinate
    y = function() {
      .val <- .Call(C_R6Point__y, .call = match.call(), private$.ptr)
      if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
      .val
    },
    # R6Point::distance_from_origin (149:12)
    #' @description Calculate distance from origin
    distance_from_origin = function() {
      .val <- .Call(C_R6Point__distance_from_origin, .call = match.call(), private$.ptr)
      if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
      .val
    },
    # R6Point::add (156:12)
    #' @description Add to coordinates
    #' @param dx Amount to add to x.
    #' @param dy Amount to add to y.
    add = function(dx, dy) {
      stopifnot(
        "'dx' must be numeric, logical, or raw" = is.numeric(dx) || is.logical(dx) || is.raw(dx),
        "'dx' must have length 1" = length(dx) == 1L,
        "'dy' must be numeric, logical, or raw" = is.numeric(dy) || is.logical(dy) || is.raw(dy),
        "'dy' must have length 1" = length(dy) == 1L
      )
      .val <- .Call(C_R6Point__add, .call = match.call(), private$.ptr, dx, dy)
      if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
      invisible(self)
    }
  ),
  private = list(
    .ptr = NULL
  ),
  lock_objects = TRUE,
  lock_class = FALSE,
  cloneable = FALSE
)

# Generated from Rust impl `S3Point` (lib.rs:182:6)
# S3Point::new (184:12)
#' @rdname S3Point
#' @title S3Point (S3-style)
#' @name S3Point
#' @description A 2D point using S3-style class system.
#' @aliases new_s3point s3point_x s3point_y s3point_distance
#' @description Create a new point
#' @source Generated by miniextendr from Rust type `S3Point`
#' @export
new_s3point <- function(x, y) {
  stopifnot(
    "'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x),
    "'x' must have length 1" = length(x) == 1L,
    "'y' must be numeric, logical, or raw" = is.numeric(y) || is.logical(y) || is.raw(y),
    "'y' must have length 1" = length(y) == 1L
  )
  .val <- .Call(C_S3Point__new, .call = match.call(), x, y)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  structure(.val, class = "S3Point")
}

# S3Point::s3point_x (189:12)
#' @title S3 generic for `s3point_x`
#' S3 generic for `s3point_x`
#' @name s3point_x.S3Point
#' @rdname S3Point
#' @param x An object
#' @param ... Additional arguments passed to methods
#' @source Generated by miniextendr from `S3Point::s3point_x`
#' @export s3point_x
if (!exists("s3point_x", mode = "function")) {
  s3point_x <- function(x, ...) UseMethod("s3point_x")
}

#' @description Get x coordinate
#' @name s3point_x.S3Point
#' @rdname S3Point
#' @source Generated by miniextendr from `S3Point::s3point_x`
#' @method s3point_x S3Point
#' @param x An object.
#' @param ... Additional arguments.
#' @export
s3point_x.S3Point <- function(x, ...) {
  .val <- .Call(C_S3Point__s3point_x, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# S3Point::s3point_y (194:12)
#' @title S3 generic for `s3point_y`
#' S3 generic for `s3point_y`
#' @name s3point_y.S3Point
#' @rdname S3Point
#' @param x An object
#' @param ... Additional arguments passed to methods
#' @source Generated by miniextendr from `S3Point::s3point_y`
#' @export s3point_y
if (!exists("s3point_y", mode = "function")) {
  s3point_y <- function(x, ...) UseMethod("s3point_y")
}

#' @description Get y coordinate
#' @name s3point_y.S3Point
#' @rdname S3Point
#' @source Generated by miniextendr from `S3Point::s3point_y`
#' @method s3point_y S3Point
#' @param x An object.
#' @param ... Additional arguments.
#' @export
s3point_y.S3Point <- function(x, ...) {
  .val <- .Call(C_S3Point__s3point_y, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# S3Point::s3point_distance (199:12)
#' @title S3 generic for `s3point_distance`
#' S3 generic for `s3point_distance`
#' @name s3point_distance.S3Point
#' @rdname S3Point
#' @param x An object
#' @param ... Additional arguments passed to methods
#' @source Generated by miniextendr from `S3Point::s3point_distance`
#' @export s3point_distance
if (!exists("s3point_distance", mode = "function")) {
  s3point_distance <- function(x, ...) UseMethod("s3point_distance")
}

#' @description Calculate distance from origin
#' @name s3point_distance.S3Point
#' @rdname S3Point
#' @source Generated by miniextendr from `S3Point::s3point_distance`
#' @method s3point_distance S3Point
#' @param x An object.
#' @param ... Additional arguments.
#' @export
s3point_distance.S3Point <- function(x, ...) {
  .val <- .Call(C_S3Point__s3point_distance, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# S3Point::s3point_add (204:12)
#' @title S3 generic for `s3point_add`
#' S3 generic for `s3point_add`
#' @name s3point_add.S3Point
#' @rdname S3Point
#' @param x An object
#' @param ... Additional arguments passed to methods
#' @source Generated by miniextendr from `S3Point::s3point_add`
#' @export s3point_add
if (!exists("s3point_add", mode = "function")) {
  s3point_add <- function(x, ...) UseMethod("s3point_add")
}

#' @description Add to coordinates
#' @param dx (undocumented)
#' @param dy (undocumented)
#' @name s3point_add.S3Point
#' @rdname S3Point
#' @source Generated by miniextendr from `S3Point::s3point_add`
#' @method s3point_add S3Point
#' @param x An object.
#' @param ... Additional arguments.
#' @export
s3point_add.S3Point <- function(x, dx, dy, ...) {
  stopifnot(
    "'dx' must be numeric, logical, or raw" = is.numeric(dx) || is.logical(dx) || is.raw(dx),
    "'dx' must have length 1" = length(dx) == 1L,
    "'dy' must be numeric, logical, or raw" = is.numeric(dy) || is.logical(dy) || is.raw(dy),
    "'dy' must have length 1" = length(dy) == 1L
  )
  .val <- .Call(C_S3Point__s3point_add, .call = match.call(), x, dx, dy)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  x
}

#' @rdname S3Point
#' @export
S3Point <- new.env(parent = emptyenv())

S3Point$new <- new_s3point

# Generated from Rust impl `S4Point` (lib.rs:230:6)
#' @rdname S4Point
#' @title S4Point (S4-style)
#' @name S4Point
#' @description A 2D point using S4-style class system.
#' @aliases S4Point s4point_x s4point_y s4point_distance
#' @source Generated by miniextendr from Rust type `S4Point`
#' @importFrom methods setClass setGeneric setMethod new
#' @slot ptr External pointer to Rust `S4Point` struct
methods::setClass("S4Point", slots = c(ptr = "externalptr"))

# S4Point::new (232:12)
#' @description Create a new point
#' @param x (undocumented)
#' @param y (undocumented)
#' @name S4Point
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::new`
#' @export
S4Point <- function(x, y) {
  stopifnot(
    "'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x),
    "'x' must have length 1" = length(x) == 1L,
    "'y' must be numeric, logical, or raw" = is.numeric(y) || is.logical(y) || is.raw(y),
    "'y' must have length 1" = length(y) == 1L
  )
  .val <- .Call(C_S4Point__new, .call = match.call(), x, y)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  methods::new("S4Point", ptr = .val)
}

# S4Point::x (237:12)
#' @description Get x coordinate
#' @name S4Point-s4_x
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::s4_x`
#' @aliases s4_x,S4Point-method
if (!methods::isGeneric("s4_x")) methods::setGeneric("s4_x", function(x, ...) standardGeneric("s4_x"))
#' @exportMethod s4_x
methods::setMethod("s4_x", "S4Point", function(x, ...) {
    .val <- .Call(C_S4Point__x, .call = match.call(), x@ptr)
    if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
    .val
  })

# S4Point::y (242:12)
#' @description Get y coordinate
#' @name S4Point-s4_y
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::s4_y`
#' @aliases s4_y,S4Point-method
if (!methods::isGeneric("s4_y")) methods::setGeneric("s4_y", function(x, ...) standardGeneric("s4_y"))
#' @exportMethod s4_y
methods::setMethod("s4_y", "S4Point", function(x, ...) {
    .val <- .Call(C_S4Point__y, .call = match.call(), x@ptr)
    if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
    .val
  })

# S4Point::distance (247:12)
#' @description Calculate distance from origin
#' @name S4Point-s4_distance
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::s4_distance`
#' @aliases s4_distance,S4Point-method
if (!methods::isGeneric("s4_distance")) methods::setGeneric("s4_distance", function(x, ...) standardGeneric("s4_distance"))
#' @exportMethod s4_distance
methods::setMethod("s4_distance", "S4Point", function(x, ...) {
    .val <- .Call(C_S4Point__distance, .call = match.call(), x@ptr)
    if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
    .val
  })

# S4Point::add (252:12)
#' @description Add to coordinates
#' @name S4Point-s4_add
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::s4_add`
#' @aliases s4_add,S4Point-method
if (!methods::isGeneric("s4_add")) methods::setGeneric("s4_add", function(x, ...) standardGeneric("s4_add"))
#' @exportMethod s4_add
methods::setMethod("s4_add", "S4Point", function(x, dx, dy, ...) {
  stopifnot(
    "'dx' must be numeric, logical, or raw" = is.numeric(dx) || is.logical(dx) || is.raw(dx),
    "'dx' must have length 1" = length(dx) == 1L,
    "'dy' must be numeric, logical, or raw" = is.numeric(dy) || is.logical(dy) || is.raw(dy),
    "'dy' must have length 1" = length(dy) == 1L
  )
  {
    .val <- .Call(C_S4Point__add, .call = match.call(), x@ptr, dx, dy)
    if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
    x
  }
})

# Generated from Rust impl `S7Point` (lib.rs:278:6)
#' @rdname S7Point
#' @title S7Point (S7-style)
#' @name S7Point
#' @description A 2D point using S7-style class system.
#' @aliases S7Point s7point_x s7point_y s7point_distance
#' @source Generated by miniextendr from Rust type `S7Point`
#' @importFrom S7 new_class class_any new_object S7_object new_generic method
#' @export
#' @param x (undocumented)
#' @param y (undocumented)
#' @param .ptr Internal pointer (used by static methods, not for direct use).
S7Point <- S7::new_class("S7Point",
  properties = list(
    .ptr = S7::class_any
  ),
  constructor = function(x, y, .ptr = NULL) {
    if (is.null(.ptr)) {
      stopifnot(
        "'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x),
        "'x' must have length 1" = length(x) == 1L,
        "'y' must be numeric, logical, or raw" = is.numeric(y) || is.logical(y) || is.raw(y),
        "'y' must have length 1" = length(y) == 1L
      )
    }
    if (!is.null(.ptr)) {
      S7::new_object(S7::S7_object(), .ptr = .ptr)
    } else {
      .val <- .Call(C_S7Point__new, .call = match.call(), x, y)
      if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
      S7::new_object(S7::S7_object(), .ptr = .val)
    }
  }
)

# S7Point::s7point_x (285:12)
#' @description Get x coordinate
#' @name S7Point-s7point_x
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_x`
#' @aliases S7Point$s7point_x
#' @rawNamespace export(s7point_x)
if (!exists("s7point_x", mode = "function")) {
  s7point_x <- S7::new_generic("s7point_x", "x", function(x, ...) S7::S7_dispatch())
}
S7::method(s7point_x, S7Point) <- function(x, ...) {
    .val <- .Call(C_S7Point__s7point_x, .call = match.call(), x@.ptr)
    if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
    .val
  }

# S7Point::s7point_y (290:12)
#' @description Get y coordinate
#' @name S7Point-s7point_y
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_y`
#' @aliases S7Point$s7point_y
#' @rawNamespace export(s7point_y)
if (!exists("s7point_y", mode = "function")) {
  s7point_y <- S7::new_generic("s7point_y", "x", function(x, ...) S7::S7_dispatch())
}
S7::method(s7point_y, S7Point) <- function(x, ...) {
    .val <- .Call(C_S7Point__s7point_y, .call = match.call(), x@.ptr)
    if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
    .val
  }

# S7Point::s7point_distance (295:12)
#' @description Calculate distance from origin
#' @name S7Point-s7point_distance
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_distance`
#' @aliases S7Point$s7point_distance
#' @rawNamespace export(s7point_distance)
if (!exists("s7point_distance", mode = "function")) {
  s7point_distance <- S7::new_generic("s7point_distance", "x", function(x, ...) S7::S7_dispatch())
}
S7::method(s7point_distance, S7Point) <- function(x, ...) {
    .val <- .Call(C_S7Point__s7point_distance, .call = match.call(), x@.ptr)
    if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
    .val
  }

# S7Point::s7point_add (300:12)
#' @description Add to coordinates
#' @name S7Point-s7point_add
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_add`
#' @aliases S7Point$s7point_add
#' @rawNamespace export(s7point_add)
if (!exists("s7point_add", mode = "function")) {
  s7point_add <- S7::new_generic("s7point_add", "x", function(x, ...) S7::S7_dispatch())
}
S7::method(s7point_add, S7Point) <- function(x, dx, dy, ...) {
  stopifnot(
    "'dx' must be numeric, logical, or raw" = is.numeric(dx) || is.logical(dx) || is.raw(dx),
    "'dx' must have length 1" = length(dx) == 1L,
    "'dy' must be numeric, logical, or raw" = is.numeric(dy) || is.logical(dy) || is.raw(dy),
    "'dy' must have length 1" = length(dy) == 1L
  )
  {
    .val <- .Call(C_S7Point__s7point_add, .call = match.call(), x@.ptr, dx, dy)
    if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
    x
  }
}

# Generated from Rust impl `EnvPoint` (lib.rs:83:6)
#' @rdname EnvPoint
#' @title EnvPoint (Env-style)
#' @name EnvPoint
#' @description A 2D point using the default Env-style class system.
#' @source Generated by miniextendr from Rust type `EnvPoint`
#' @export
EnvPoint <- new.env(parent = emptyenv())

# EnvPoint::new (85:8)
#' @description Create a new point
#' @name EnvPoint$new
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::new`
EnvPoint$new <- function(x, y) {
  stopifnot(
    "'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x),
    "'x' must have length 1" = length(x) == 1L,
    "'y' must be numeric, logical, or raw" = is.numeric(y) || is.logical(y) || is.raw(y),
    "'y' must have length 1" = length(y) == 1L
  )
  .val <- .Call(C_EnvPoint__new, .call = match.call(), x, y)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  self <- .val
  class(self) <- "EnvPoint"
  self
}

# EnvPoint::x (90:8)
#' @description Get x coordinate
#' @name EnvPoint$x
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::x`
EnvPoint$x <- function() {
  .val <- .Call(C_EnvPoint__x, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# EnvPoint::y (95:8)
#' @description Get y coordinate
#' @name EnvPoint$y
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::y`
EnvPoint$y <- function() {
  .val <- .Call(C_EnvPoint__y, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# EnvPoint::distance_from_origin (100:8)
#' @description Calculate distance from origin
#' @name EnvPoint$distance_from_origin
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::distance_from_origin`
EnvPoint$distance_from_origin <- function() {
  .val <- .Call(C_EnvPoint__distance_from_origin, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# EnvPoint::add (105:8)
#' @description Add another point's coordinates
#' @name EnvPoint$add
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::add`
EnvPoint$add <- function(dx, dy) {
  stopifnot(
    "'dx' must be numeric, logical, or raw" = is.numeric(dx) || is.logical(dx) || is.raw(dx),
    "'dx' must have length 1" = length(dx) == 1L,
    "'dy' must be numeric, logical, or raw" = is.numeric(dy) || is.logical(dy) || is.raw(dy),
    "'dy' must have length 1" = length(dy) == 1L
  )
  .val <- .Call(C_EnvPoint__add, .call = match.call(), self, dx, dy)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  self
}

#' @rdname EnvPoint
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.EnvPoint` <- function(self, name) {
  obj <- EnvPoint[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level -- search trait namespace environments
    for (ns_name in names(EnvPoint)) {
      ns <- EnvPoint[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method -- bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @rdname EnvPoint
#' @export
`[[.EnvPoint` <- `$.EnvPoint`

# Generated from Rust impl `SharedData` (lib.rs:45:6)
#' @rdname SharedData
#' @title SharedData (Env-style)
#' @name SharedData
#' @description A point with label using Env-style class system.
#' @source Generated by miniextendr from Rust type `SharedData`
#' @export
SharedData <- new.env(parent = emptyenv())

# SharedData::get_x (52:8)
#' @description Get the x coordinate
#' @name SharedData$get_x
#' @rdname SharedData
#' @source Generated by miniextendr from `SharedData::get_x`
SharedData$get_x <- function() {
  .val <- .Call(C_SharedData__get_x, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# SharedData::get_y (57:8)
#' @description Get the y coordinate
#' @name SharedData$get_y
#' @rdname SharedData
#' @source Generated by miniextendr from `SharedData::get_y`
SharedData$get_y <- function() {
  .val <- .Call(C_SharedData__get_y, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# SharedData::get_label (62:8)
#' @description Get the label
#' @name SharedData$get_label
#' @rdname SharedData
#' @source Generated by miniextendr from `SharedData::get_label`
SharedData$get_label <- function() {
  .val <- .Call(C_SharedData__get_label, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# SharedData::create (47:8)
#' @description Create a new SharedData
#' @name SharedData$create
#' @rdname SharedData
#' @source Generated by miniextendr from `SharedData::create`
SharedData$create <- function(x, y, label) {
  stopifnot(
    "'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x),
    "'x' must have length 1" = length(x) == 1L,
    "'y' must be numeric, logical, or raw" = is.numeric(y) || is.logical(y) || is.raw(y),
    "'y' must have length 1" = length(y) == 1L,
    "'label' must be character" = is.character(label),
    "'label' must have length 1" = length(label) == 1L
  )
  .val <- .Call(C_SharedData__create, .call = match.call(), x, y, label)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  class(.val) <- "SharedData"
  .val
}

#' @rdname SharedData
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.SharedData` <- function(self, name) {
  obj <- SharedData[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level -- search trait namespace environments
    for (ns_name in names(SharedData)) {
      ns <- SharedData[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method -- bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @rdname SharedData
#' @export
`[[.SharedData` <- `$.SharedData`

# Generated from Rust impl `SimpleCounter` (lib.rs:321:6)
#' @title SimpleCounter  Class
#' @name SimpleCounter
#' @rdname SimpleCounter
#' @source Generated by miniextendr from Rust type `SimpleCounter`
#' @export
SimpleCounter <- new.env(parent = emptyenv())

# SimpleCounter::get_value (323:8)
#' @description Get current value (inherent method)
#' @name SimpleCounter$get_value
#' @rdname SimpleCounter
#' @source Generated by miniextendr from `SimpleCounter::get_value`
SimpleCounter$get_value <- function() {
  .val <- .Call(C_SimpleCounter__get_value, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

#' @rdname SimpleCounter
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.SimpleCounter` <- function(self, name) {
  obj <- SimpleCounter[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level -- search trait namespace environments
    for (ns_name in names(SimpleCounter)) {
      ns <- SimpleCounter[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method -- bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @rdname SimpleCounter
#' @export
`[[.SimpleCounter` <- `$.SimpleCounter`

# Generated from Rust impl `StatefulCounter` (lib.rs:390:6)
#' @title StatefulCounter  Class
#' @name StatefulCounter
#' @rdname StatefulCounter
#' @source Generated by miniextendr from Rust type `StatefulCounter`
#' @export
StatefulCounter <- new.env(parent = emptyenv())

# StatefulCounter::get_value (392:8)
#' @description Get current value (inherent method)
#' @name StatefulCounter$get_value
#' @rdname StatefulCounter
#' @source Generated by miniextendr from `StatefulCounter::get_value`
StatefulCounter$get_value <- function() {
  .val <- .Call(C_StatefulCounter__get_value, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# StatefulCounter::history_len (397:8)
#' @description Get how many history entries exist
#' @name StatefulCounter$history_len
#' @rdname StatefulCounter
#' @source Generated by miniextendr from `StatefulCounter::history_len`
StatefulCounter$history_len <- function() {
  .val <- .Call(C_StatefulCounter__history_len, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

#' @rdname StatefulCounter
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.StatefulCounter` <- function(self, name) {
  obj <- StatefulCounter[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level -- search trait namespace environments
    for (ns_name in names(StatefulCounter)) {
      ns <- StatefulCounter[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method -- bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @rdname StatefulCounter
#' @export
`[[.StatefulCounter` <- `$.StatefulCounter`

# Generated from Rust fn `get_r_class` (lib.rs:510:8)
#' @title Get class of any R object (for cross-package testing)
#' @param x Any R object
#' @return Character vector of class names
#' @export
#' @source Generated by miniextendr from Rust fn `get_r_class`
get_r_class <- function(x) {
  .val <- .Call(C_get_r_class, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `new_counter` (lib.rs:463:8)
#' @title Create a new counter with cross-package trait dispatch support
#' @param initial Initial counter value
#' @return An external pointer to the wrapped counter
#' @export
#' @source Generated by miniextendr from Rust fn `new_counter`
new_counter <- function(initial) {
  stopifnot(
    "'initial' must be numeric, logical, or raw" = is.numeric(initial) || is.logical(initial) || is.raw(initial),
    "'initial' must have length 1" = length(initial) == 1L
  )
  .val <- .Call(C_new_counter, .call = match.call(), initial)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `counter_get_value` (lib.rs:474:8)
#' @title Get the value from a trait-wrapped counter
#' @param counter_sexp An external pointer from new_counter()
#' @return The counter's current value
#' @export
#' @source Generated by miniextendr from Rust fn `counter_get_value`
counter_get_value <- function(counter_sexp) {
  .val <- .Call(C_counter_get_value, .call = match.call(), counter_sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `debug_tag_counter` (lib.rs:486:8)
#' @title Debug: Get TAG_COUNTER as hex string
#' @export
#' @source Generated by miniextendr from Rust fn `debug_tag_counter`
debug_tag_counter <- function() {
  .val <- .Call(C_debug_tag_counter, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `debug_tag_resettable` (lib.rs:493:8)
#' @title Debug: Get TAG_RESETTABLE as hex string
#' @export
#' @source Generated by miniextendr from Rust fn `debug_tag_resettable`
debug_tag_resettable <- function() {
  .val <- .Call(C_debug_tag_resettable, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `new_stateful_counter` (lib.rs:452:8)
#' @title Create a new StatefulCounter with cross-package trait dispatch support
#' @param initial Initial counter value
#' @return An external pointer to the wrapped stateful counter
#' @export
#' @source Generated by miniextendr from Rust fn `new_stateful_counter`
new_stateful_counter <- function(initial) {
  stopifnot(
    "'initial' must be numeric, logical, or raw" = is.numeric(initial) || is.logical(initial) || is.raw(initial),
    "'initial' must have length 1" = length(initial) == 1L
  )
  .val <- .Call(C_new_stateful_counter, .call = match.call(), initial)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `debug_shared_data_type_name` (lib.rs:500:8)
#' @title Debug: Get the ExternalPtr type name for SharedData
#' @export
#' @source Generated by miniextendr from Rust fn `debug_shared_data_type_name`
debug_shared_data_type_name <- function() {
  .val <- .Call(C_debug_shared_data_type_name, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust impl `Counter` for `SimpleCounter` (lib.rs:329:18)
# Trait methods and consts for SimpleCounter implementing Counter
# Generated by #[miniextendr] impl Counter for SimpleCounter

SimpleCounter$Counter <- new.env(parent = emptyenv())

#' @name SimpleCounter$Counter$value
#' @rdname SimpleCounter
SimpleCounter$Counter$value <- function(x) {
  .Call(C_SimpleCounter__Counter__value, .call = match.call(), x)
}
attr(SimpleCounter$Counter$value, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$increment
#' @rdname SimpleCounter
SimpleCounter$Counter$increment <- function(x) {
  .Call(C_SimpleCounter__Counter__increment, .call = match.call(), x)
  invisible(x)
}
attr(SimpleCounter$Counter$increment, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$add
#' @rdname SimpleCounter
SimpleCounter$Counter$add <- function(x, n) {
  .Call(C_SimpleCounter__Counter__add, .call = match.call(), x, n)
  invisible(x)
}
attr(SimpleCounter$Counter$add, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$panic_plain
#' @rdname SimpleCounter
SimpleCounter$Counter$panic_plain <- function(x) {
  .Call(C_SimpleCounter__Counter__panic_plain, .call = match.call(), x)
  invisible(x)
}
attr(SimpleCounter$Counter$panic_plain, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$error_with_class
#' @rdname SimpleCounter
SimpleCounter$Counter$error_with_class <- function(x, class_name) {
  .Call(C_SimpleCounter__Counter__error_with_class, .call = match.call(), x, class_name)
  invisible(x)
}
attr(SimpleCounter$Counter$error_with_class, ".__mx_instance__") <- TRUE

# Generated from Rust impl `Counter` for `StatefulCounter` (lib.rs:403:18)
# Trait methods and consts for StatefulCounter implementing Counter
# Generated by #[miniextendr] impl Counter for StatefulCounter

StatefulCounter$Counter <- new.env(parent = emptyenv())

#' @name StatefulCounter$Counter$value
#' @rdname StatefulCounter
StatefulCounter$Counter$value <- function(x) {
  .Call(C_StatefulCounter__Counter__value, .call = match.call(), x)
}
attr(StatefulCounter$Counter$value, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$increment
#' @rdname StatefulCounter
StatefulCounter$Counter$increment <- function(x) {
  .Call(C_StatefulCounter__Counter__increment, .call = match.call(), x)
  invisible(x)
}
attr(StatefulCounter$Counter$increment, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$add
#' @rdname StatefulCounter
StatefulCounter$Counter$add <- function(x, n) {
  .Call(C_StatefulCounter__Counter__add, .call = match.call(), x, n)
  invisible(x)
}
attr(StatefulCounter$Counter$add, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$panic_plain
#' @rdname StatefulCounter
StatefulCounter$Counter$panic_plain <- function(x) {
  .Call(C_StatefulCounter__Counter__panic_plain, .call = match.call(), x)
  invisible(x)
}
attr(StatefulCounter$Counter$panic_plain, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$error_with_class
#' @rdname StatefulCounter
StatefulCounter$Counter$error_with_class <- function(x, class_name) {
  .Call(C_StatefulCounter__Counter__error_with_class, .call = match.call(), x, class_name)
  invisible(x)
}
attr(StatefulCounter$Counter$error_with_class, ".__mx_instance__") <- TRUE

# Generated from Rust impl `Resettable` for `SimpleCounter` (lib.rs:361:21)
# Trait methods and consts for SimpleCounter implementing Resettable
# Generated by #[miniextendr] impl Resettable for SimpleCounter

SimpleCounter$Resettable <- new.env(parent = emptyenv())

#' @name SimpleCounter$Resettable$reset
#' @rdname SimpleCounter
SimpleCounter$Resettable$reset <- function(x) {
  .Call(C_SimpleCounter__Resettable__reset, .call = match.call(), x)
  invisible(x)
}
attr(SimpleCounter$Resettable$reset, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Resettable$is_default
#' @rdname SimpleCounter
SimpleCounter$Resettable$is_default <- function(x) {
  .Call(C_SimpleCounter__Resettable__is_default, .call = match.call(), x)
}
attr(SimpleCounter$Resettable$is_default, ".__mx_instance__") <- TRUE

# Generated from Rust impl `Resettable` for `StatefulCounter` (lib.rs:435:21)
# Trait methods and consts for StatefulCounter implementing Resettable
# Generated by #[miniextendr] impl Resettable for StatefulCounter

StatefulCounter$Resettable <- new.env(parent = emptyenv())

#' @name StatefulCounter$Resettable$reset
#' @rdname StatefulCounter
StatefulCounter$Resettable$reset <- function(x) {
  .Call(C_StatefulCounter__Resettable__reset, .call = match.call(), x)
  invisible(x)
}
attr(StatefulCounter$Resettable$reset, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Resettable$is_default
#' @rdname StatefulCounter
StatefulCounter$Resettable$is_default <- function(x) {
  .Call(C_StatefulCounter__Resettable__is_default, .call = match.call(), x)
}
attr(StatefulCounter$Resettable$is_default, ".__mx_instance__") <- TRUE

# nocov end
# nolint end
