# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: run `just devtools-document` or rebuild the package.
# nolint start
# nocov start

#' @title Create a new counter with cross-package trait dispatch support
#' @param initial Initial counter value
#' @return An external pointer to the wrapped counter
#' @export
#' @source Generated by miniextendr from Rust fn `new_counter`
new_counter <- function(initial) {
    .Call(C_new_counter, .call = match.call(), initial)
}

#' @title Get the value from a trait-wrapped counter
#' @param counter_sexp An external pointer from new_counter()
#' @return The counter's current value
#' @export
#' @source Generated by miniextendr from Rust fn `counter_get_value`
counter_get_value <- function(counter_sexp) {
    .Call(C_counter_get_value, .call = match.call(), counter_sexp)
}

#' @title Debug: Get the ExternalPtr type name for SharedData
#' @export
#' @source Generated by miniextendr from Rust fn `debug_shared_data_type_name`
debug_shared_data_type_name <- function() {
    .Call(C_debug_shared_data_type_name, .call = match.call())
}

#' @title Debug: Get TAG_COUNTER as hex string
#' @export
#' @source Generated by miniextendr from Rust fn `debug_tag_counter`
debug_tag_counter <- function() {
    .Call(C_debug_tag_counter, .call = match.call())
}

#' @title Get class of any R object (for cross-package testing)
#' @param x Any R object
#' @return Character vector of class names
#' @export
#' @source Generated by miniextendr from Rust fn `get_r_class`
get_r_class <- function(x) {
    .Call(C_get_r_class, .call = match.call(), x)
}



#' @rdname SharedData
#' @title SharedData (Env-style)
#' @name SharedData
#' @description A point with label using Env-style class system.
#' @examples
#' p <- SharedData$create(1.0, 2.0, "origin")
#' p$get_x()
#' p$get_y()
#' p$get_label()
#' @source Generated by miniextendr from Rust type `SharedData`
#' @export
SharedData <- new.env(parent = emptyenv())

#' @description Get the x coordinate
#' @name SharedData$get_x
#' @rdname SharedData
#' @source Generated by miniextendr from `SharedData::get_x`
SharedData$get_x <- function() {
    .Call(C_SharedData__get_x, .call = match.call(), self)
}

#' @description Get the y coordinate
#' @name SharedData$get_y
#' @rdname SharedData
#' @source Generated by miniextendr from `SharedData::get_y`
SharedData$get_y <- function() {
    .Call(C_SharedData__get_y, .call = match.call(), self)
}

#' @description Get the label
#' @name SharedData$get_label
#' @rdname SharedData
#' @source Generated by miniextendr from `SharedData::get_label`
SharedData$get_label <- function() {
    .Call(C_SharedData__get_label, .call = match.call(), self)
}

#' @description Create a new SharedData
#' @name SharedData$create
#' @rdname SharedData
#' @source Generated by miniextendr from `SharedData::create`
SharedData$create <- function(x, y, label) {
    result <- .Call(C_SharedData__create, .call = match.call(), x, y, label)
    class(result) <- "SharedData"
    result
}

#' @rdname SharedData
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.SharedData` <- function(self, name) {
    obj <- SharedData[[name]]
    if (is.environment(obj)) {
        # Trait namespace - bind self to all methods
        bound <- new.env(parent = emptyenv())
        for (method_name in names(obj)) {
            method <- obj[[method_name]]
            if (is.function(method)) {
                environment(method) <- environment()
                bound[[method_name]] <- method
            }
        }
        bound
    } else {
        environment(obj) <- environment()
        obj
    }
}
#' @rdname SharedData
#' @export
`[[.SharedData` <- `$.SharedData`

#' @rdname EnvPoint
#' @title EnvPoint (Env-style)
#' @name EnvPoint
#' @description A 2D point using the default Env-style class system.
#' @examples
#' p <- EnvPoint$new(3.0, 4.0)
#' p$x()
#' p$y()
#' p$distance_from_origin()
#' @source Generated by miniextendr from Rust type `EnvPoint`
#' @export
EnvPoint <- new.env(parent = emptyenv())

#' @description Create a new point
#' @name EnvPoint$new
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::new`
EnvPoint$new <- function(x, y) {
    self <- .Call(C_EnvPoint__new, .call = match.call(), x, y)
    class(self) <- "EnvPoint"
    self
}

#' @description Get x coordinate
#' @name EnvPoint$x
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::x`
EnvPoint$x <- function() {
    .Call(C_EnvPoint__x, .call = match.call(), self)
}

#' @description Get y coordinate
#' @name EnvPoint$y
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::y`
EnvPoint$y <- function() {
    .Call(C_EnvPoint__y, .call = match.call(), self)
}

#' @description Calculate distance from origin
#' @name EnvPoint$distance_from_origin
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::distance_from_origin`
EnvPoint$distance_from_origin <- function() {
    .Call(C_EnvPoint__distance_from_origin, .call = match.call(), self)
}

#' @description Add another point's coordinates
#' @name EnvPoint$add
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::add`
EnvPoint$add <- function(dx, dy) {
    .Call(C_EnvPoint__add, .call = match.call(), self, dx, dy)
    self
}

#' @rdname EnvPoint
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.EnvPoint` <- function(self, name) {
    obj <- EnvPoint[[name]]
    if (is.environment(obj)) {
        # Trait namespace - bind self to all methods
        bound <- new.env(parent = emptyenv())
        for (method_name in names(obj)) {
            method <- obj[[method_name]]
            if (is.function(method)) {
                environment(method) <- environment()
                bound[[method_name]] <- method
            }
        }
        bound
    } else {
        environment(obj) <- environment()
        obj
    }
}
#' @rdname EnvPoint
#' @export
`[[.EnvPoint` <- `$.EnvPoint`

#' @rdname R6Point
#' @title R6Point (R6-style)
#' @name R6Point
#' @description A 2D point using R6-style class system.
#' @examples
#' p <- R6Point$new(3.0, 4.0)
#' p$x()
#' p$y()
#' p$distance_from_origin()
#' @source Generated by miniextendr from Rust type `R6Point`
#' @importFrom R6 R6Class
#' @param .ptr Internal pointer (used by static methods, not for direct use).
#' @export
R6Point <- R6::R6Class("R6Point",
    public = list(
        #' @description Create a new point
        initialize = function(x, y, .ptr = NULL) {
            if (!is.null(.ptr)) {
                private$.ptr <- .ptr
            } else {
                private$.ptr <- .Call(C_R6Point__new, .call = match.call(), x, y)
            }
        },
        #' @description Get x coordinate
        x = function() {
            .Call(C_R6Point__x, .call = match.call(), private$.ptr)
        },
        #' @description Get y coordinate
        y = function() {
            .Call(C_R6Point__y, .call = match.call(), private$.ptr)
        },
        #' @description Calculate distance from origin
        distance_from_origin = function() {
            .Call(C_R6Point__distance_from_origin, .call = match.call(), private$.ptr)
        },
        #' @description Add to coordinates
        add = function(dx, dy) {
            .Call(C_R6Point__add, .call = match.call(), private$.ptr, dx, dy)
            invisible(self)
        }
    ),
    private = list(
        .ptr = NULL
    ),
    lock_objects = TRUE,
    lock_class = FALSE,
    cloneable = FALSE
)

#' @rdname S3Point
#' @title S3Point (S3-style)
#' @name S3Point
#' @description A 2D point using S3-style class system.
#' @aliases new_s3point s3point_x s3point_y s3point_distance
#' @examples
#' p <- new_s3point(3.0, 4.0)
#' s3point_x(p)
#' s3point_y(p)
#' s3point_distance(p)
#' @description Create a new point
#' @source Generated by miniextendr from Rust type `S3Point`
#' @export
new_s3point <- function(x, y) {
    structure(.Call(C_S3Point__new, .call = match.call(), x, y), class = "S3Point")
}

#' @title S3 generic for `s3point_x`
#' S3 generic for `s3point_x`
#' @rdname S3Point
#' @name s3point_x
#' @param x An object
#' @param ... Additional arguments passed to methods
#' @source Generated by miniextendr from `S3Point::s3point_x`
#' @export
if (!exists("s3point_x", mode = "function")) {
    s3point_x <- function(x, ...) UseMethod("s3point_x")
}

#' @description Get x coordinate
#' @name s3point_x
#' @rdname S3Point
#' @source Generated by miniextendr from `S3Point::s3point_x`
#' @method s3point_x S3Point
#' @export
s3point_x.S3Point <- function(x, ...) {
    .Call(C_S3Point__s3point_x, .call = match.call(), x)
}

#' @title S3 generic for `s3point_y`
#' S3 generic for `s3point_y`
#' @rdname S3Point
#' @name s3point_y
#' @param x An object
#' @param ... Additional arguments passed to methods
#' @source Generated by miniextendr from `S3Point::s3point_y`
#' @export
if (!exists("s3point_y", mode = "function")) {
    s3point_y <- function(x, ...) UseMethod("s3point_y")
}

#' @description Get y coordinate
#' @name s3point_y
#' @rdname S3Point
#' @source Generated by miniextendr from `S3Point::s3point_y`
#' @method s3point_y S3Point
#' @export
s3point_y.S3Point <- function(x, ...) {
    .Call(C_S3Point__s3point_y, .call = match.call(), x)
}

#' @title S3 generic for `s3point_distance`
#' S3 generic for `s3point_distance`
#' @rdname S3Point
#' @name s3point_distance
#' @param x An object
#' @param ... Additional arguments passed to methods
#' @source Generated by miniextendr from `S3Point::s3point_distance`
#' @export
if (!exists("s3point_distance", mode = "function")) {
    s3point_distance <- function(x, ...) UseMethod("s3point_distance")
}

#' @description Calculate distance from origin
#' @name s3point_distance
#' @rdname S3Point
#' @source Generated by miniextendr from `S3Point::s3point_distance`
#' @method s3point_distance S3Point
#' @export
s3point_distance.S3Point <- function(x, ...) {
    .Call(C_S3Point__s3point_distance, .call = match.call(), x)
}

#' @title S3 generic for `s3point_add`
#' S3 generic for `s3point_add`
#' @rdname S3Point
#' @name s3point_add
#' @param x An object
#' @param ... Additional arguments passed to methods
#' @source Generated by miniextendr from `S3Point::s3point_add`
#' @export
if (!exists("s3point_add", mode = "function")) {
    s3point_add <- function(x, ...) UseMethod("s3point_add")
}

#' @description Add to coordinates
#' @name s3point_add
#' @rdname S3Point
#' @source Generated by miniextendr from `S3Point::s3point_add`
#' @method s3point_add S3Point
#' @export
s3point_add.S3Point <- function(x, dx, dy, ...) {
    .Call(C_S3Point__s3point_add, .call = match.call(), x, dx, dy)
    x
}

#' @rdname S3Point
#' @export
S3Point <- new.env(parent = emptyenv())

S3Point$new <- new_s3point

#' @rdname S4Point
#' @title S4Point (S4-style)
#' @name S4Point
#' @description A 2D point using S4-style class system.
#' @aliases S4Point s4point_x s4point_y s4point_distance
#' @examples
#' p <- S4Point(3.0, 4.0)
#' s4point_x(p)
#' s4point_y(p)
#' s4point_distance(p)
#' @source Generated by miniextendr from Rust type `S4Point`
#' @importFrom methods setClass setGeneric setMethod new
#' @slot ptr External pointer to Rust `S4Point` struct
methods::setClass("S4Point", slots = c(ptr = "externalptr"))

#' @description Create a new point
#' @name new
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::new`
#' @export
S4Point <- function(x, y) {
    methods::new("S4Point", ptr = .Call(C_S4Point__new, .call = match.call(), x, y))
}

#' @description Get x coordinate
#' @name s4_x
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::s4_x`
methods::setGeneric("s4_x", function(x, ...) standardGeneric("s4_x"))
#' @exportMethod s4_x
methods::setMethod("s4_x", "S4Point", function(x, ...) .Call(C_S4Point__x, .call = match.call(), x@ptr))

#' @description Get y coordinate
#' @name s4_y
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::s4_y`
methods::setGeneric("s4_y", function(x, ...) standardGeneric("s4_y"))
#' @exportMethod s4_y
methods::setMethod("s4_y", "S4Point", function(x, ...) .Call(C_S4Point__y, .call = match.call(), x@ptr))

#' @description Calculate distance from origin
#' @name s4_distance
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::s4_distance`
methods::setGeneric("s4_distance", function(x, ...) standardGeneric("s4_distance"))
#' @exportMethod s4_distance
methods::setMethod("s4_distance", "S4Point", function(x, ...) .Call(C_S4Point__distance, .call = match.call(), x@ptr))

#' @description Add to coordinates
#' @name s4_add
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::s4_add`
methods::setGeneric("s4_add", function(x, ...) standardGeneric("s4_add"))
#' @exportMethod s4_add
methods::setMethod("s4_add", "S4Point", function(x, dx, dy, ...) { .Call(C_S4Point__add, .call = match.call(), x@ptr, dx, dy); x })

#' @rdname S7Point
#' @title S7Point (S7-style)
#' @name S7Point
#' @description A 2D point using S7-style class system.
#' @aliases S7Point s7point_x s7point_y s7point_distance
#' @examples
#' p <- S7Point(3.0, 4.0)
#' s7point_x(p)
#' s7point_y(p)
#' s7point_distance(p)
#' @source Generated by miniextendr from Rust type `S7Point`
#' @importFrom S7 new_class class_any new_object S7_object new_generic method
#' @export
#' @param .ptr Internal pointer (used by static methods, not for direct use).
S7Point <- S7::new_class("S7Point",
    properties = list(
        .ptr = S7::class_any
    ),
    constructor = function(x, y, .ptr = NULL) {
        if (!is.null(.ptr)) {
            S7::new_object(S7::S7_object(), .ptr = .ptr)
        } else {
            S7::new_object(S7::S7_object(), .ptr = .Call(C_S7Point__new, .call = match.call(), x, y))
        }
    }
)

#' @description Get x coordinate
#' @name s7point_x
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_x`
#' @export
if (!exists("s7point_x", mode = "function")) s7point_x <- S7::new_generic("s7point_x", "x", function(x, ...) S7::S7_dispatch())
S7::method(s7point_x, S7Point) <- function(x, ...) .Call(C_S7Point__s7point_x, .call = match.call(), x@.ptr)

#' @description Get y coordinate
#' @name s7point_y
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_y`
#' @export
if (!exists("s7point_y", mode = "function")) s7point_y <- S7::new_generic("s7point_y", "x", function(x, ...) S7::S7_dispatch())
S7::method(s7point_y, S7Point) <- function(x, ...) .Call(C_S7Point__s7point_y, .call = match.call(), x@.ptr)

#' @description Calculate distance from origin
#' @name s7point_distance
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_distance`
#' @export
if (!exists("s7point_distance", mode = "function")) s7point_distance <- S7::new_generic("s7point_distance", "x", function(x, ...) S7::S7_dispatch())
S7::method(s7point_distance, S7Point) <- function(x, ...) .Call(C_S7Point__s7point_distance, .call = match.call(), x@.ptr)

#' @description Add to coordinates
#' @name s7point_add
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_add`
#' @export
if (!exists("s7point_add", mode = "function")) s7point_add <- S7::new_generic("s7point_add", "x", function(x, ...) S7::S7_dispatch())
S7::method(s7point_add, S7Point) <- function(x, dx, dy, ...) { .Call(C_S7Point__s7point_add, .call = match.call(), x@.ptr, dx, dy); x }

#' @title SimpleCounter  Class
#' @name SimpleCounter
#' @rdname SimpleCounter
#' @source Generated by miniextendr from Rust type `SimpleCounter`
#' @export
SimpleCounter <- new.env(parent = emptyenv())

#' @description Get current value (inherent method)
#' @name SimpleCounter$get_value
#' @rdname SimpleCounter
#' @source Generated by miniextendr from `SimpleCounter::get_value`
SimpleCounter$get_value <- function() {
    .Call(C_SimpleCounter__get_value, .call = match.call(), self)
}

#' @rdname SimpleCounter
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.SimpleCounter` <- function(self, name) {
    obj <- SimpleCounter[[name]]
    if (is.environment(obj)) {
        # Trait namespace - bind self to all methods
        bound <- new.env(parent = emptyenv())
        for (method_name in names(obj)) {
            method <- obj[[method_name]]
            if (is.function(method)) {
                environment(method) <- environment()
                bound[[method_name]] <- method
            }
        }
        bound
    } else {
        environment(obj) <- environment()
        obj
    }
}
#' @rdname SimpleCounter
#' @export
`[[.SimpleCounter` <- `$.SimpleCounter`

# Trait methods and consts for SimpleCounter implementing Counter
# Generated by #[miniextendr] impl Counter for SimpleCounter

SimpleCounter$Counter <- new.env(parent = emptyenv())

#' @name SimpleCounter$Counter$value
#' @rdname SimpleCounter
SimpleCounter$Counter$value <- function(x) {
    .Call(C_SimpleCounter__Counter__value, .call = match.call(), x)
}

#' @name SimpleCounter$Counter$increment
#' @rdname SimpleCounter
SimpleCounter$Counter$increment <- function(x) {
    .Call(C_SimpleCounter__Counter__increment, .call = match.call(), x)
}

#' @name SimpleCounter$Counter$add
#' @rdname SimpleCounter
SimpleCounter$Counter$add <- function(x, n) {
    .Call(C_SimpleCounter__Counter__add, .call = match.call(), x, n)
}

# nocov end
# nolint end
