# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: run `just devtools-document` or rebuild the package.
# nolint start
# nocov start

# Generated from Rust fn `passthrough_ptr` (lib.rs:24:8)
#' @title Pass an ExternalPtr through consumer without knowing its type
#' @param ptr An ExternalPtr from any package
#' @return The same ExternalPtr (pass-through)
#' @export
#' @source Generated by miniextendr from Rust fn `passthrough_ptr`
passthrough_ptr <- function(ptr) {
  .Call(C_passthrough_ptr, .call = match.call(), ptr)
}

# Generated from Rust fn `is_external_ptr` (lib.rs:33:8)
#' @title Check if a SEXP is an ExternalPtr (type-agnostic check)
#' @param sexp Any R object
#' @return TRUE if it's an ExternalPtr
#' @export
#' @source Generated by miniextendr from Rust fn `is_external_ptr`
is_external_ptr <- function(sexp) {
  .Call(C_is_external_ptr, .call = match.call(), sexp)
}

# Generated from Rust fn `consumer_get_class` (lib.rs:43:8)
#' @title Get class of any R object (for cross-package testing)
#' @param x Any R object
#' @return Character vector of class names
#' @export
#' @source Generated by miniextendr from Rust fn `consumer_get_class`
consumer_get_class <- function(x) {
  .Call(C_consumer_get_class, .call = match.call(), x)
}

# Generated from Rust fn `has_class` (lib.rs:53:8)
#' @title Check if an object has a specific class
#' @param x Any R object
#' @param class_name Class name to check for
#' @return TRUE if object has the specified class
#' @export
#' @source Generated by miniextendr from Rust fn `has_class`
has_class <- function(x, class_name) {
  .Call(C_has_class, .call = match.call(), x, class_name)
}

# Generated from Rust fn `new_double_counter` (lib.rs:119:8)
#' @title Create a new DoubleCounter (consumer's own Counter implementation) DoubleCounter increments by 2, demonstrating a different implementation
#' @param initial Initial counter value
#' @return An external pointer to the wrapped DoubleCounter
#' @export
#' @source Generated by miniextendr from Rust fn `new_double_counter`
new_double_counter <- function(initial) {
  .Call(C_new_double_counter, .call = match.call(), initial)
}

# Generated from Rust fn `increment_twice` (lib.rs:135:8)
#' @title Increment a counter twice (generic over Counter trait) This function works with Counter objects from ANY package
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @return The counter's value after incrementing twice
#' @export
#' @source Generated by miniextendr from Rust fn `increment_twice`
increment_twice <- function(counter_sexp) {
  .Call(C_increment_twice, .call = match.call(), counter_sexp)
}

# Generated from Rust fn `add_and_get` (lib.rs:148:8)
#' @title Add a value to a counter and return the new value
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param n Value to add
#' @return The counter's value after adding n
#' @export
#' @source Generated by miniextendr from Rust fn `add_and_get`
add_and_get <- function(counter_sexp, n) {
  .Call(C_add_and_get, .call = match.call(), counter_sexp, n)
}

# Generated from Rust fn `peek_value` (lib.rs:159:8)
#' @title Get value without modifying (uses immutable reference)
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @return The counter's current value
#' @export
#' @source Generated by miniextendr from Rust fn `peek_value`
peek_value <- function(counter_sexp) {
  .Call(C_peek_value, .call = match.call(), counter_sexp)
}

# Generated from Rust fn `is_counter` (lib.rs:169:8)
#' @title Check if an object implements the Counter trait
#' @param sexp Any R object
#' @return TRUE if the object implements Counter trait
#' @export
#' @source Generated by miniextendr from Rust fn `is_counter`
is_counter <- function(sexp) {
  .Call(C_is_counter, .call = match.call(), sexp)
}

# Generated from Rust fn `consumer_greet` (lib.rs:182:8)
#' @title Greet with a message demonstrating consumer package is working
#' @param name Name to greet
#' @return A greeting string
#' @export
#' @source Generated by miniextendr from Rust fn `consumer_greet`
consumer_greet <- function(name) {
  .Call(C_consumer_greet, .call = match.call(), name)
}

# Generated from Rust fn `consumer_magic_number` (lib.rs:190:8)
#' @title Return a constant to verify the package is loaded
#' @return The number 42
#' @export
#' @source Generated by miniextendr from Rust fn `consumer_magic_number`
consumer_magic_number <- function() {
  .Call(C_consumer_magic_number, .call = match.call())
}

# Generated from Rust fn `debug_consumer_tag_counter` (lib.rs:197:8)
#' @title Debug: Get TAG_COUNTER as hex string
#' @export
#' @source Generated by miniextendr from Rust fn `debug_consumer_tag_counter`
debug_consumer_tag_counter <- function() {
  .Call(C_debug_consumer_tag_counter, .call = match.call())
}



# Generated from Rust impl `DoubleCounter` (lib.rs:87:6)
#' @title DoubleCounter  Class
#' @name DoubleCounter
#' @rdname DoubleCounter
#' @source Generated by miniextendr from Rust type `DoubleCounter`
#' @export
DoubleCounter <- new.env(parent = emptyenv())

#' @description Get the current value (inherent method)
#' @name DoubleCounter$get_value
#' @rdname DoubleCounter
#' @source Generated by miniextendr from `DoubleCounter::get_value`
DoubleCounter$get_value <- function() {
  .Call(C_DoubleCounter__get_value, .call = match.call(), self)
}

#' @name DoubleCounter$create
#' @rdname DoubleCounter
#' @source Generated by miniextendr from `DoubleCounter::create`
DoubleCounter$create <- function(initial) {
  result <- .Call(C_DoubleCounter__create, .call = match.call(), initial)
  class(result) <- "DoubleCounter"
  result
}

#' @rdname DoubleCounter
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.DoubleCounter` <- function(self, name) {
  obj <- DoubleCounter[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level — search trait namespace environments
    for (ns_name in names(DoubleCounter)) {
      ns <- DoubleCounter[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method — bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @rdname DoubleCounter
#' @export
`[[.DoubleCounter` <- `$.DoubleCounter`

# Generated from Rust impl `Counter` for `DoubleCounter` (lib.rs:99:18)
# Trait methods and consts for DoubleCounter implementing Counter
# Generated by #[miniextendr] impl Counter for DoubleCounter

DoubleCounter$Counter <- new.env(parent = emptyenv())

#' @name DoubleCounter$Counter$value
#' @rdname DoubleCounter
DoubleCounter$Counter$value <- function(x) {
  .Call(C_DoubleCounter__Counter__value, .call = match.call(), x)
}
attr(DoubleCounter$Counter$value, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$increment
#' @rdname DoubleCounter
DoubleCounter$Counter$increment <- function(x) {
  .Call(C_DoubleCounter__Counter__increment, .call = match.call(), x)
  invisible(x)
}
attr(DoubleCounter$Counter$increment, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$add
#' @rdname DoubleCounter
DoubleCounter$Counter$add <- function(x, n) {
  .Call(C_DoubleCounter__Counter__add, .call = match.call(), x, n)
  invisible(x)
}
attr(DoubleCounter$Counter$add, ".__mx_instance__") <- TRUE

# nocov end
# nolint end
