# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# miniextendr-api 0.1.0 | fnv1a-64 of the normalized lines below: 3e01e9d8d895e544
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: rebuild the package (R CMD INSTALL or devtools::install).
# nolint start
# nocov start

# Internal helper: re-raise a tagged Rust error/condition value as an R condition.
# Generated wrappers call this whenever `.Call()` returns a `rust_condition_value`.
# `.call_default` is the wrapper's `sys.call()` (or its caller-derived
# `.mx_call` for `#[miniextendr(noexport, call = caller)]` entry points), used as the
# fallback when the Rust panic payload didn't carry a captured call (e.g.
# lambda contexts that pass `.call = NULL` to `.Call`). For error/panic kinds `stop()` longjmps;
# for warning/message/condition the helper signals and returns invisible(NULL),
# which the wrapper's surrounding `return(...)` propagates as its result.
.miniextendr_raise_condition <- function(.val, .call_default) {
  .msg <- .val$error
  .call <- (if (is.null(.val$call)) .call_default else .val$call)
  .class <- .val$class
  # `.val$data` is an optional named list of structured fields (from the
  # macros' `data = ...` form). When present, splice its named elements into
  # the condition object alongside message/call/kind so handlers can read
  # `e$<name>`. `utils::modifyList` keeps the base fields and appends the
  # data fields; a malformed (non-list / unnamed) payload is ignored.
  # `keep.null = TRUE`: a field the Rust side set to `RValue::Null` is a
  # present field whose value is NULL, and must stay in `names(e)`; the
  # default would silently drop it (found downstream via a
  # `RConditionError::data()` returning an explicit NULL entry).
  .data <- .val$data
  .cond_fields <- function(base) {
    if (is.null(.data) || !is.list(.data) || is.null(names(.data))) {
      base
    } else {
      utils::modifyList(base, .data, keep.null = TRUE)
    }
  }
  switch(.val$kind,
    error = stop(structure(.cond_fields(list(message = .msg, call = .call, kind = "error")),
      class = c(.class, "rust_error", "simpleError", "error", "condition"))),
    warning = warning(structure(.cond_fields(list(message = .msg, call = .call, kind = "warning")),
      class = c(.class, "rust_warning", "simpleWarning", "warning", "condition"))),
    message = message(structure(.cond_fields(list(message = paste0(.msg, "\n"), call = NULL, kind = "message")),
      class = c(.class, "rust_message", "simpleMessage", "message", "condition"))),
    condition = signalCondition(structure(.cond_fields(list(message = .msg, call = .call, kind = "condition")),
      class = c(.class, "rust_condition", "simpleCondition", "condition"))),
    panic = stop(structure(list(message = .msg, call = .call, kind = "panic"),
      class = c("rust_error", "simpleError", "error", "condition"))),
    # result_err / none_err / conversion / other: an error whose class vector and
    # data (if any) come from the Rust side, e.g. a `Result<T, E: RConditionError>`.
    stop(structure(.cond_fields(list(message = .msg, call = .call, kind = .val$kind)),
      class = c(.class, "rust_error", "simpleError", "error", "condition")))
  )
  invisible(NULL)
}

# Internal helper: the call a `#[miniextendr(noexport, call = caller)]` wrapper
# attributes its conditions to (#1450, #1548, #1552). Called as the wrapper's
# first statement, `.mx_call <- .miniextendr_caller_call()`, so the calling
# chain is [caller's caller] <- [caller] <- [wrapper] <- [this helper]:
# `sys.parent(1L)` is the wrapper's frame, `sys.parent(2L)` its caller's. When
# that caller is a closure, the result is the caller's call with the caller's
# formals matched; `envir` is the frame the caller's call was evaluated in,
# where a literal `...` in that call is bound (`function(...) verb(...)`,
# `lapply()`'s `FUN(X[[i]], ...)`; #1462). Otherwise (top level, or an `eval()`
# frame such as a testthat block, `source()` or `local()`, whose frame function
# is not a closure) it falls back to the wrapper's own matched call. Every
# `sys.*` lookup is a plain statement in this helper's frame, never a promise
# forced inside `match.call()`, where `sys.call(0)` would resolve to
# `match.call`'s frame.
.miniextendr_caller_call <- function() {
  wrapper <- sys.parent(1L)
  parent <- sys.parent(2L)
  def <- if (parent > 0L) sys.function(parent)
  if (typeof(def) == "closure") {
    match.call(def, sys.call(parent), envir = parent.frame(3L))
  } else {
    match.call(sys.function(wrapper), sys.call(wrapper), envir = parent.frame(2L))
  }
}

# Internal helper: raise an argument error from an R-side check (#1591): a
# type / length precondition, `no_na`, `inherits`, or a `match_arg` /
# `choices` value. The condition is the one a failed Rust conversion raises:
# the crate's `conversion_error_class` (`.miniextendr_conversion_error_class`,
# at the end of this preamble), then `rust_error`, with
# `kind = "conversion"` and `e$param`, so one handler catches an argument
# error whichever side finds it. The message is `'<param>' <what>`. `call`
# defaults to the wrapper's own call, as `stopifnot()` reported it; a
# `call = caller` wrapper passes `.mx_call` (#1548). Only a failing check
# calls this: the passing path is one `isTRUE()` test per check.
.miniextendr_arg_error <- function(param, what, call = sys.call(-1L)) {
  stop(structure(
    list(message = sprintf("'%s' %s", param, what), call = call, kind = "conversion", param = param),
    class = c(.miniextendr_conversion_error_class, "rust_error", "simpleError", "error", "condition")
  ))
}

# Internal helper: strict `match.arg(several.ok = TRUE)` for `several_ok` params.
# Base R keeps only the elements that match as long as one of them does, so a
# misspelled entry silently shortens the selection and the per-element check on
# the Rust side never sees it (#1472). Here every element has to match a choice
# (exactly or as a unique prefix), the first that does not is reported with its
# position, and `NULL` selects every choice, like an omitted argument does. A
# factor is read as its labels. The error is an argument error
# (`.miniextendr_arg_error`) attributed to `call`: by default the wrapper's own
# call, not this helper; a `call = caller` wrapper passes its caller's matched
# call (#1548).
.miniextendr_match_arg_several <- function(arg, choices, arg_name, call = sys.call(-1L)) {
  if (is.null(arg)) return(choices)
  if (is.factor(arg)) arg <- as.character(arg)
  if (!is.character(arg)) .miniextendr_arg_error(arg_name, "must be NULL or a character vector", call)
  if (length(arg) == 0L) .miniextendr_arg_error(arg_name, "must be of length >= 1", call)
  i <- pmatch(arg, choices, nomatch = 0L, duplicates.ok = TRUE)
  bad <- which(is.na(i) | i == 0L)
  if (length(bad)) {
    .miniextendr_arg_error(arg_name, sprintf("element %d (\"%s\") should be one of %s", bad[[1L]], arg[[bad[[1L]]]], paste(dQuote(choices, FALSE), collapse = ", ")), call)
  }
  choices[i]
}

# Internal helper: scalar `match.arg()` for `match_arg` / `choices` params.
# `base::match.arg()` says `'arg'` in its messages and reports its own frame;
# this names the argument and raises an argument error
# (`.miniextendr_arg_error`) attributed to `call`: by default the wrapper's own
# call, for a `call = caller` wrapper its caller's matched call (#1548).
# Semantics follow `match.arg(arg, choices)`: `NULL` and the full choice vector
# (the formal default) select the first choice; otherwise exactly one string
# that matches a choice exactly or as a unique prefix. A factor is read as its
# labels (#1552).
.miniextendr_match_arg <- function(arg, choices, arg_name, call = sys.call(-1L)) {
  if (is.null(arg)) return(choices[[1L]])
  if (is.factor(arg)) arg <- as.character(arg)
  if (!is.character(arg)) .miniextendr_arg_error(arg_name, "must be NULL or a character vector", call)
  if (identical(arg, choices)) return(arg[[1L]])
  if (length(arg) != 1L) .miniextendr_arg_error(arg_name, "must be of length 1", call)
  i <- pmatch(arg, choices, nomatch = 0L, duplicates.ok = TRUE)
  if (is.na(i) || i == 0L) {
    .miniextendr_arg_error(arg_name, sprintf("should be one of %s", paste(dQuote(choices, FALSE), collapse = ", ")), call)
  }
  choices[[i]]
}

# Internal: the crate's `conversion_error_class` ([package.metadata.miniextendr]),
# the classes of every argument error ahead of `rust_error`; NULL when unset.
.miniextendr_conversion_error_class <- NULL

# Generated from Rust impl `DoubleCounter` (lib.rs:84:6)
#' @title DoubleCounter  Class
#' @name DoubleCounter
#' @rdname DoubleCounter
#' @export
DoubleCounter <- new.env(parent = emptyenv())

# DoubleCounter::get_value (90:8)
#' @description Get the current value (inherent method)
#' @name DoubleCounter$get_value
#' @rdname DoubleCounter
DoubleCounter$get_value <- function() {
  .val <- .Call(C_consumer_pkg_DoubleCounter__get_value, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# DoubleCounter::create (85:8)
#' @name DoubleCounter$create
#' @rdname DoubleCounter
DoubleCounter$create <- function(initial) {
  if (!isTRUE(is.integer(initial))) .miniextendr_arg_error("initial", "must be integer")
  if (!isTRUE(length(initial) == 1L)) .miniextendr_arg_error("initial", "must have length 1")
  .val <- .Call(C_consumer_pkg_DoubleCounter__create, .call = match.call(), initial)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  class(.val) <- "DoubleCounter"
  .val
}

#' @rdname DoubleCounter
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.DoubleCounter` <- function(self, name) {
  obj <- DoubleCounter[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level -- search trait namespace environments
    for (ns_name in names(DoubleCounter)) {
      ns <- DoubleCounter[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method -- bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @rdname DoubleCounter
#' @export
`[[.DoubleCounter` <- `$.DoubleCounter`

# Generated from Rust fn `passthrough_ptr` (lib.rs:29:8)
#' @title passthrough_ptr
#' @description Pass an ExternalPtr through consumer without knowing its type. This tests that ExternalPtr can cross package boundaries as opaque SEXP.
#' @param ptr An ExternalPtr from any package
#' @return The same ExternalPtr (pass-through)
#' @export
passthrough_ptr <- function(ptr) {
  .val <- .Call(C_consumer_pkg_passthrough_ptr, .call = match.call(), ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `is_external_ptr` (lib.rs:38:8)
#' @title is_external_ptr
#' @description Check if a SEXP is an ExternalPtr (type-agnostic check)
#' @param sexp Any R object
#' @return TRUE if it's an ExternalPtr
#' @export
is_external_ptr <- function(sexp) {
  .val <- .Call(C_consumer_pkg_is_external_ptr, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `consumer_get_class` (lib.rs:48:8)
#' @title consumer_get_class
#' @description Get class of any R object (for cross-package testing)
#' @param x Any R object
#' @return Character vector of class names
#' @export
consumer_get_class <- function(x) {
  .val <- .Call(C_consumer_pkg_consumer_get_class, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `has_class` (lib.rs:58:8)
#' @title has_class
#' @description Check if an object has a specific class
#' @param x Any R object
#' @param class_name Class name to check for
#' @return TRUE if object has the specified class
#' @export
has_class <- function(x, class_name) {
  if (!isTRUE(is.character(class_name))) .miniextendr_arg_error("class_name", "must be character")
  if (!isTRUE(length(class_name) == 1L)) .miniextendr_arg_error("class_name", "must have length 1")
  .val <- .Call(C_consumer_pkg_has_class, .call = match.call(), x, class_name)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `new_double_counter` (lib.rs:161:8)
#' @title new_double_counter
#' @description Create a new DoubleCounter (consumer's own Counter implementation) DoubleCounter increments by 2, demonstrating a different implementation.
#' @param initial Initial counter value
#' @return An external pointer to the wrapped DoubleCounter
#' @export
new_double_counter <- function(initial) {
  if (!isTRUE(is.integer(initial))) .miniextendr_arg_error("initial", "must be integer")
  if (!isTRUE(length(initial) == 1L)) .miniextendr_arg_error("initial", "must have length 1")
  .val <- .Call(C_consumer_pkg_new_double_counter, .call = match.call(), initial)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `increment_twice` (lib.rs:176:8)
#' @title increment_twice
#' @description Increment a counter twice (generic over Counter trait) This function works with Counter objects from ANY package.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @return The counter's value after incrementing twice
#' @export
increment_twice <- function(counter_sexp) {
  .val <- .Call(C_consumer_pkg_increment_twice, .call = match.call(), counter_sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `add_and_get` (lib.rs:189:8)
#' @title add_and_get
#' @description Add a value to a counter and return the new value
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param n Value to add
#' @return The counter's value after adding n
#' @export
add_and_get <- function(counter_sexp, n) {
  if (!isTRUE(is.integer(n))) .miniextendr_arg_error("n", "must be integer")
  if (!isTRUE(length(n) == 1L)) .miniextendr_arg_error("n", "must have length 1")
  .val <- .Call(C_consumer_pkg_add_and_get, .call = match.call(), counter_sexp, n)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `peek_value` (lib.rs:200:8)
#' @title peek_value
#' @description Get value without modifying (uses immutable reference)
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @return The counter's current value
#' @export
peek_value <- function(counter_sexp) {
  .val <- .Call(C_consumer_pkg_peek_value, .call = match.call(), counter_sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `is_counter` (lib.rs:210:8)
#' @title is_counter
#' @description Check if an object implements the Counter trait
#' @param sexp Any R object
#' @return TRUE if the object implements Counter trait
#' @export
is_counter <- function(sexp) {
  .val <- .Call(C_consumer_pkg_is_counter, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `reset_and_check` (lib.rs:223:8)
#' @title reset_and_check
#' @description Reset an object and check if it's in default state This function works with Resettable objects from ANY package.
#' @param sexp An ExternalPtr to any type implementing Resettable
#' @return TRUE if the object is in default state after reset
#' @export
reset_and_check <- function(sexp) {
  .val <- .Call(C_consumer_pkg_reset_and_check, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `check_is_default` (lib.rs:234:8)
#' @title check_is_default
#' @description Check if an object is in its default state (without resetting)
#' @param sexp An ExternalPtr to any type implementing Resettable
#' @return TRUE if the object is in default state
#' @export
check_is_default <- function(sexp) {
  .val <- .Call(C_consumer_pkg_check_is_default, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `is_resettable` (lib.rs:244:8)
#' @title is_resettable
#' @description Check if an object implements the Resettable trait
#' @param sexp Any R object
#' @return TRUE if the object implements Resettable trait
#' @export
is_resettable <- function(sexp) {
  .val <- .Call(C_consumer_pkg_is_resettable, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `increment_then_reset` (lib.rs:257:8)
#' @title increment_then_reset
#' @description Increment a Counter twice, then reset it via Resettable, return is_default Tests combined trait usage on the same object across packages.
#' @param sexp An ExternalPtr to a type implementing BOTH Counter and Resettable
#' @return TRUE if the object is in default state after increment+reset
#' @export
increment_then_reset <- function(sexp) {
  .val <- .Call(C_consumer_pkg_increment_then_reset, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `get_reset_get` (lib.rs:275:8)
#' @title get_reset_get
#' @description Get the value of a Counter, reset it, then get the value again Returns the value after reset.
#' @param sexp An ExternalPtr to a type implementing BOTH Counter and Resettable
#' @return The counter value after reset
#' @export
get_reset_get <- function(sexp) {
  .val <- .Call(C_consumer_pkg_get_reset_get, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `debug_consumer_tag_resettable` (lib.rs:288:8)
#' @title debug_consumer_tag_resettable
#' @description Debug: Get TAG_RESETTABLE as hex string
#' @export
debug_consumer_tag_resettable <- function() {
  .val <- .Call(C_consumer_pkg_debug_consumer_tag_resettable, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `counter_panic_plain` (lib.rs:302:8)
#' @title counter_panic_plain
#' @description Call panic_plain() on any Counter object via trait dispatch.
#' 
#' Used by spike tests to verify rust_error class layering across the trait-ABI boundary.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @export
counter_panic_plain <- function(counter_sexp) {
  .val <- .Call(C_consumer_pkg_counter_panic_plain, .call = match.call(), counter_sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `counter_error_with_class` (lib.rs:315:8)
#' @title counter_error_with_class
#' @description Call error_with_class() on any Counter object via trait dispatch.
#' 
#' Used by spike tests to verify user-class layering across the trait-ABI boundary.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param class_name The class name to use with error!()
#' @export
counter_error_with_class <- function(counter_sexp, class_name) {
  if (!isTRUE(is.character(class_name))) .miniextendr_arg_error("class_name", "must be character")
  if (!isTRUE(length(class_name) == 1L)) .miniextendr_arg_error("class_name", "must have length 1")
  .val <- .Call(C_consumer_pkg_counter_error_with_class, .call = match.call(), counter_sexp, class_name)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `counter_raise_error` (lib.rs:329:8)
#' @title counter_raise_error
#' @description Raise a bare error!() through a Counter trait method via trait dispatch.
#' 
#' Verifies that a producer-side `error!()` round-trips to `rust_error` / `e$kind == "error"` across the trait-ABI boundary, matching the in-process matrix's free-fn / R6 error rows.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param msg The error message
#' @export
counter_raise_error <- function(counter_sexp, msg) {
  if (!isTRUE(is.character(msg))) .miniextendr_arg_error("msg", "must be character")
  if (!isTRUE(length(msg) == 1L)) .miniextendr_arg_error("msg", "must have length 1")
  .val <- .Call(C_consumer_pkg_counter_raise_error, .call = match.call(), counter_sexp, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `counter_raise_warning` (lib.rs:343:8)
#' @title counter_raise_warning
#' @description Raise a warning!() through a Counter trait method via trait dispatch.
#' 
#' Verifies that a producer-side `warning!()` round-trips to `rust_warning` / `e$kind == "warning"` across the trait-ABI boundary, matching the in-process matrix's R6/S3/S4/S7 warning rows.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param msg The warning message
#' @export
counter_raise_warning <- function(counter_sexp, msg) {
  if (!isTRUE(is.character(msg))) .miniextendr_arg_error("msg", "must be character")
  if (!isTRUE(length(msg) == 1L)) .miniextendr_arg_error("msg", "must have length 1")
  .val <- .Call(C_consumer_pkg_counter_raise_warning, .call = match.call(), counter_sexp, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `counter_raise_message` (lib.rs:357:8)
#' @title counter_raise_message
#' @description Raise a message!() through a Counter trait method via trait dispatch.
#' 
#' Verifies that a producer-side `message!()` round-trips to `rust_message` / `e$kind == "message"` across the trait-ABI boundary, matching the in-process matrix's message rows.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param msg The message body
#' @export
counter_raise_message <- function(counter_sexp, msg) {
  if (!isTRUE(is.character(msg))) .miniextendr_arg_error("msg", "must be character")
  if (!isTRUE(length(msg) == 1L)) .miniextendr_arg_error("msg", "must have length 1")
  .val <- .Call(C_consumer_pkg_counter_raise_message, .call = match.call(), counter_sexp, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `counter_raise_condition_classed` (lib.rs:373:8)
#' @title counter_raise_condition_classed
#' @description Raise a classed condition!() through a Counter trait method via trait dispatch.
#' 
#' Verifies that a producer-side `condition!(class = …)` is catchable by the user class and round-trips to `e$kind == "condition"` across the trait-ABI boundary, matching the in-process matrix's condition!() rows.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param class_name The class name to use with condition!()
#' @param msg The condition message
#' @export
counter_raise_condition_classed <- function(counter_sexp, class_name, msg) {
  if (!isTRUE(is.character(class_name))) .miniextendr_arg_error("class_name", "must be character")
  if (!isTRUE(length(class_name) == 1L)) .miniextendr_arg_error("class_name", "must have length 1")
  if (!isTRUE(is.character(msg))) .miniextendr_arg_error("msg", "must be character")
  if (!isTRUE(length(msg) == 1L)) .miniextendr_arg_error("msg", "must have length 1")
  .val <- .Call(C_consumer_pkg_counter_raise_condition_classed, .call = match.call(), counter_sexp, class_name, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `counter_raise_error_with_data` (lib.rs:391:8)
#' @title counter_raise_error_with_data
#' @description Raise an error!() with structured `data =` fields through a Counter trait method via trait dispatch.
#' 
#' Exercises the `from_tagged_sexp` slot 4 round-trip path (issue #996 path-1): producer raises `error!(class = "data_bearing_error", data = [...], "msg")`, the vtable shim returns a tagged SEXP, `repanic_if_rust_error` reconstructs the `RCondition` (including data), and the consumer's `with_r_unwind_protect` guard re-emits a new tagged SEXP with the data intact.
#' 
#' R handlers can then access `e$field_a`, `e$field_b`, `e$flag`, `e$score`.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @export
counter_raise_error_with_data <- function(counter_sexp) {
  .val <- .Call(C_consumer_pkg_counter_raise_error_with_data, .call = match.call(), counter_sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `consumer_greet` (lib.rs:405:8)
#' @title consumer_greet
#' @description Greet with a message demonstrating consumer package is working
#' @param name Name to greet
#' @return A greeting string
#' @export
consumer_greet <- function(name) {
  if (!isTRUE(is.character(name))) .miniextendr_arg_error("name", "must be character")
  if (!isTRUE(length(name) == 1L)) .miniextendr_arg_error("name", "must have length 1")
  .val <- .Call(C_consumer_pkg_consumer_greet, .call = match.call(), name)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `consumer_magic_number` (lib.rs:413:8)
#' @title consumer_magic_number
#' @description Return a constant to verify the package is loaded
#' @return The number 42
#' @export
consumer_magic_number <- function() {
  .val <- .Call(C_consumer_pkg_consumer_magic_number, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `debug_consumer_tag_counter` (lib.rs:420:8)
#' @title debug_consumer_tag_counter
#' @description Debug: Get TAG_COUNTER as hex string
#' @export
debug_consumer_tag_counter <- function() {
  .val <- .Call(C_consumer_pkg_debug_consumer_tag_counter, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust impl `Counter` for `DoubleCounter` (lib.rs:96:18)
# Trait methods and consts for DoubleCounter implementing Counter
# Generated by #[miniextendr] impl Counter for DoubleCounter

DoubleCounter$Counter <- new.env(parent = emptyenv())

#' @name DoubleCounter$Counter$value
#' @rdname DoubleCounter
DoubleCounter$Counter$value <- function(x) {
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__value, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}
attr(DoubleCounter$Counter$value, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$increment
#' @rdname DoubleCounter
DoubleCounter$Counter$increment <- function(x) {
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__increment, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  x
}
attr(DoubleCounter$Counter$increment, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$add
#' @rdname DoubleCounter
DoubleCounter$Counter$add <- function(x, n) {
  if (!isTRUE(is.integer(n))) .miniextendr_arg_error("n", "must be integer")
  if (!isTRUE(length(n) == 1L)) .miniextendr_arg_error("n", "must have length 1")
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__add, .call = match.call(), x, n)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  x
}
attr(DoubleCounter$Counter$add, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$panic_plain
#' @rdname DoubleCounter
DoubleCounter$Counter$panic_plain <- function(x) {
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__panic_plain, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  x
}
attr(DoubleCounter$Counter$panic_plain, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$error_with_class
#' @rdname DoubleCounter
DoubleCounter$Counter$error_with_class <- function(x, class_name) {
  if (!isTRUE(is.character(class_name))) .miniextendr_arg_error("class_name", "must be character")
  if (!isTRUE(length(class_name) == 1L)) .miniextendr_arg_error("class_name", "must have length 1")
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__error_with_class, .call = match.call(), x, class_name)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  x
}
attr(DoubleCounter$Counter$error_with_class, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$raise_error
#' @rdname DoubleCounter
DoubleCounter$Counter$raise_error <- function(x, msg) {
  if (!isTRUE(is.character(msg))) .miniextendr_arg_error("msg", "must be character")
  if (!isTRUE(length(msg) == 1L)) .miniextendr_arg_error("msg", "must have length 1")
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__raise_error, .call = match.call(), x, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  x
}
attr(DoubleCounter$Counter$raise_error, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$raise_warning
#' @rdname DoubleCounter
DoubleCounter$Counter$raise_warning <- function(x, msg) {
  if (!isTRUE(is.character(msg))) .miniextendr_arg_error("msg", "must be character")
  if (!isTRUE(length(msg) == 1L)) .miniextendr_arg_error("msg", "must have length 1")
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__raise_warning, .call = match.call(), x, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  x
}
attr(DoubleCounter$Counter$raise_warning, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$raise_message
#' @rdname DoubleCounter
DoubleCounter$Counter$raise_message <- function(x, msg) {
  if (!isTRUE(is.character(msg))) .miniextendr_arg_error("msg", "must be character")
  if (!isTRUE(length(msg) == 1L)) .miniextendr_arg_error("msg", "must have length 1")
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__raise_message, .call = match.call(), x, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  x
}
attr(DoubleCounter$Counter$raise_message, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$raise_condition_classed
#' @rdname DoubleCounter
DoubleCounter$Counter$raise_condition_classed <- function(x, class_name, msg) {
  if (!isTRUE(is.character(class_name))) .miniextendr_arg_error("class_name", "must be character")
  if (!isTRUE(length(class_name) == 1L)) .miniextendr_arg_error("class_name", "must have length 1")
  if (!isTRUE(is.character(msg))) .miniextendr_arg_error("msg", "must be character")
  if (!isTRUE(length(msg) == 1L)) .miniextendr_arg_error("msg", "must have length 1")
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__raise_condition_classed, .call = match.call(), x, class_name, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  x
}
attr(DoubleCounter$Counter$raise_condition_classed, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$raise_error_with_data
#' @rdname DoubleCounter
DoubleCounter$Counter$raise_error_with_data <- function(x) {
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__raise_error_with_data, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  x
}
attr(DoubleCounter$Counter$raise_error_with_data, ".__mx_instance__") <- TRUE

# nocov end
# nolint end
