# Tests for miniextendr_build()'s and miniextendr_build_tarball()'s step order
# and guards (#860, #1288, #1294, #1549).
#
# The wrappers file is written by the Makevars wrapper-gen rule, roxygen2
# reads it to write NAMESPACE and man/, and the install ships all three. So
# the steps run in dependency order: compile + regenerate wrappers in the
# source tree (pkgbuild::compile_dll, which never loads the namespace) ->
# devtools::document() -> one devtools::install(). Earlier versions installed
# first and papered over the resulting one-build lag with a conditional
# reinstall (#860) and a deferred install failure (#1288); an edited doc
# comment still never reached the installed help (#1549).
#
# These tests are behavioural-through-mocks (pkgbuild::compile_dll,
# devtools::install/document + the internal autoconf/configure helpers), NOT
# deparse(body) greps -- see minirextendr/CLAUDE.md's brittle-test gotcha.
# The real compile/roxygen/install round-trip is covered by the gated e2e
# tests in test-templates.R.

make_build_pkg_root <- function(wrappers = TRUE) {
  tmp <- tempfile("workflow-build-")
  dir.create(tmp)
  writeLines(
    "Package: testpkg\nTitle: Test\nVersion: 0.1.0\n",
    file.path(tmp, "DESCRIPTION")
  )
  writeLines(
    "# Generated by roxygen2: do not edit by hand\n",
    file.path(tmp, "NAMESPACE")
  )
  dir.create(file.path(tmp, "R"))
  # The mocked compile_dll writes nothing, so pre-seed the wrappers file the
  # real Makevars rule would have produced; `wrappers = FALSE` models a compile
  # that produced none.
  if (wrappers) writeLines("# generated", file.path(tmp, "R", "testpkg-wrappers.R"))
  tmp
}

# Mock the three external steps, recording the order they run in. `state` is
# an environment so the mocks can append from inside testthat's binding.
mock_build_steps <- function(state,
                             compile = function() invisible(NULL),
                             document = function() invisible(NULL),
                             install = function() invisible(NULL)) {
  record <- function(step, body) {
    force(step)
    force(body)
    function(...) {
      state$calls <- c(state$calls, step)
      body()
    }
  }
  testthat::local_mocked_bindings(
    compile_dll = record("compile_dll", compile),
    .package = "pkgbuild",
    .env = parent.frame()
  )
  testthat::local_mocked_bindings(
    document = record("document", document),
    install = record("install", install),
    .package = "devtools",
    .env = parent.frame()
  )
  # document() leaves the package's development namespace loaded; the
  # workflow unloads it. `state$dev_loaded` models whether one is registered.
  testthat::local_mocked_bindings(
    is_dev_package = function(name) isTRUE(state$dev_loaded),
    unload = function(package = NULL, quiet = FALSE) {
      state$calls <- c(state$calls, "unload")
      state$unloaded <- package
      invisible(NULL)
    },
    .package = "pkgload",
    .env = parent.frame()
  )
  testthat::local_mocked_bindings(
    miniextendr_autoconf = function(...) invisible(TRUE),
    miniextendr_configure = function(...) invisible(TRUE),
    .package = "minirextendr",
    .env = parent.frame()
  )
  invisible(state)
}

new_state <- function(dev_loaded = TRUE) {
  state <- new.env(parent = emptyenv())
  state$calls <- character()
  state$dev_loaded <- dev_loaded
  state$unloaded <- NULL
  state
}

test_that("miniextendr_build(): compiles + regenerates wrappers, documents, then installs exactly once, in that order", {
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  state <- mock_build_steps(new_state())

  expect_true(miniextendr_build(tmp, install = TRUE))
  expect_equal(state$calls, c("compile_dll", "document", "unload", "install"))
  # The namespace document()'s load_all() registered is unloaded by name.
  expect_equal(state$unloaded, "testpkg")
})

test_that("miniextendr_build(): leaves a namespace alone that pkgload did not register", {
  # library(pkg) loaded earlier from an installed image is not a dev namespace;
  # unloading it over a reinstall is the #1000 hazard, so it is left in place.
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  state <- mock_build_steps(new_state(dev_loaded = FALSE))

  expect_true(miniextendr_build(tmp, install = TRUE))
  expect_equal(state$calls, c("compile_dll", "document", "install"))
  expect_null(state$unloaded)
})

test_that("miniextendr_build(install = FALSE): compiles and documents, installs nothing", {
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  state <- mock_build_steps(new_state())

  expect_true(miniextendr_build(tmp, install = FALSE))
  expect_equal(state$calls, c("compile_dll", "document", "unload"))
})

test_that("miniextendr_build(): a compile failure aborts before document() and the install", {
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  state <- mock_build_steps(new_state(), compile = function() stop("error[E0425]: cannot find value"))

  expect_error(miniextendr_build(tmp, install = TRUE), "wrapper generation failed")
  expect_equal(state$calls, "compile_dll")
})

test_that("miniextendr_build(): a compile that leaves no wrappers file aborts with the reachability hint", {
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root(wrappers = FALSE)
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  state <- mock_build_steps(new_state())

  expect_error(miniextendr_build(tmp, install = TRUE), "wrappers\\.R.*was generated")
  expect_equal(state$calls, "compile_dll")
})

test_that("miniextendr_build(): an install failure errors loudly and is not retried", {
  # There is nothing to retry: NAMESPACE was reconciled before the install,
  # so a failing install is a genuine failure, not the #1288 superset case.
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  state <- mock_build_steps(new_state(), install = function() stop("undefined exports: old_fn"))

  expect_error(miniextendr_build(tmp, install = TRUE), "installation failed")
  expect_equal(state$calls, c("compile_dll", "document", "unload", "install"))
})

# miniextendr_build_tarball(): the build without the install, then the vendor
# step, then R CMD build with the vendor archive in place. `vendor` models
# cargo-revendor's side effects: the archive, a frozen manifest and vendor/.
mock_tarball_steps <- function(state, pkg, env = parent.frame()) {
  manifest <- file.path(pkg, "src", "rust", "Cargo.toml")
  latch <- file.path(pkg, "inst", "vendor.tar.xz")
  testthat::local_mocked_bindings(
    miniextendr_vendor = function(...) {
      state$calls <- c(state$calls, "vendor")
      dir.create(dirname(latch), showWarnings = FALSE)
      writeLines("fake tarball", latch)
      writeLines(c("[package]", 'name = "testpkg"', 'path = "vendor/my-core"'), manifest)
      writeLines("snapshot", file.path(pkg, "src", "rust", ".Cargo.toml.prefreeze"))
      dir.create(file.path(pkg, "vendor", "my-core"), recursive = TRUE)
      invisible(latch)
    },
    .package = "minirextendr",
    .env = env
  )
  testthat::local_mocked_bindings(
    build = function(path, dest_path = NULL, args = NULL, ...) {
      state$calls <- c(state$calls, "build")
      state$latch_at_build <- file.exists(latch)
      state$build_args <- args
      file.path(dest_path, "testpkg_0.1.0.tar.gz")
    },
    .package = "pkgbuild",
    .env = env
  )
  invisible(state)
}

make_tarball_pkg_root <- function() {
  tmp <- make_build_pkg_root()
  dir.create(file.path(tmp, "src", "rust"), recursive = TRUE)
  writeLines(c("[package]", 'name = "testpkg"', 'path = "../../../my-core"'),
             file.path(tmp, "src", "rust", "Cargo.toml"))
  writeLines("# lock", file.path(tmp, "src", "rust", "Cargo.lock"))
  tmp
}

test_that("miniextendr_build_tarball(): documents, vendors, builds, and restores the source tree", {
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_tarball_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  manifest <- file.path(tmp, "src", "rust", "Cargo.toml")
  entry <- readLines(manifest)
  state <- mock_build_steps(new_state())
  mock_tarball_steps(state, tmp)

  tarball <- miniextendr_build_tarball(tmp, dest_path = tmp, args = "--no-build-vignettes")
  expect_equal(tarball, file.path(tmp, "testpkg_0.1.0.tar.gz"))
  # No install: the tarball is the artifact.
  expect_equal(state$calls, c("compile_dll", "document", "unload", "vendor", "build"))
  expect_true(state$latch_at_build)
  expect_equal(state$build_args, "--no-build-vignettes")
  expect_false(file.exists(file.path(tmp, "inst", "vendor.tar.xz")))
  expect_false(file.exists(file.path(tmp, "src", "rust", ".Cargo.toml.prefreeze")))
  expect_false(dir.exists(file.path(tmp, "vendor")))
  expect_equal(readLines(manifest), entry)
})

test_that("miniextendr_build_tarball(): the source tree is restored when the build fails", {
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_tarball_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  manifest <- file.path(tmp, "src", "rust", "Cargo.toml")
  entry <- readLines(manifest)
  dir.create(file.path(tmp, "vendor", "offline-crate"), recursive = TRUE)
  state <- mock_build_steps(new_state())
  mock_tarball_steps(state, tmp)
  testthat::local_mocked_bindings(build = function(...) stop("R CMD build failed"), .package = "pkgbuild")

  expect_error(miniextendr_build_tarball(tmp), "R CMD build failed")
  expect_false(file.exists(file.path(tmp, "inst", "vendor.tar.xz")))
  expect_equal(readLines(manifest), entry)
  # A vendor/ that existed before the build is the author's, not ours.
  expect_true(dir.exists(file.path(tmp, "vendor", "offline-crate")))
})

test_that("miniextendr_build_tarball(): refuses a tree that still carries release vendoring", {
  tmp <- make_tarball_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  latch <- file.path(tmp, "inst", "vendor.tar.xz")
  dir.create(dirname(latch))
  writeLines("stale", latch)

  expect_error(miniextendr_build_tarball(tmp), "earlier release build")
  expect_true(file.exists(latch))
})

test_that("miniextendr_build(): a pre-existing latch is warned about and never deleted (#1294)", {
  # A latch that existed BEFORE the build may be a deliberate release-prep
  # artifact: it must survive, and the up-front warning must fire (the tree
  # builds in offline tarball mode throughout).
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  latch_path <- file.path(tmp, "inst", "vendor.tar.xz")
  dir.create(dirname(latch_path), showWarnings = FALSE)
  writeLines("pre-existing tarball", latch_path)
  state <- mock_build_steps(new_state())

  expect_warning(
    miniextendr_build(tmp, install = TRUE),
    "Pre-existing .*vendor\\.tar\\.xz.* latch"
  )
  expect_true(file.exists(latch_path))
  expect_equal(state$calls, c("compile_dll", "document", "unload", "install"))
})

test_that("wrappers_file_exists detects a generated *-wrappers.R", {
  tmp <- make_build_pkg_root(wrappers = FALSE)
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  # Fresh package: no wrappers file yet.
  expect_false(minirextendr:::wrappers_file_exists(tmp))

  # Once a *-wrappers.R lands, it is detected regardless of the package stem.
  writeLines("# generated", file.path(tmp, "R", "testpkg-wrappers.R"))
  expect_true(minirextendr:::wrappers_file_exists(tmp))
})

test_that("wrappers_file_exists is FALSE when the R/ directory is missing", {
  tmp <- tempfile("workflow-build-nodir-")
  dir.create(tmp)
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  expect_false(minirextendr:::wrappers_file_exists(tmp))
})
