# Tests for miniextendr_check_static()

# Creates a minimal valid R package in a temp dir (no Rust scaffolding needed —
# --install=fake skips configure entirely).
make_minimal_pkg <- function(tmp, pkg_name = "teststaticpkg") {
  pkg_path <- file.path(tmp, pkg_name)
  dir.create(pkg_path, recursive = TRUE)
  writeLines(
    c(
      paste0("Package: ", pkg_name),
      "Version: 0.1.0",
      "Title: Test Static Pkg",
      "Description: Minimal package for static check tests.",
      "Authors@R: person('Test', 'User', email = 'test@example.com', role = c('aut', 'cre'))",
      "License: MIT + file LICENSE",
      "Encoding: UTF-8"
    ),
    file.path(pkg_path, "DESCRIPTION")
  )
  writeLines("# Generated by roxygen2: do not edit by hand", file.path(pkg_path, "NAMESPACE"))
  writeLines(
    c("MIT License", "", "Copyright (c) 2024 Test User"),
    file.path(pkg_path, "LICENSE")
  )
  dir.create(file.path(pkg_path, "R"), showWarnings = FALSE)
  writeLines(
    c("#' A placeholder function", "#' @export", "placeholder <- function() invisible(NULL)"),
    file.path(pkg_path, "R", "placeholder.R")
  )
  pkg_path
}

test_that("miniextendr_check_static passes on a valid minimal package", {
  skip_on_cran()
  skip_if_not_installed("rcmdcheck")

  tmp <- tempfile("static-check-happy-")
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  dir.create(tmp)

  pkg_path <- make_minimal_pkg(tmp)

  result <- suppressMessages(
    miniextendr_check_static(pkg_path, error_on = "error")
  )

  expect_s3_class(result, "rcmdcheck")
  expect_equal(length(result$errors), 0L)
  # Confirm no Rust target dir was created — cargo was never invoked.
  expect_false(dir.exists(file.path(pkg_path, "src", "rust", "target")))
})

test_that("miniextendr_check_static surfaces a broken DESCRIPTION", {
  skip_on_cran()
  skip_if_not_installed("rcmdcheck")

  tmp <- tempfile("static-check-broken-")
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  dir.create(tmp)

  pkg_path <- make_minimal_pkg(tmp, pkg_name = "testbrokenpkg")

  # Drop the Version field — R CMD check reports this as an error.
  desc_lines <- readLines(file.path(pkg_path, "DESCRIPTION"))
  desc_lines <- desc_lines[!grepl("^Version:", desc_lines)]
  writeLines(desc_lines, file.path(pkg_path, "DESCRIPTION"))

  result <- suppressMessages(
    tryCatch(
      miniextendr_check_static(pkg_path, error_on = "note"),
      error = function(e) e
    )
  )

  # Either rcmdcheck threw (error_on triggered) or the result has errors/warnings.
  has_issues <- inherits(result, "error") ||
    (inherits(result, "rcmdcheck") &&
       (length(result$errors) > 0 || length(result$warnings) > 0))
  expect_true(has_issues, info = "Expected check to flag missing Version field")
})
