# Tests for miniextendr_build()'s removal/rename self-heal (#1288).
#
# The additive case (#860/#899, exercised in test-workflow-bootstrap.R and the
# e2e test in test-templates.R) self-heals via the existing Step-3 install ->
# Step-4 document() -> Step-5 conditional-reinstall dance. The removal/rename
# case instead dies at Step 3: the on-disk NAMESPACE is a superset of the
# freshly regenerated wrappers, and R CMD INSTALL's test-load aborts with
# "undefined exports: <old_name>" before document() can drop the stale entry.
#
# These tests are behavioural-through-mocks (devtools::install/document +
# the internal autoconf/configure/wrappers-gate helpers), NOT deparse(body)
# greps -- see minirextendr/CLAUDE.md's brittle-test gotcha.

make_selfheal_pkg_root <- function() {
  tmp <- tempfile("workflow-selfheal-")
  dir.create(tmp)
  writeLines(
    "Package: testpkg\nTitle: Test\nVersion: 0.1.0\n",
    file.path(tmp, "DESCRIPTION")
  )
  writeLines(
    "# Generated by roxygen2: do not edit by hand\n",
    file.path(tmp, "NAMESPACE")
  )
  dir.create(file.path(tmp, "R"))
  # Pre-seed a wrappers file so miniextendr_build()'s Step 3a bootstrap branch
  # is skipped -- these tests target the mature-package Step 3/5 path, not
  # the fresh-package bootstrap (covered separately below / in
  # test-workflow-bootstrap.R).
  writeLines("# generated", file.path(tmp, "R", "testpkg-wrappers.R"))
  tmp
}

test_that("miniextendr_build(): a deferred Step-3 failure forces the Step-5 retry even when document() leaves NAMESPACE unchanged", {
  # Pins the forced-retry rule (#1288): a digest-only Step-5 condition would
  # skip the reinstall here because document() doesn't touch NAMESPACE in
  # this mock (it's a no-op), but the installed image is still the broken one
  # from Step 3's failure. install must be retried regardless.
  tmp <- make_selfheal_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  install_call_count <- 0L

  testthat::local_mocked_bindings(
    install = function(...) {
      install_call_count <<- install_call_count + 1L
      if (install_call_count == 1L) {
        stop("undefined exports: old_fn")
      }
      invisible(NULL)
    },
    document = function(...) invisible(NULL),
    .package = "devtools"
  )

  testthat::local_mocked_bindings(
    miniextendr_autoconf = function(...) invisible(TRUE),
    miniextendr_configure = function(...) invisible(TRUE),
    wrappers_file_exists = function(...) TRUE,
    .package = "minirextendr"
  )

  expect_warning(
    result <- miniextendr_build(tmp, install = TRUE),
    "Install failed before NAMESPACE reconciliation"
  )

  expect_true(result)
  expect_equal(install_call_count, 2L)
})

test_that("miniextendr_build(): an install that always fails errors loudly after exactly one bounded retry", {
  # A genuinely broken build must still fail the overall build -- the defer
  # is not a silent swallow, and the retry is bounded to one pass (no loop).
  tmp <- make_selfheal_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  install_call_count <- 0L

  testthat::local_mocked_bindings(
    install = function(...) {
      install_call_count <<- install_call_count + 1L
      stop("undefined exports: old_fn")
    },
    document = function(...) invisible(NULL),
    .package = "devtools"
  )

  testthat::local_mocked_bindings(
    miniextendr_autoconf = function(...) invisible(TRUE),
    miniextendr_configure = function(...) invisible(TRUE),
    wrappers_file_exists = function(...) TRUE,
    .package = "minirextendr"
  )

  expect_warning(
    expect_error(
      miniextendr_build(tmp, install = TRUE),
      "installation failed"
    ),
    "Install failed before NAMESPACE reconciliation"
  )

  expect_equal(install_call_count, 2L)
})

test_that("miniextendr_build(): the source tree is restored BEFORE document(), not only on exit (#1294)", {
  # Step 3's build = TRUE install runs bootstrap.R in the source tree, which
  # seals inst/vendor.tar.xz and freezes src/rust/Cargo.toml by design. If
  # the restore only ran at on.exit, Step 4's document() would execute in a
  # latched (tarball-mode) tree and wrapper regeneration would be skipped
  # (#1022 guard) -- breaking both self-heal paths (#860 additive, #1288
  # removal/rename) for post-first-build export changes. This test mocks
  # devtools::install to SIMULATE bootstrap.R's side effect and asserts, at
  # document-time, that the latch is already gone and the manifest matches
  # the entry snapshot.
  tmp <- make_selfheal_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  manifest_path <- file.path(tmp, "src", "rust", "Cargo.toml")
  dir.create(dirname(manifest_path), recursive = TRUE)
  manifest_entry <- c("[package]", 'name = "testpkg"', 'path = "../../../my-core"')
  writeLines(manifest_entry, manifest_path)

  latch_path <- file.path(tmp, "inst", "vendor.tar.xz")

  document_time_latch_present <- NA
  document_time_manifest <- NULL

  testthat::local_mocked_bindings(
    install = function(...) {
      # Simulate bootstrap.R's documented side effect: seal the latch into
      # the source tree and freeze the manifest.
      dir.create(dirname(latch_path), showWarnings = FALSE)
      writeLines("fake tarball", latch_path)
      writeLines(c("[package]", 'name = "testpkg"', 'path = "vendor/my-core"'),
                 manifest_path)
      invisible(NULL)
    },
    document = function(...) {
      document_time_latch_present <<- file.exists(latch_path)
      document_time_manifest <<- readLines(manifest_path, warn = FALSE)
      invisible(NULL)
    },
    .package = "devtools"
  )

  testthat::local_mocked_bindings(
    miniextendr_autoconf = function(...) invisible(TRUE),
    miniextendr_configure = function(...) invisible(TRUE),
    wrappers_file_exists = function(...) TRUE,
    .package = "minirextendr"
  )

  expect_true(miniextendr_build(tmp, install = TRUE))

  # The mid-build restore must have run before document(): latch deleted,
  # manifest back to its entry snapshot.
  expect_false(document_time_latch_present)
  expect_equal(document_time_manifest, manifest_entry)

  # And the on.exit backstop leaves the tree clean after return too.
  expect_false(file.exists(latch_path))
  expect_equal(readLines(manifest_path, warn = FALSE), manifest_entry)
})

test_that("miniextendr_build(): a pre-existing latch is warned about and never deleted mid-build (#1294)", {
  # A latch that existed BEFORE the build may be a deliberate release-prep
  # artifact -- it must survive both the mid-build restore and the on.exit
  # backstop, and the new up-front warning must fire (dev-loop self-heal is
  # structurally disabled in a latched tree).
  tmp <- make_selfheal_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  latch_path <- file.path(tmp, "inst", "vendor.tar.xz")
  dir.create(dirname(latch_path), showWarnings = FALSE)
  writeLines("pre-existing tarball", latch_path)

  document_time_latch_present <- NA

  testthat::local_mocked_bindings(
    install = function(...) invisible(NULL),
    document = function(...) {
      document_time_latch_present <<- file.exists(latch_path)
      invisible(NULL)
    },
    .package = "devtools"
  )

  testthat::local_mocked_bindings(
    miniextendr_autoconf = function(...) invisible(TRUE),
    miniextendr_configure = function(...) invisible(TRUE),
    wrappers_file_exists = function(...) TRUE,
    .package = "minirextendr"
  )

  expect_warning(
    miniextendr_build(tmp, install = TRUE),
    "Pre-existing .*vendor\\.tar\\.xz.* latch"
  )

  # Not deleted mid-build (still present at document-time) nor on exit.
  expect_true(document_time_latch_present)
  expect_true(file.exists(latch_path))
})

test_that("bootstrap_fresh_wrappers(): a deferred first-install failure heals when wrappers exist", {
  # Mature-package flavour of the same bug (#1288): reachable when a fresh
  # scaffold's wrappers.R is absent (triggering the Step 3a bootstrap path)
  # AND the pre-existing NAMESPACE lists a since-removed/renamed export. The
  # Makevars `** libs` target writes wrappers in-place before test-load runs,
  # so a test-load-only failure still leaves wrappers on disk -- the
  # discriminator that lets bootstrap_fresh_wrappers() defer and heal instead
  # of aborting.
  tmp <- tempfile("workflow-selfheal-bootstrap-")
  dir.create(tmp)
  writeLines(
    "Package: testpkg\nTitle: Test\nVersion: 0.1.0\n",
    file.path(tmp, "DESCRIPTION")
  )
  writeLines("", file.path(tmp, "NAMESPACE"))
  dir.create(file.path(tmp, "R"))
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  install_call_count <- 0L

  testthat::local_mocked_bindings(
    install = function(...) {
      install_call_count <<- install_call_count + 1L
      if (install_call_count == 1L) {
        stop("undefined exports: old_fn")
      }
      invisible(NULL)
    },
    document = function(...) invisible(NULL),
    .package = "devtools"
  )

  testthat::local_mocked_bindings(
    miniextendr_configure = function(...) invisible(TRUE),
    clear_install_mode_latch = function(...) invisible(TRUE),
    wrappers_file_exists = function(...) TRUE,
    .package = "minirextendr"
  )

  expect_warning(
    minirextendr:::bootstrap_fresh_wrappers(tmp),
    "Bootstrap install failed before NAMESPACE reconciliation"
  )

  expect_equal(install_call_count, 2L)
})

test_that("bootstrap_fresh_wrappers(): a first-install failure with no wrappers on disk re-raises as a real failure", {
  # If wrappers are still absent after the failed install, the failure was
  # real (e.g. a genuine compile error) -- re-raise with the existing wording
  # rather than deferring indefinitely.
  tmp <- tempfile("workflow-selfheal-bootstrap-real-")
  dir.create(tmp)
  writeLines(
    "Package: testpkg\nTitle: Test\nVersion: 0.1.0\n",
    file.path(tmp, "DESCRIPTION")
  )
  writeLines("", file.path(tmp, "NAMESPACE"))
  dir.create(file.path(tmp, "R"))
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  install_call_count <- 0L

  testthat::local_mocked_bindings(
    install = function(...) {
      install_call_count <<- install_call_count + 1L
      stop("some real compile error")
    },
    .package = "devtools"
  )

  testthat::local_mocked_bindings(
    miniextendr_configure = function(...) invisible(TRUE),
    clear_install_mode_latch = function(...) invisible(TRUE),
    wrappers_file_exists = function(...) FALSE,
    .package = "minirextendr"
  )

  expect_error(
    minirextendr:::bootstrap_fresh_wrappers(tmp),
    "Bootstrap install failed"
  )

  expect_equal(install_call_count, 1L)
})
