# Tests for miniextendr_check_static()

# Creates a minimal valid R package in a temp dir (no Rust scaffolding needed --
# --install=fake skips configure entirely).
make_minimal_pkg <- function(tmp, pkg_name = "teststaticpkg") {
  pkg_path <- file.path(tmp, pkg_name)
  dir.create(pkg_path, recursive = TRUE)
  writeLines(
    c(
      paste0("Package: ", pkg_name),
      "Version: 0.1.0",
      "Title: Test Static Pkg",
      "Description: Minimal package for static check tests.",
      "Authors@R: person('Test', 'User', email = 'test@example.com', role = c('aut', 'cre'))",
      "License: MIT + file LICENSE",
      "Encoding: UTF-8"
    ),
    file.path(pkg_path, "DESCRIPTION")
  )
  writeLines("# Generated by roxygen2: do not edit by hand", file.path(pkg_path, "NAMESPACE"))
  writeLines(
    c("MIT License", "", "Copyright (c) 2024 Test User"),
    file.path(pkg_path, "LICENSE")
  )
  dir.create(file.path(pkg_path, "R"), showWarnings = FALSE)
  writeLines(
    c("#' A placeholder function", "#' @export", "placeholder <- function() invisible(NULL)"),
    file.path(pkg_path, "R", "placeholder.R")
  )
  pkg_path
}

# Test 1: happy path on a minimal package (no Rust scaffolding).
# roxygenize = FALSE so this test does not depend on roxygen2 being installed.
test_that("miniextendr_check_static passes on a valid minimal package", {
  skip_on_cran()
  skip_if_not_installed("rcmdcheck")

  tmp <- tempfile("static-check-happy-")
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  dir.create(tmp)

  pkg_path <- make_minimal_pkg(tmp)

  result <- suppressMessages(
    miniextendr_check_static(pkg_path, error_on = "error", roxygenize = FALSE)
  )

  expect_s3_class(result, "rcmdcheck")
  expect_equal(length(result$errors), 0L)
  # Confirm no Rust target dir was created -- cargo was never invoked.
  expect_false(dir.exists(file.path(pkg_path, "src", "rust", "target")))
})

# Test 2: broken DESCRIPTION surfaces in the check result.
# roxygenize = FALSE so the test exercises pure R CMD check error reporting.
test_that("miniextendr_check_static surfaces a broken DESCRIPTION", {
  skip_on_cran()
  skip_if_not_installed("rcmdcheck")

  tmp <- tempfile("static-check-broken-")
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  dir.create(tmp)

  pkg_path <- make_minimal_pkg(tmp, pkg_name = "testbrokenpkg")

  # Drop the Version field -- R CMD check reports this as an error.
  desc_lines <- readLines(file.path(pkg_path, "DESCRIPTION"))
  desc_lines <- desc_lines[!grepl("^Version:", desc_lines)]
  writeLines(desc_lines, file.path(pkg_path, "DESCRIPTION"))

  result <- suppressMessages(suppressWarnings(
    tryCatch(
      miniextendr_check_static(pkg_path, error_on = "note", roxygenize = FALSE),
      error = function(e) e
    )
  ))

  # Either rcmdcheck threw (error_on triggered) or the result has errors/warnings.
  has_issues <- inherits(result, "error") ||
    (inherits(result, "rcmdcheck") &&
       (length(result$errors) > 0 || length(result$warnings) > 0))
  expect_true(has_issues, info = "Expected check to flag missing Version field")
})

# Test 3: real miniextendr-shaped package fixture.
#
# Uses a manually-crafted fixture directory under
# tests/testthat/_fixtures/static-check-rustpkg/ rather than
# create_miniextendr_package() because:
#   - create_miniextendr_package() requires autoconf, cargo, and network to
#     run use_miniextendr() (it writes configure.ac, runs autoconf, etc.).
#   - The fixture approach is deterministic, offline, and instant.
#   - The fixture has src/rust/Cargo.toml + a stub configure to look like a
#     real miniextendr package; the test verifies --install=fake skips configure
#     even when those files are present.
#
# roxygenize = FALSE: the fixture's NAMESPACE is hand-written and not connected
# to its R sources; roxygenize would overwrite it and produce a fresh file from
# the placeholder.R export, which is fine but adds a roxygen2 dependency to the
# test. Keeping it FALSE keeps this test self-contained.
test_that("miniextendr_check_static does not invoke cargo on a Rust-scaffolded package", {
  skip_on_cran()
  skip_if_not_installed("rcmdcheck")

  fixture_src <- testthat::test_path("_fixtures", "static-check-rustpkg")
  skip_if(!dir.exists(fixture_src), "Rust-pkg fixture not found")

  # Copy fixture to a temp dir so the check does not modify the repo.
  tmp <- tempfile("static-check-rustpkg-")
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  dir.create(tmp)
  pkg_path <- file.path(tmp, "staticcheckrustpkg")
  fs::dir_copy(fixture_src, pkg_path)

  result <- suppressMessages(
    tryCatch(
      # error_on = "note" would fail on real CRAN warnings, use "error" to
      # only catch hard failures and verify the static phases ran cleanly.
      miniextendr_check_static(pkg_path, error_on = "error", roxygenize = FALSE),
      error = function(e) e
    )
  )

  # The check must have returned an rcmdcheck object (not thrown unexpectedly).
  # If it threw, surface the message for diagnosis.
  if (inherits(result, "error")) {
    fail(paste("miniextendr_check_static() threw unexpectedly:", conditionMessage(result)))
  }

  expect_s3_class(result, "rcmdcheck")
  expect_equal(length(result$errors), 0L,
               label = "No hard errors from static check on Rust-scaffolded fixture")

  # Verify cargo was never invoked:
  # (a) No target/ directory was created inside src/rust/.
  expect_false(
    dir.exists(file.path(pkg_path, "src", "rust", "target")),
    label = "src/rust/target/ must not exist (cargo was never run)"
  )
  # (b) No vendor tarball was produced.
  expect_false(
    file.exists(file.path(pkg_path, "inst", "vendor.tar.xz")),
    label = "inst/vendor.tar.xz must not exist (vendoring was never triggered)"
  )
})
