# Tests for miniextendr_build()'s step order and guards (#860, #1288, #1294,
# #1549).
#
# The wrappers file is written by the Makevars wrapper-gen rule, roxygen2
# reads it to write NAMESPACE and man/, and the install ships all three. So
# the steps run in dependency order: compile + regenerate wrappers in the
# source tree (pkgbuild::compile_dll, which never loads the namespace) ->
# devtools::document() -> one devtools::install(). Earlier versions installed
# first and papered over the resulting one-build lag with a conditional
# reinstall (#860) and a deferred install failure (#1288); an edited doc
# comment still never reached the installed help (#1549).
#
# These tests are behavioural-through-mocks (pkgbuild::compile_dll,
# devtools::install/document + the internal autoconf/configure helpers), NOT
# deparse(body) greps -- see minirextendr/CLAUDE.md's brittle-test gotcha.
# The real compile/roxygen/install round-trip is covered by the gated e2e
# tests in test-templates.R.

make_build_pkg_root <- function(wrappers = TRUE) {
  tmp <- tempfile("workflow-build-")
  dir.create(tmp)
  writeLines(
    "Package: testpkg\nTitle: Test\nVersion: 0.1.0\n",
    file.path(tmp, "DESCRIPTION")
  )
  writeLines(
    "# Generated by roxygen2: do not edit by hand\n",
    file.path(tmp, "NAMESPACE")
  )
  dir.create(file.path(tmp, "R"))
  # The mocked compile_dll writes nothing, so pre-seed the wrappers file the
  # real Makevars rule would have produced; `wrappers = FALSE` models a compile
  # that produced none.
  if (wrappers) writeLines("# generated", file.path(tmp, "R", "testpkg-wrappers.R"))
  tmp
}

# Mock the three external steps, recording the order they run in and the
# MINIEXTENDR_FORCE_WRAPPER_GEN value each one sees. `calls` and `force_seen`
# are environments so the mocks can append from inside testthat's binding.
mock_build_steps <- function(state,
                             compile = function() invisible(NULL),
                             document = function() invisible(NULL),
                             install = function() invisible(NULL)) {
  record <- function(step, body) {
    force(step)
    force(body)
    function(...) {
      state$calls <- c(state$calls, step)
      state$force_seen[[step]] <- Sys.getenv("MINIEXTENDR_FORCE_WRAPPER_GEN", unset = "")
      body()
    }
  }
  testthat::local_mocked_bindings(
    compile_dll = record("compile_dll", compile),
    .package = "pkgbuild",
    .env = parent.frame()
  )
  testthat::local_mocked_bindings(
    document = record("document", document),
    install = record("install", install),
    .package = "devtools",
    .env = parent.frame()
  )
  # document() leaves the package's development namespace loaded; the
  # workflow unloads it. `state$dev_loaded` models whether one is registered.
  testthat::local_mocked_bindings(
    is_dev_package = function(name) isTRUE(state$dev_loaded),
    unload = function(package = NULL, quiet = FALSE) {
      state$calls <- c(state$calls, "unload")
      state$unloaded <- package
      invisible(NULL)
    },
    .package = "pkgload",
    .env = parent.frame()
  )
  testthat::local_mocked_bindings(
    miniextendr_autoconf = function(...) invisible(TRUE),
    miniextendr_configure = function(...) invisible(TRUE),
    .package = "minirextendr",
    .env = parent.frame()
  )
  invisible(state)
}

new_state <- function(dev_loaded = TRUE) {
  state <- new.env(parent = emptyenv())
  state$calls <- character()
  state$force_seen <- list()
  state$dev_loaded <- dev_loaded
  state$unloaded <- NULL
  state
}

test_that("miniextendr_build(): compiles + regenerates wrappers, documents, then installs exactly once, in that order", {
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  state <- mock_build_steps(new_state())

  expect_true(miniextendr_build(tmp, install = TRUE))
  expect_equal(state$calls, c("compile_dll", "document", "unload", "install"))
  # The namespace document()'s load_all() registered is unloaded by name.
  expect_equal(state$unloaded, "testpkg")
})

test_that("miniextendr_build(): leaves a namespace alone that pkgload did not register", {
  # library(pkg) loaded earlier from an installed image is not a dev namespace;
  # unloading it over a reinstall is the #1000 hazard, so it is left in place.
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  state <- mock_build_steps(new_state(dev_loaded = FALSE))

  expect_true(miniextendr_build(tmp, install = TRUE))
  expect_equal(state$calls, c("compile_dll", "document", "install"))
  expect_null(state$unloaded)
})

test_that("miniextendr_build(install = FALSE): compiles and documents, installs nothing", {
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  state <- mock_build_steps(new_state())

  expect_true(miniextendr_build(tmp, install = FALSE))
  expect_equal(state$calls, c("compile_dll", "document", "unload"))
})

test_that("miniextendr_build(): MINIEXTENDR_FORCE_WRAPPER_GEN=1 covers the compile and the install, not document(), and is restored afterwards", {
  # The Makevars wrapper-gen rule regenerates unconditionally under the
  # override (#757 / #911). document()'s own roxygenise compile must run
  # WITHOUT it so the rule reuses the wrappers Step 3 just wrote instead of
  # loading the shared object a second time.
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  withr::local_envvar(c(MINIEXTENDR_FORCE_WRAPPER_GEN = NA))
  state <- mock_build_steps(new_state())

  miniextendr_build(tmp, install = TRUE)

  expect_equal(state$force_seen$compile_dll, "1")
  expect_equal(state$force_seen$document, "")
  expect_equal(state$force_seen$install, "1")
  expect_equal(Sys.getenv("MINIEXTENDR_FORCE_WRAPPER_GEN", unset = ""), "")
})

test_that("miniextendr_build(): a compile failure aborts before document() and the install", {
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  state <- mock_build_steps(new_state(), compile = function() stop("error[E0425]: cannot find value"))

  expect_error(miniextendr_build(tmp, install = TRUE), "wrapper generation failed")
  expect_equal(state$calls, "compile_dll")
})

test_that("miniextendr_build(): a compile that leaves no wrappers file aborts with the reachability hint", {
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root(wrappers = FALSE)
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  state <- mock_build_steps(new_state())

  expect_error(miniextendr_build(tmp, install = TRUE), "wrappers\\.R.*was generated")
  expect_equal(state$calls, "compile_dll")
})

test_that("miniextendr_build(): an install failure errors loudly and is not retried", {
  # There is nothing to retry: NAMESPACE was reconciled before the install,
  # so a failing install is a genuine failure, not the #1288 superset case.
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  state <- mock_build_steps(new_state(), install = function() stop("undefined exports: old_fn"))

  expect_error(miniextendr_build(tmp, install = TRUE), "installation failed")
  expect_equal(state$calls, c("compile_dll", "document", "unload", "install"))
})

test_that("miniextendr_build(): the source tree is restored on exit (#1294)", {
  # The install's `R CMD build` runs bootstrap.R in the source tree, which
  # seals inst/vendor.tar.xz and freezes src/rust/Cargo.toml by design. The
  # install is the last step, so an on.exit restore is enough: the latch the
  # build created is deleted and the manifest is back to its entry snapshot.
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  manifest_path <- file.path(tmp, "src", "rust", "Cargo.toml")
  dir.create(dirname(manifest_path), recursive = TRUE)
  manifest_entry <- c("[package]", 'name = "testpkg"', 'path = "../../../my-core"')
  writeLines(manifest_entry, manifest_path)
  latch_path <- file.path(tmp, "inst", "vendor.tar.xz")

  state <- mock_build_steps(new_state(), install = function() {
    # Simulate bootstrap.R's documented side effect.
    dir.create(dirname(latch_path), showWarnings = FALSE)
    writeLines("fake tarball", latch_path)
    writeLines(c("[package]", 'name = "testpkg"', 'path = "vendor/my-core"'), manifest_path)
    invisible(NULL)
  })

  expect_true(miniextendr_build(tmp, install = TRUE))
  expect_equal(state$calls, c("compile_dll", "document", "unload", "install"))
  expect_false(file.exists(latch_path))
  expect_equal(readLines(manifest_path, warn = FALSE), manifest_entry)
})

test_that("miniextendr_build(): a pre-existing latch is warned about and never deleted (#1294)", {
  # A latch that existed BEFORE the build may be a deliberate release-prep
  # artifact: it must survive the on.exit restore, and the up-front warning
  # must fire (the tree builds in offline tarball mode throughout).
  skip_if_not_installed("pkgbuild")
  skip_if_not_installed("devtools")
  tmp <- make_build_pkg_root()
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  latch_path <- file.path(tmp, "inst", "vendor.tar.xz")
  dir.create(dirname(latch_path), showWarnings = FALSE)
  writeLines("pre-existing tarball", latch_path)
  state <- mock_build_steps(new_state())

  expect_warning(
    miniextendr_build(tmp, install = TRUE),
    "Pre-existing .*vendor\\.tar\\.xz.* latch"
  )
  expect_true(file.exists(latch_path))
  expect_equal(state$calls, c("compile_dll", "document", "unload", "install"))
})

test_that("wrappers_file_exists detects a generated *-wrappers.R", {
  tmp <- make_build_pkg_root(wrappers = FALSE)
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  # Fresh package: no wrappers file yet.
  expect_false(minirextendr:::wrappers_file_exists(tmp))

  # Once a *-wrappers.R lands, it is detected regardless of the package stem.
  writeLines("# generated", file.path(tmp, "R", "testpkg-wrappers.R"))
  expect_true(minirextendr:::wrappers_file_exists(tmp))
})

test_that("wrappers_file_exists is FALSE when the R/ directory is missing", {
  tmp <- tempfile("workflow-build-nodir-")
  dir.create(tmp)
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  expect_false(minirextendr:::wrappers_file_exists(tmp))
})
