# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: run `devtools::document()` or rebuild the package.
# nolint start
# nocov start



# Generated from Rust impl `World` (lib.rs:70:6)
#' @title World  Class
#' @name World
#' @rdname World
#' @source Generated by miniextendr from Rust type `World`
#' @export
World <- new.env(parent = emptyenv())

#' @title Create a new simulation world with the given parameters
#' @return A new `World` object (opaque pointer).
#'
#' \describe{
#'   \item{\code{n_initial}}{Number of pigs to create at time zero.}
#'   \item{\code{food_per_tick}}{Energy gained by each pig per simulation tick.}
#'   \item{\code{move_cost}}{Energy spent by each pig per tick for movement.}
#'   \item{\code{reproduction_threshold}}{Energy level above which a pig reproduces.}
#'   \item{\code{max_age}}{Maximum age in ticks before a pig dies of old age.}
#'   \item{\code{interaction_radius}}{Euclidean distance within which pigs compete.}
#'   \item{\code{seed}}{Integer seed for the random number generator (for reproducibility).}
#' }
#' @name World$new
#' @rdname World
#' @source Generated by miniextendr from `World::new`
World$new <- function(n_initial, food_per_tick, move_cost, reproduction_threshold, max_age, interaction_radius, seed) {
  self <- .Call(C_World__new, .call = match.call(), n_initial, food_per_tick, move_cost, reproduction_threshold, max_age, interaction_radius, seed)
  class(self) <- "World"
  self
}

#' @title Advance the simulation by one tick
#' @return The `World` object (invisibly, for method chaining).
#' @name World$step
#' @rdname World
#' @source Generated by miniextendr from `World::step`
World$step <- function() {
  .Call(C_World__step, .call = match.call(), self)
  self
}

#' @title Run the simulation for multiple ticks
#' @return The `World` object (invisibly, for method chaining).
#'
#' \describe{
#'   \item{\code{steps}}{Number of ticks to advance.}
#' }
#' @name World$run
#' @rdname World
#' @source Generated by miniextendr from `World::run`
World$run <- function(steps) {
  .Call(C_World__run, .call = match.call(), self, steps)
  self
}

#' @title Get the current simulation tick
#' @return Integer tick count (starts at 0, incremented by each `step()`).
#' @name World$get_tick
#' @rdname World
#' @source Generated by miniextendr from `World::get_tick`
World$get_tick <- function() {
  .Call(C_World__get_tick, .call = match.call(), self)
}

#' @title Get the number of living pigs
#' @return Integer count of pigs currently alive.
#' @name World$population
#' @rdname World
#' @source Generated by miniextendr from `World::population`
World$population <- function() {
  .Call(C_World__population, .call = match.call(), self)
}

#' @title Get all x-coordinates of living pigs
#' @return Numeric vector of x positions (one per pig).
#' @name World$x_positions
#' @rdname World
#' @source Generated by miniextendr from `World::x_positions`
World$x_positions <- function() {
  .Call(C_World__x_positions, .call = match.call(), self)
}

#' @title Get all y-coordinates of living pigs
#' @return Numeric vector of y positions (one per pig).
#' @name World$y_positions
#' @rdname World
#' @source Generated by miniextendr from `World::y_positions`
World$y_positions <- function() {
  .Call(C_World__y_positions, .call = match.call(), self)
}

#' @title Get the energy levels of all living pigs
#' @return Numeric vector of energy values (one per pig).
#' @name World$energies
#' @rdname World
#' @source Generated by miniextendr from `World::energies`
World$energies <- function() {
  .Call(C_World__energies, .call = match.call(), self)
}

#' @title Get the ages (in ticks) of all living pigs
#' @return Integer vector of ages (one per pig).
#' @name World$ages
#' @rdname World
#' @source Generated by miniextendr from `World::ages`
World$ages <- function() {
  .Call(C_World__ages, .call = match.call(), self)
}

#' @title Compute the age distribution as a histogram
#' @return Integer vector where element `i` is the number of pigs in
#' age bucket `[10*i, 10*i+9]`. Empty vector if no pigs are alive.
#' @name World$age_histogram
#' @rdname World
#' @source Generated by miniextendr from `World::age_histogram`
World$age_histogram <- function() {
  .Call(C_World__age_histogram, .call = match.call(), self)
}

#' @title Get a human-readable summary of the current simulation state
#' @return Character string of the form `"Tick N: M pigs, avg energy X.X"`.
#' @name World$summary
#' @rdname World
#' @source Generated by miniextendr from `World::summary`
World$summary <- function() {
  .Call(C_World__summary, .call = match.call(), self)
}

#' @rdname World
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.World` <- function(self, name) {
  obj <- World[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level — search trait namespace environments
    for (ns_name in names(World)) {
      ns <- World[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method — bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @rdname World
#' @export
`[[.World` <- `$.World`

# nocov end
# nolint end
