#!/bin/sh
# Variables that are present from R build process
# Sys.setenv(R_PACKAGE_NAME = pkgname)
# Sys.setenv(R_PACKAGE_DIR = pkgdir)
# Sys.setenv(R_LIBRARY_DIR = dirname(pkgdir))

# Only clean when on CRAN or during R CMD check
if [ "${NOT_CRAN:-false}" = "false" ]; then
  rm -rf ../.cargo
  rm -rf .cargo
  rm -rf src/.cargo
  rm -rf src/vendor
  rm -f  src/Makevars
  rm -rf src/rust/target
  # rm -rf src/rust/ra_target
  rm -rf src/rust/.cargo
  rm -f  src/rust/Cargo.toml
  rm -f  src/rust/document.rs
  rm -f  src/entrypoint.c
  rm -f  src/miniextendr_wrappers.R
fi
