fn main() {
    miniextendr_lint::build_script();

    // Only the wasm32 build reads wasm_registry.rs. The host install rewrites it
    // after linking whenever the wrappers change, so watching it on a native
    // build would recompile the crate on the next install.
    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    if target_arch != "wasm32" {
        return;
    }
    println!("cargo:rerun-if-changed=wasm_registry.rs");

    let path = std::path::Path::new("wasm_registry.rs");
    let content = std::fs::read_to_string(path).unwrap_or_else(|_| {
        panic!(
            "wasm32 build requires src/rust/wasm_registry.rs, which is absent.\n\
             \n\
             This crate is NOT directly installable on wasm32. wasm_registry.rs\n\
             (and R/<pkg>-wrappers.R) are generated by a host install and are\n\
             NOT tracked in git. The wasm32 build is a TWO-STEP process:\n\
             \n\
               1. Host build:  R CMD INSTALL <pkg>\n\
                  — loads the linked .so and writes src/rust/wasm_registry.rs.\n\
               2. wasm32 build: cross-compile, which reads the file from step 1.\n\
             \n\
             For a wasm install from a tarball, the tarball must already contain\n\
             wasm_registry.rs (written by a host install, then packed by\n\
             `R CMD build`). The wasm32 .so is a SIDE_MODULE host R cannot\n\
             dyn.load, so there is no wasm-side regeneration fallback."
        )
    });

    let header_version: u32 = content
        .lines()
        .find_map(|l| l.strip_prefix("// generator-version: "))
        .and_then(|v| v.trim().parse().ok())
        .expect("wasm_registry.rs is missing or malformed `// generator-version: N` header");

    // Mirror miniextendr-api/src/wasm_registry_writer.rs GENERATOR_VERSION.
    // Bump both together when the generated-file shape changes.
    const EXPECTED_VERSION: u32 = 2;
    if header_version != EXPECTED_VERSION {
        panic!(
            "wasm_registry.rs was generated by miniextendr generator-version {header_version}, \
             but this build expects version {EXPECTED_VERSION}. \
             Run `R CMD INSTALL <pkg>` on the host to regenerate it."
        );
    }
}
