fn main() {
    miniextendr_lint::build_script();

    println!("cargo:rerun-if-changed=wasm_registry.rs");

    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    if target_arch != "wasm32" {
        return;
    }

    let path = std::path::Path::new("wasm_registry.rs");
    let content = std::fs::read_to_string(path).unwrap_or_else(|_| {
        panic!(
            "wasm32 build requires src/rust/wasm_registry.rs.\n\
             Run `just rcmdinstall` (or equivalent R CMD INSTALL) on the host to regenerate it."
        )
    });

    let header_version: u32 = content
        .lines()
        .find_map(|l| l.strip_prefix("// generator-version: "))
        .and_then(|v| v.trim().parse().ok())
        .expect("wasm_registry.rs is missing or malformed `// generator-version: N` header");

    // Mirror miniextendr-api/src/wasm_registry_writer.rs GENERATOR_VERSION.
    // Bump both together when the generated-file shape changes.
    const EXPECTED_VERSION: u32 = 1;
    if header_version != EXPECTED_VERSION {
        panic!(
            "wasm_registry.rs was generated by miniextendr generator-version {header_version}, \
             but this build expects version {EXPECTED_VERSION}. \
             Run `just rcmdinstall` on the host to regenerate it."
        );
    }
}
