//! `RSlot` sidecar fields: R values kept in an external pointer's `prot` list.
//!
//! A Rust struct cannot root an R value: the GC doesn't trace Rust memory, so a
//! `SEXP` stored in a struct field is freed as soon as R drops its own
//! references. An `RSlot` field holds no data. Its value lives in the external
//! pointer's protection list, after the type ID and the user slot, so the
//! pointer roots it for as long as the pointer is reachable, and `saveRDS`
//! writes it with the pointer.

use std::any::Any;
use std::marker::PhantomData;

use super::{ExternalPtr, PROT_TYPE_ID_INDEX, PROT_VEC_LEN, TypedExternal};
use crate::sys::{R_ExternalPtrAddr, R_ExternalPtrProtected};
use crate::{R_xlen_t, SEXP, SEXPTYPE, SexpExt};

// region: Marker and key

/// A sidecar field holding an R value.
///
/// Declare it as `#[r_data] pub keys: RSlot` on a `#[derive(ExternalPtr)]`
/// struct. The field itself is zero-sized: the value lives in the external
/// pointer's protection list, which roots it while the pointer is reachable
/// and serializes it with the pointer.
///
/// - R reads and writes it through the generated `Type_get_keys(x)` /
///   `Type_set_keys(x, value)`, an R6 active binding (`r6(r_data_accessors)`)
///   or an S7 property (`s7(r_data_accessors)`). It reads `NULL` until set.
/// - Rust reads and writes it through [`ExternalPtr::r_slot`] /
///   [`ExternalPtr::set_r_slot`], with the key the derive generates for the
///   field, `Type::KEYS_SLOT`. A method reaches the pointer with a
///   `self: &ExternalPtr<Self>` receiver.
///
/// ```ignore
/// #[derive(ExternalPtr)]
/// pub struct Engine {
///     #[r_data]
///     _r: RSidecar,
///     #[r_data]
///     pub keys: RSlot,
/// }
///
/// #[miniextendr(env)]
/// impl Engine {
///     pub fn n_keys(self: &ExternalPtr<Self>) -> i32 {
///         i32::try_from(self.r_slot(Self::KEYS_SLOT).len()).unwrap_or(i32::MAX)
///     }
/// }
/// ```
///
/// A plain `SEXP` field under `#[r_data]` is a compile error: nothing would
/// root it.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
pub struct RSlot;

/// The position of one [`RSlot`] field of `T` in the external pointer's
/// protection list.
///
/// `#[derive(ExternalPtr)]` generates one per field, named after it:
/// `Type::KEYS_SLOT` for `keys`. Pass it to [`ExternalPtr::r_slot`] /
/// [`ExternalPtr::set_r_slot`].
pub struct RSlotKey<T> {
    index: usize,
    _type: PhantomData<fn() -> T>,
}

impl<T> RSlotKey<T> {
    /// The key of `T`'s `index`-th `RSlot` field, counting from 0.
    ///
    /// Generated by `#[derive(ExternalPtr)]`; `index` must be below
    /// `T::R_SLOT_COUNT`.
    #[doc(hidden)]
    pub const fn new(index: usize) -> Self {
        Self {
            index,
            _type: PhantomData,
        }
    }
}

impl<T> Clone for RSlotKey<T> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<T> Copy for RSlotKey<T> {}

impl<T> std::fmt::Debug for RSlotKey<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("RSlotKey").field(&self.index).finish()
    }
}

// endregion

// region: Protection-list access

/// The protection-list position of `RSlot` field `index`.
fn prot_index(index: usize) -> R_xlen_t {
    let index = R_xlen_t::try_from(index).expect("RSlot index exceeds R_xlen_t::MAX");
    PROT_VEC_LEN + index
}

/// Whether `sym` is the symbol of `T`'s type ID.
///
/// Compares names rather than installing `T`'s symbol, so it allocates nothing.
fn is_type_id_symbol<T: TypedExternal>(sym: SEXP) -> bool {
    if sym.type_of() != SEXPTYPE::SYMSXP {
        return false;
    }
    let id = T::TYPE_ID_CSTR
        .strip_suffix(b"\0")
        .unwrap_or(T::TYPE_ID_CSTR);
    let printname = sym.printname();
    // SAFETY: a CHARSXP's data holds `len` bytes.
    let name =
        unsafe { std::slice::from_raw_parts(printname.r_char().cast::<u8>(), printname.len()) };
    name == id
}

/// The `prot` list of `x`, after checking that `x` is an external pointer to
/// a `T`. Allocates nothing.
///
/// A live pointer is checked by `Any::downcast`. A pointer whose address is
/// NULL (finalized, or read back by `readRDS`) still holds its `RSlot`
/// values, so it is accepted when its stored type ID is `T`'s.
///
/// # Panics
///
/// When `x` is not an external pointer to a `T`.
///
/// # Safety
///
/// Must be called from R's main thread with a valid `x`.
unsafe fn checked_prot<T: TypedExternal>(x: SEXP) -> SEXP {
    if x.type_of() != SEXPTYPE::EXTPTRSXP {
        panic!(
            "expected ExternalPtr<{}>, got a non-external-pointer object",
            T::TYPE_NAME
        );
    }
    let prot = unsafe { R_ExternalPtrProtected(x) };
    let any_raw = unsafe { R_ExternalPtrAddr(x) }.cast::<Box<dyn Any>>();
    let is_t = if any_raw.is_null() {
        prot.type_of() == SEXPTYPE::VECSXP
            && prot.len() > 0
            && is_type_id_symbol::<T>(prot.vector_elt(PROT_TYPE_ID_INDEX))
    } else {
        unsafe { &*any_raw }.is::<T>()
    };
    if !is_t {
        panic!("expected ExternalPtr<{}>", T::TYPE_NAME);
    }
    prot
}

/// Reads `T`'s `RSlot` field `index` from the external pointer `x`; `NULL`
/// when the pointer's protection list has no such slot.
///
/// Called by the getters `#[derive(ExternalPtr)]` generates.
///
/// # Panics
///
/// When `x` is not an external pointer to a `T`.
///
/// # Safety
///
/// Must be called from R's main thread with a valid `x`.
#[doc(hidden)]
pub unsafe fn r_slot_from_sexp<T: TypedExternal>(x: SEXP, index: usize) -> SEXP {
    let prot = unsafe { checked_prot::<T>(x) };
    let at = prot_index(index);
    if usize::try_from(at).is_ok_and(|at| at < prot.len()) {
        prot.vector_elt(at)
    } else {
        SEXP::nil()
    }
}

/// Stores `value` in `T`'s `RSlot` field `index` of the external pointer `x`.
///
/// Called by the setters `#[derive(ExternalPtr)]` generates. Allocates
/// nothing, so `value` needs no protection across the call.
///
/// # Panics
///
/// When `x` is not an external pointer to a `T`, or its protection list has
/// no such slot.
///
/// # Safety
///
/// Must be called from R's main thread with valid `x` and `value`.
#[doc(hidden)]
pub unsafe fn set_r_slot_in_sexp<T: TypedExternal>(x: SEXP, index: usize, value: SEXP) {
    let prot = unsafe { checked_prot::<T>(x) };
    let at = prot_index(index);
    if !usize::try_from(at).is_ok_and(|at| at < prot.len()) {
        panic!(
            "ExternalPtr<{}> has no RSlot {index}: its protection list was not built by `ExternalPtr`",
            T::TYPE_NAME
        );
    }
    prot.set_vector_elt(at, value);
}

impl<T: TypedExternal> ExternalPtr<T> {
    /// The R value in the [`RSlot`] field `key`; `NULL` until one is set.
    ///
    /// Must be called on R's main thread.
    #[inline]
    pub fn r_slot(&self, key: RSlotKey<T>) -> SEXP {
        unsafe { r_slot_from_sexp::<T>(self.as_sexp(), key.index) }
    }

    /// Stores `value` in the [`RSlot`] field `key`.
    ///
    /// The external pointer roots `value` from here on, so it stays valid as
    /// long as the pointer is reachable. Must be called on R's main thread.
    #[inline]
    pub fn set_r_slot(&self, key: RSlotKey<T>, value: SEXP) {
        unsafe { set_r_slot_in_sexp::<T>(self.as_sexp(), key.index, value) }
    }

    /// Copies every `RSlot` value of `source` into `self`, on R's main thread.
    pub(super) fn copy_r_slots_from(&self, source: &Self) {
        if T::R_SLOT_COUNT == 0 {
            return;
        }
        let (dest, src) = (self.as_sexp(), source.as_sexp());
        crate::worker::with_r_thread(move || {
            for index in 0..T::R_SLOT_COUNT {
                // SAFETY: on R's main thread; both are external pointers to a
                // `T`, and storing allocates nothing.
                unsafe {
                    set_r_slot_in_sexp::<T>(dest, index, r_slot_from_sexp::<T>(src, index));
                }
            }
        });
    }
}

// endregion
