test_that("ALTREP constructors cover all classes", {
  expect_equal(length(constant_int()), 10L)
  expect_equal(length(constant_real()), 10L)
  expect_equal(length(arith_seq(0, 1, 5L)), 5L)
  expect_equal(length(lazy_int_seq(1L, 5L, 1L)), 5L)
  expect_equal(length(constant_logical(1L, 2L)), 2L)
  expect_equal(length(altrep_from_logicals(c(TRUE, FALSE, NA))), 3L)
  expect_equal(length(lazy_string("x", 2L)), 2L)
  expect_equal(length(repeating_raw(as.raw(c(1, 2)), 3L)), 3L)
  expect_equal(length(unit_circle(4L)), 4L)
  expect_equal(length(altrep_from_integers(1:3)), 3L)
  expect_equal(length(altrep_from_strings(c("a", "b"))), 2L)
  expect_equal(length(altrep_from_raw(as.raw(1:3))), 3L)
  expect_equal(length(altrep_from_doubles(c(1, 2))), 2L)
  expect_equal(length(boxed_ints(3L)), 3L)
  expect_equal(length(static_ints()), 5L)
  expect_equal(length(static_strings()), 4L)
  expect_equal(length(altrep_from_list(list(1L, 2L))), 2L)
})

test_that("Box ALTREP builtins cover all base types", {
  reals <- boxed_reals(4L)
  expect_equal(reals, c(1.5, 3.0, 4.5, 6.0))
  expect_equal(reals + 1.0, c(2.5, 4.0, 5.5, 7.0))

  logicals <- boxed_logicals(4L)
  expect_true(logicals[1])
  expect_false(logicals[2])
  expect_true(logicals[3])
  expect_false(logicals[4])

  raw_bytes <- boxed_raw(3L)
  expect_equal(raw_bytes[1], as.raw(0))
  expect_equal(raw_bytes[2], as.raw(1))
  expect_equal(raw_bytes[3], as.raw(2))

  strings <- boxed_strings(3L)
  expect_equal(strings, c("boxed_0", "boxed_1", "boxed_2"))

  complex_vals <- boxed_complex(3L)
  expect_equal(Re(complex_vals[1]), 0.25)
  expect_equal(Im(complex_vals[1]), 0.75)
  expect_equal(Re(complex_vals[3]), 2.25)
  expect_equal(Im(complex_vals[3]), 2.75)
})

test_that("Vec and Range ALTREP builtins cover additional types", {
  complex_vec <- vec_complex_altrep(3L)
  expect_equal(length(complex_vec), 3L)
  expect_equal(Re(complex_vec[1]), 0)
  expect_equal(Im(complex_vec[1]), 0)
  expect_equal(Re(complex_vec[3]), 2)
  expect_equal(Im(complex_vec[3]), -2)

  r64 <- range_i64_altrep(1L, 6L)
  expect_equal(length(r64), 5L)
  expect_equal(sum(r64), 15L)
  expect_equal(min(r64), 1L)
  expect_equal(max(r64), 5L)

  rreal <- range_real_altrep(0.5, 3.5)
  expect_equal(length(rreal), 3L)
  expect_equal(rreal[1], 0.5)
  expect_equal(rreal[3], 2.5)
  expect_equal(sum(rreal), 4.5)
  expect_equal(min(rreal), 0.5)
  expect_equal(max(rreal), 2.5)
})
