test_that("cooperative interrupts preserve class, call, and Rust cleanup", {
  skip_if_not(exists("ctrlc_interrupt", asNamespace("miniextendr")))
  before <- miniextendr:::ctrlc_drop_count()
  caught <- tryCatch(miniextendr:::ctrlc_interrupt(), interrupt = identity)
  expect_identical(class(caught), c("rust_interrupt", "interrupt", "condition"))
  expect_false(inherits(caught, "error"))
  expect_identical(caught$kind, "interrupt")
  expect_identical(conditionCall(caught), quote(miniextendr:::ctrlc_interrupt()))
  expect_identical(conditionMessage(caught), "Interrupted")
  expect_identical(miniextendr:::ctrlc_drop_count(), before + 1L)
  expect_identical(miniextendr:::ctrlc_wait(0L), 42L)
})

test_that("interrupt transport survives GC and trait-ABI reconstruction", {
  skip_if_not(exists("gc_stress_ctrlc_roundtrip", asNamespace("miniextendr")))
  gctorture(TRUE)
  on.exit(gctorture(FALSE))
  roundtrip <- miniextendr:::gc_stress_ctrlc_roundtrip()
  caught <- tryCatch(miniextendr:::ctrlc_interrupt(), interrupt = identity)
  gctorture(FALSE)
  expect_true(roundtrip)
  expect_identical(class(caught), c("rust_interrupt", "interrupt", "condition"))
})

test_that("checkpoint time limits remain errors and unwind owned resources", {
  skip_if_not(exists("ctrlc_wait", asNamespace("miniextendr")))
  before <- miniextendr:::ctrlc_drop_count()
  on.exit(setTimeLimit(cpu = Inf, elapsed = Inf, transient = FALSE))
  caught <- tryCatch({
    setTimeLimit(elapsed = 0.1, transient = TRUE)
    miniextendr:::ctrlc_wait(5L)
  }, error = identity)
  setTimeLimit(cpu = Inf, elapsed = Inf, transient = FALSE)
  expect_s3_class(caught, "error")
  expect_false(inherits(caught, "interrupt"))
  expect_match(conditionMessage(caught), "time limit")
  expect_identical(miniextendr:::ctrlc_drop_count(), before + 1L)
})

test_that("the native boundary returns an interrupt value before R signalling", {
  skip_if_not(exists("ctrlc_interrupt", asNamespace("miniextendr")))
  before <- miniextendr:::ctrlc_drop_count()
  symbol <- get("C_miniextendr_ctrlc_interrupt", asNamespace("miniextendr"))
  value <- .Call(symbol, NULL)
  expect_s3_class(value, "rust_condition_value")
  expect_true(attr(value, "__rust_condition__"))
  expect_identical(value$kind, "interrupt")
  expect_identical(miniextendr:::ctrlc_drop_count(), before + 1L)
})
