#!/usr/bin/env bash
# Guard against committing build artifacts: vendor tarballs, vendored crate
# trees, cargo and R CMD build/check output, rpkg's configure- and
# install-generated files, and any file over a size limit.
#
# WHY
# ---
# rpkg/inst/vendor.tar.xz runs to ~20 MiB, and every committed copy stays in
# the history that each clone downloads; a later deletion doesn't remove it.
# A .gitignore rule stops `git add -A`, but not `git add -f`, a checkout from
# before the rule, or an artifact at a new path. This script is the backstop. CI (the Generated Files
# Check job in .github/workflows/ci.yml) runs it over the tree and over every
# commit a PR or push adds, and .githooks/pre-commit runs it over the index.
#
# WHAT IT CHECKS
# --------------
# Every file in scope is matched against the path rules below and the size
# limit (MAX_FILE_MIB, default 5 MiB; the largest tracked file is ~0.25 MiB).
#
#   (no argument)   every file tracked at HEAD
#   <base>..<head>  every file tracked at HEAD, plus every file that each
#                   commit in the range adds or modifies (diffed against its
#                   first parent). Rebase-merge keeps every commit, so a
#                   tarball that one commit adds and a later commit deletes
#                   still lands in main's history.
#   --staged        every file the index adds or modifies (pre-commit hook)
#
# Deletions never trip it, so the commit that untracks an artifact passes.
# If a legitimate path ever matches a rule, narrow that rule here and say why
# in the PR. Don't add an allowlist.
#
# EXIT CODE
# ---------
# Non-zero iff anything was flagged. Each hit is printed with where it was
# found (HEAD, index, or a commit) and ends with a fix hint. Under GitHub
# Actions, each hit is also an ::error:: annotation.
#
# USAGE
#   bash scripts/committed-artifacts-check.sh                # tracked tree
#   bash scripts/committed-artifacts-check.sh origin/main..HEAD
#   bash scripts/committed-artifacts-check.sh --staged
#   just committed-artifacts-check [<base>..<head>]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

max_mib="${MAX_FILE_MIB:-5}"
max_bytes=$((max_mib * 1024 * 1024))

# Path rules (bash ERE against the repo-relative path) and what a match is.
# The rpkg-scoped rule stays scoped: tests/model_project and the cross-package
# fixtures track their generated wrappers on purpose.
rule_res=(
    '(^|/)vendor\.tar\.xz$'
    '(^|/)vendor/'
    '(^|/)(target|rust-target[^/]*|ra[-_]target)/'
    '(^|/)[^/]+\.Rcheck/|(^|/)rpkg-check-output/'
    '(^|/)[A-Za-z][A-Za-z0-9.]*_[0-9][0-9.-]*\.(tar\.gz|tgz|zip)$'
    '^rpkg/src/Makevars$|^rpkg/src/[^/]*-win\.def$|^rpkg/src/rust/\.cargo/|^rpkg/(R|src)/[^/]*-wrappers\.R$|^rpkg/src/rust/wasm_registry\.rs$|^rpkg/src/rust/\.Cargo\.toml\.prefreeze$'
)
rule_whats=(
    'vendor tarball: the release step ("just vendor", miniextendr_build_tarball()) makes it, CI builds its own'
    'vendored crate sources: cargo vendor / cargo-revendor output'
    'cargo build output'
    'R CMD check output'
    'R package archive: R CMD build / R CMD INSTALL --build output'
    'generated by rpkg configure, R CMD INSTALL or cargo revendor --freeze'
)

mode=tree
range=""
case "${1:-}" in
    "") ;;
    --staged) mode=staged ;;
    -h|--help) sed -n '2,/^set -euo/{/^set -euo/d;s/^# \{0,1\}//;p;}' "$0"; exit 0 ;;
    *..*) mode=range; range="$1" ;;
    *) echo "usage: $0 [--staged | <base>..<head>]" >&2; exit 2 ;;
esac

# Parallel arrays: one entry per (file version, where it was found).
paths=()
shas=()
wheres=()

# Read `git diff --raw -z --no-renames` records (":om nm os ns status\0path\0")
# from stdin. Gitlinks (mode 160000) have no blob to size.
add_raw_records() {
    local where="$1" meta path nm ns
    while IFS= read -r -d '' meta && IFS= read -r -d '' path; do
        read -r _ nm _ ns _ <<<"${meta#:}"
        [ "$nm" = 160000 ] && continue
        paths+=("$path"); shas+=("$ns"); wheres+=("$where")
    done
}

if [ "$mode" = staged ]; then
    add_raw_records index < <(git diff --cached --raw -z --no-renames --diff-filter=ACMT)
else
    while IFS= read -r -d '' rec; do
        read -r _ type sha <<<"${rec%%$'\t'*}"
        [ "$type" = blob ] || continue
        paths+=("${rec#*$'\t'}"); shas+=("$sha"); wheres+=(HEAD)
    done < <(git ls-tree -r -z --full-tree HEAD)
fi

tree_files="${#paths[@]}"
ncommits=0
if [ "$mode" = range ]; then
    if ! commits="$(git rev-list --reverse "$range" 2>/dev/null)"; then
        echo "error: cannot resolve commit range '$range' (are both ends fetched?)" >&2
        exit 2
    fi
    for c in $commits; do
        ncommits=$((ncommits + 1))
        short="commit $(git rev-parse --short "$c")"
        if parent="$(git rev-parse -q --verify "$c^1")"; then
            add_raw_records "$short" < <(git diff-tree -r -z --no-renames --diff-filter=ACMT "$parent" "$c")
        else
            add_raw_records "$short" < <(git diff-tree -r -z --root --no-commit-id --no-renames --diff-filter=ACMT "$c")
        fi
    done
fi

# Blob sizes in one batch, in input order ("<sha> missing" for absent objects).
sizes=()
if [ "${#shas[@]}" -gt 0 ]; then
    while IFS= read -r line; do
        sizes+=("$line")
    done < <(printf '%s\n' "${shas[@]}" | git cat-file --batch-check='%(objectsize)')
fi

# GitHub workflow-command escaping: data needs %, CR and LF encoded; property
# values (file=) also need : and , encoded.
gh_data() { local s="${1//%/%25}"; s="${s//$'\r'/%0D}"; printf '%s' "${s//$'\n'/%0A}"; }
gh_prop() { local s; s="$(gh_data "$1")"; s="${s//:/%3A}"; printf '%s' "${s//,/%2C}"; }

hits=0
tree_hits=0
commit_hits=0
flag() {
    local path="$1" where="$2" why="$3"
    if [ "$hits" -eq 0 ]; then
        echo "Build artifacts or oversized files are committed or staged:"
    fi
    hits=$((hits + 1))
    case "$where" in
        commit*) commit_hits=$((commit_hits + 1)) ;;
        *) tree_hits=$((tree_hits + 1)) ;;
    esac
    echo "  $path  [$where]  $why"
    if [ "${GITHUB_ACTIONS:-}" = true ]; then
        echo "::error file=$(gh_prop "$path"),title=Committed build artifact::$(gh_data "$path [$where]: $why")"
    fi
}

for i in "${!paths[@]}"; do
    path="${paths[$i]}"
    for j in "${!rule_res[@]}"; do
        if [[ $path =~ ${rule_res[$j]} ]]; then
            flag "$path" "${wheres[$i]}" "${rule_whats[$j]}"
            break
        fi
    done
    size="${sizes[$i]:-}"
    if [[ $size =~ ^[0-9]+$ ]] && [ "$size" -gt "$max_bytes" ]; then
        flag "$path" "${wheres[$i]}" "$(awk -v b="$size" -v m="$max_mib" 'BEGIN { printf "%.1f MiB, over the %s MiB limit", b / 1048576, m }')"
    fi
done

if [ "$hits" -eq 0 ]; then
    # Silent for the pre-commit hook; a one-line receipt in CI logs.
    if [ "$mode" = tree ]; then
        echo "No build artifacts or files over ${max_mib} MiB in the $tree_files files at HEAD."
    elif [ "$mode" = range ]; then
        echo "No build artifacts or files over ${max_mib} MiB in the $tree_files files at HEAD" \
            "or the $(( ${#paths[@]} - tree_files )) file versions that $ncommits commit(s) in $range add or modify."
    fi
    exit 0
fi

echo ""
if [ "$tree_hits" -gt 0 ]; then
    echo "Untrack it. The file stays on disk, and artifact paths are already gitignored:"
    echo "    git rm --cached <path>        # add -r for a directory"
fi
if [ "$commit_hits" -gt 0 ]; then
    echo "A commit in $range adds or changes the file. Deleting it later is not enough:"
    echo "rebase-merge still puts the adding commit, and the blob, on main. Rewrite the"
    echo "branch so that no commit adds it, then force-push. Either squash the branch, or"
    echo "run 'git rebase -i ${range%%..*}', mark the commit that adds it as 'edit', and"
    echo "at that stop run 'git rm --cached <path>', 'git commit --amend' and"
    echo "'git rebase --continue'."
fi
echo "Vendor tarballs and R source packages are build outputs. CI builds its own, and on"
echo "main the CRAN-like check uploads the vendored source package as the"
echo "miniextendr-source-package workflow artifact."
echo "If a large file really is source, raise MAX_FILE_MIB in the Generated Files Check"
echo "job and say why in the PR."
exit 1
