//! # Type Conversion Helpers for Method Shims
//!
//! This module provides type conversion functions used by the generated
//! method shims from `#[miniextendr]` traits. These functions wrap the existing
//! [`TryFromSexp`] and [`IntoR`] traits with appropriate error handling.
//!
//! ## Purpose
//!
//! Method shims generated by `#[miniextendr]` traits need to:
//! 1. Convert SEXP arguments to Rust types
//! 2. Convert Rust return values to SEXP
//! 3. Handle conversion errors gracefully (via `r_stop`)
//!
//! This module provides a uniform interface for these conversions.
//!
//! ## Error Handling
//!
//! Conversion errors are handled by calling [`r_stop`], which raises
//! an R error and unwinds back to R. This ensures that:
//! - Invalid arguments produce helpful error messages
//! - R's error handling mechanism is used consistently
//! - No Rust panics escape to R
//!
//! ## Thread Safety
//!
//! All functions in this module must be called on R's main thread,
//! as they interact with R's SEXP values and error handling.
//!
//! [`TryFromSexp`]: crate::TryFromSexp
//! [`IntoR`]: crate::IntoR
//! [`r_stop`]: crate::r_stop

use crate::ffi::SEXP;

/// Raise an R error with the given message.
///
/// This is a thin wrapper around [`crate::r_stop`] for use in method shims.
/// It never returns (diverges to R's error handler).
///
/// # Arguments
///
/// * `msg` - Error message to display
///
/// # Safety
///
/// - Must be called on R's main thread
/// - Never returns (uses R's `Rf_error` which longjmps)
///
/// # Example
///
/// ```ignore
/// if argc != 2 {
///     unsafe { rf_error("expected 2 arguments, got {argc}"); }
/// }
/// ```
#[inline]
pub unsafe fn rf_error(msg: &str) -> ! {
    crate::error::r_stop(msg)
}

/// Return R's `NULL` value.
///
/// Convenience function for method shims returning nothing.
///
/// # Safety
///
/// - Must be called on R's main thread (accesses R_NilValue)
///
/// # Returns
///
/// R's `NULL` value (`R_NilValue`)
#[inline]
pub unsafe fn nil() -> SEXP {
    unsafe { crate::ffi::R_NilValue }
}

/// Convert an R SEXP to a Rust type.
///
/// Wrapper around [`crate::TryFromSexp::try_from_sexp`] that calls [`rf_error`]
/// on conversion failure.
///
/// # Type Parameters
///
/// * `T` - Target Rust type (must implement [`TryFromSexp`])
///
/// # Arguments
///
/// * `x` - R value to convert
///
/// # Returns
///
/// The converted Rust value.
///
/// # Safety
///
/// - `x` must be a valid SEXP
/// - Must be called on R's main thread
///
/// # Errors
///
/// Calls [`rf_error`] (never returns) if conversion fails. Error messages
/// are generated by [`TryFromSexp`]'s error type's `Display` impl.
///
/// # Example
///
/// ```ignore
/// // In a method shim:
/// let arg0: i32 = unsafe { from_sexp(argv[0]) };
/// let arg1: String = unsafe { from_sexp(argv[1]) };
/// ```
///
/// [`TryFromSexp`]: crate::TryFromSexp
#[inline]
pub unsafe fn from_sexp<T>(x: SEXP) -> T
where
    T: crate::TryFromSexp,
    T::Error: std::fmt::Display,
{
    match T::try_from_sexp(x) {
        Ok(val) => val,
        Err(e) => unsafe { rf_error(&e.to_string()) },
    }
}

/// Convert a Rust value to an R SEXP.
///
/// Wrapper around [`crate::IntoR::into_sexp`] for use in method shims.
///
/// # Type Parameters
///
/// * `T` - Source Rust type (must implement [`IntoR`])
///
/// # Arguments
///
/// * `x` - Rust value to convert
///
/// # Returns
///
/// R SEXP representation of the value.
///
/// # Safety
///
/// - Must be called on R's main thread
/// - The returned SEXP must be protected if used across R allocations
///
/// # Example
///
/// ```ignore
/// // In a method shim:
/// let result: f64 = self_ref.area();
/// unsafe { to_sexp(result) }
/// ```
///
/// [`IntoR`]: crate::IntoR
#[inline]
pub unsafe fn to_sexp<T>(x: T) -> SEXP
where
    T: crate::IntoR,
{
    x.into_sexp()
}

/// Convert an R SEXP to a Rust type, returning a Result.
///
/// Unlike [`from_sexp`], this function returns a `Result` instead of
/// calling `rf_error` on failure. Useful when you want custom error handling.
///
/// # Type Parameters
///
/// * `T` - Target Rust type (must implement [`TryFromSexp`])
///
/// # Arguments
///
/// * `x` - R value to convert
///
/// # Returns
///
/// `Ok(T)` on success, `Err` with the conversion error on failure.
///
/// # Safety
///
/// - `x` must be a valid SEXP
/// - Must be called on R's main thread
///
/// # Example
///
/// ```ignore
/// match unsafe { try_from_sexp::<i32>(argv[0]) } {
///     Ok(val) => { /* use val */ }
///     Err(e) => {
///         // Custom error handling
///         rf_error(&format!("argument 1: {}", e));
///     }
/// }
/// ```
///
/// [`TryFromSexp`]: crate::TryFromSexp
#[inline]
pub unsafe fn try_from_sexp<T>(x: SEXP) -> Result<T, T::Error>
where
    T: crate::TryFromSexp,
{
    T::try_from_sexp(x)
}

// =============================================================================
// Argument extraction helpers
// =============================================================================

/// Extract and convert an argument from argv with bounds checking.
///
/// Checks that `index < argc` before extracting, and provides a helpful
/// error message if out of bounds.
///
/// # Type Parameters
///
/// * `T` - Target Rust type (must implement [`TryFromSexp`])
///
/// # Arguments
///
/// * `argc` - Number of arguments
/// * `argv` - Pointer to argument array
/// * `index` - Index of argument to extract
/// * `name` - Name of argument (for error messages)
///
/// # Returns
///
/// The converted argument value.
///
/// # Safety
///
/// - `argv` must point to at least `argc` valid SEXPs
/// - Must be called on R's main thread
///
/// # Errors
///
/// Calls [`rf_error`] if:
/// - `index >= argc` (missing argument)
/// - Conversion fails
///
/// # Example
///
/// ```ignore
/// // In a method shim for fn foo(&self, x: i32, y: String)
/// let x: i32 = unsafe { extract_arg(argc, argv, 0, "x") };
/// let y: String = unsafe { extract_arg(argc, argv, 1, "y") };
/// ```
///
/// [`TryFromSexp`]: crate::TryFromSexp
#[inline]
pub unsafe fn extract_arg<T>(argc: i32, argv: *const SEXP, index: usize, name: &str) -> T
where
    T: crate::TryFromSexp,
    T::Error: std::fmt::Display,
{
    if index as i32 >= argc {
        unsafe { rf_error(&format!("missing argument: {name}")) };
    }
    unsafe { from_sexp(*argv.add(index)) }
}

/// Check that the number of arguments matches expected arity.
///
/// # Arguments
///
/// * `argc` - Actual number of arguments
/// * `expected` - Expected number of arguments
/// * `method_name` - Name of method (for error messages)
///
/// # Safety
///
/// Must be called on R's main thread (may call `rf_error`).
///
/// # Errors
///
/// Calls [`rf_error`] if `argc != expected`.
#[inline]
pub unsafe fn check_arity(argc: i32, expected: i32, method_name: &str) {
    if argc != expected {
        unsafe {
            rf_error(&format!(
                "{method_name}: expected {expected} arguments, got {argc}"
            ))
        };
    }
}
