//! Snapshot tests for macro-generated R wrapper code.
//!
//! These tests verify that `#[miniextendr]` generates the expected R wrapper strings.
//! Each test applies the proc macro to a small Rust function or impl block, then
//! checks the generated `R_WRAPPER_*` / `R_WRAPPERS_IMPL_*` const against an
//! inline snapshot (via `expect-test`).
//!
//! If a snapshot fails, run with `UPDATE_EXPECT=1 cargo test` to update inline expectations.
//!
//! Run with: `cargo test -p miniextendr-macros --test snapshots`

use expect_test::expect;
use miniextendr_api::miniextendr;

// =============================================================================
// Standalone function R wrappers
// =============================================================================

#[miniextendr]
pub fn add(x: i32, y: i32) -> i32 {
    x + y
}

#[miniextendr]
pub fn greet(name: String) -> String {
    format!("Hello, {}!", name)
}

#[miniextendr]
pub fn no_return(x: i32) {
    let _ = x;
}

#[miniextendr]
fn private_fn(x: f64) -> f64 {
    x * 2.0
}

#[miniextendr]
/// Compute the square of a number.
/// @param x A numeric value.
/// @return The squared value.
pub fn square(x: f64) -> f64 {
    x * x
}

#[miniextendr]
pub fn maybe_value(x: i32) -> Option<i32> {
    if x > 0 { Some(x) } else { None }
}

#[miniextendr]
pub fn fallible(x: i32) -> Result<String, String> {
    if x >= 0 {
        Ok(format!("positive: {x}"))
    } else {
        Err("negative".to_string())
    }
}

#[miniextendr(strict)]
pub fn strict_i64(x: i64) -> i64 {
    x + 1
}

#[miniextendr(internal)]
pub fn internal_fn(x: i32) -> i32 {
    x
}

#[miniextendr(noexport)]
pub fn noexport_fn(x: i32) -> i32 {
    x
}

/// A counter backed by Rust.
#[derive(Default, miniextendr_api::ExternalPtr)]
pub struct SnapCounter {
    value: i32,
}

#[miniextendr(env)]
impl SnapCounter {
    pub fn new() -> Self {
        Self::default()
    }

    /// Get the current value.
    pub fn get_value(&self) -> i32 {
        self.value
    }

    /// Increment by a step.
    /// @param step Amount to increment.
    pub fn increment(&mut self, step: i32) {
        self.value += step;
    }
}

/// An R6-based counter.
#[derive(miniextendr_api::ExternalPtr)]
pub struct SnapR6Counter {
    value: i32,
}

#[miniextendr(r6)]
impl SnapR6Counter {
    pub fn new(initial: i32) -> Self {
        Self { value: initial }
    }

    pub fn get(&self) -> i32 {
        self.value
    }
}

miniextendr_api::miniextendr_module! {
    mod snapshots;
    fn add;
    fn greet;
    fn no_return;
    fn private_fn;
    fn square;
    fn maybe_value;
    fn fallible;
    fn strict_i64;
    fn internal_fn;
    fn noexport_fn;
    impl SnapCounter;
    impl SnapR6Counter;
}

// =============================================================================
// Snapshot assertions
// =============================================================================

/// Normalize R wrapper output for snapshot comparison:
/// - Strip "# Generated from Rust source file: ..." header (contains env-specific paths)
/// - Strip trailing whitespace from each line (avoids git hook / editor conflicts)
fn strip_generated_header(s: &str) -> String {
    s.lines()
        .filter(|line| !line.starts_with("# Generated from Rust source file:"))
        .map(|line| line.trim_end())
        .collect::<Vec<_>>()
        .join("\n")
}

// -- Standalone function snapshots -------------------------------------------

#[test]
fn snapshot_add() {
    let wrapper = strip_generated_header(R_WRAPPER_ADD);
    expect![[r#"
        #' @source Generated by miniextendr from Rust fn `add`
          #' @export
          add <- function(x, y) {
            .Call(C_add, .call = match.call(), x, y)
          }"#]]
    .assert_eq(wrapper.trim());
}

#[test]
fn snapshot_greet() {
    let wrapper = strip_generated_header(R_WRAPPER_GREET);
    expect![[r#"
        #' @source Generated by miniextendr from Rust fn `greet`
          #' @export
          greet <- function(name) {
            .Call(C_greet, .call = match.call(), name)
          }"#]]
    .assert_eq(wrapper.trim());
}

#[test]
fn snapshot_no_return() {
    let wrapper = strip_generated_header(R_WRAPPER_NO_RETURN);
    expect![[r#"
        #' @source Generated by miniextendr from Rust fn `no_return`
          #' @export
          no_return <- function(x) {
            invisible(.Call(C_no_return, .call = match.call(), x))
          }"#]]
    .assert_eq(wrapper.trim());
}

#[test]
fn snapshot_private_fn() {
    // Non-pub functions should NOT have @export
    let wrapper = strip_generated_header(R_WRAPPER_PRIVATE_FN);
    expect![[r#"
        #' @source Generated by miniextendr from Rust fn `private_fn`
          private_fn <- function(x) {
            .Call(C_private_fn, .call = match.call(), x)
          }"#]]
    .assert_eq(wrapper.trim());
}

#[test]
fn snapshot_square_with_roxygen() {
    // User-provided roxygen tags should be preserved
    let wrapper = strip_generated_header(R_WRAPPER_SQUARE);
    expect![[r#"
        #' @title Compute the square of a number
          #' @param x A numeric value.
          #' @return The squared value.
          #' @source Generated by miniextendr from Rust fn `square`
          #' @export
          square <- function(x) {
            .Call(C_square, .call = match.call(), x)
          }"#]]
    .assert_eq(wrapper.trim());
}

#[test]
fn snapshot_maybe_value_option() {
    // Option<T> return should be visible (not invisible)
    let wrapper = strip_generated_header(R_WRAPPER_MAYBE_VALUE);
    expect![[r#"
        #' @source Generated by miniextendr from Rust fn `maybe_value`
          #' @export
          maybe_value <- function(x) {
            .Call(C_maybe_value, .call = match.call(), x)
          }"#]]
    .assert_eq(wrapper.trim());
}

#[test]
fn snapshot_fallible_result() {
    // Result<T, E> return should be visible
    let wrapper = strip_generated_header(R_WRAPPER_FALLIBLE);
    expect![[r#"
        #' @source Generated by miniextendr from Rust fn `fallible`
          #' @export
          fallible <- function(x) {
            .Call(C_fallible, .call = match.call(), x)
          }"#]]
    .assert_eq(wrapper.trim());
}

#[test]
fn snapshot_strict_i64() {
    // strict mode functions should look the same in R wrapper
    let wrapper = strip_generated_header(R_WRAPPER_STRICT_I64);
    expect![[r#"
        #' @source Generated by miniextendr from Rust fn `strict_i64`
          #' @export
          strict_i64 <- function(x) {
            .Call(C_strict_i64, .call = match.call(), x)
          }"#]]
    .assert_eq(wrapper.trim());
}

#[test]
fn snapshot_internal_fn() {
    // #[miniextendr(internal)] should add @keywords internal and suppress @export
    let wrapper = strip_generated_header(R_WRAPPER_INTERNAL_FN);
    expect![[r#"
        #' @source Generated by miniextendr from Rust fn `internal_fn`
          #' @keywords internal
          internal_fn <- function(x) {
            .Call(C_internal_fn, .call = match.call(), x)
          }"#]]
    .assert_eq(wrapper.trim());
}

#[test]
fn snapshot_noexport_fn() {
    // #[miniextendr(noexport)] should suppress @export only (no @keywords internal)
    let wrapper = strip_generated_header(R_WRAPPER_NOEXPORT_FN);
    expect![[r#"
        #' @source Generated by miniextendr from Rust fn `noexport_fn`
          noexport_fn <- function(x) {
            .Call(C_noexport_fn, .call = match.call(), x)
          }"#]]
    .assert_eq(wrapper.trim());
}

// -- Class system snapshots --------------------------------------------------

#[test]
fn snapshot_env_class() {
    let wrapper = strip_generated_header(R_WRAPPERS_IMPL_SNAPCOUNTER);
    expect![[r##"
        #' @title SnapCounter  Class
          #' @name SnapCounter
          #' @rdname SnapCounter
          #' @source Generated by miniextendr from Rust type `SnapCounter`
          #' @export
          SnapCounter <- new.env(parent = emptyenv())

          #' @name SnapCounter$new
          #' @rdname SnapCounter
          #' @source Generated by miniextendr from `SnapCounter::new`
          SnapCounter$new <- function() {
            self <- .Call(C_SnapCounter__new, .call = match.call())
            class(self) <- "SnapCounter"
            self
          }

          #' @description Get the current value.
          #' @name SnapCounter$get_value
          #' @rdname SnapCounter
          #' @source Generated by miniextendr from `SnapCounter::get_value`
          SnapCounter$get_value <- function() {
            .Call(C_SnapCounter__get_value, .call = match.call(), self)
          }

          #' @title Increment by a step
          #' @param step Amount to increment.
          #' @name SnapCounter$increment
          #' @rdname SnapCounter
          #' @source Generated by miniextendr from `SnapCounter::increment`
          SnapCounter$increment <- function(step) {
            .Call(C_SnapCounter__increment, .call = match.call(), self, step)
            self
          }

          #' @rdname SnapCounter
          #' @param self The object instance.
          #' @param name Method name for dispatch.
          #' @export
          `$.SnapCounter` <- function(self, name) {
            obj <- SnapCounter[[name]]
            if (is.environment(obj)) {
              # Trait namespace - bind self to all methods
              bound <- new.env(parent = emptyenv())
              for (method_name in names(obj)) {
                method <- obj[[method_name]]
                if (is.function(method)) {
                  environment(method) <- environment()
                  bound[[method_name]] <- method
                }
              }
              bound
            } else {
              environment(obj) <- environment()
              obj
            }
          }
          #' @rdname SnapCounter
          #' @export
          `[[.SnapCounter` <- `$.SnapCounter`"##]]
    .assert_eq(wrapper.trim());
}

#[test]
fn snapshot_r6_class() {
    let wrapper = strip_generated_header(R_WRAPPERS_IMPL_SNAPR6COUNTER);
    expect![[r##"
        #' @title SnapR6Counter R6 Class
          #' @name SnapR6Counter
          #' @rdname SnapR6Counter
          #' @source Generated by miniextendr from Rust type `SnapR6Counter`
          #' @importFrom R6 R6Class
          #' @param .ptr Internal pointer (used by static methods, not for direct use).
          #' @export
          SnapR6Counter <- R6::R6Class("SnapR6Counter",
            public = list(
              initialize = function(initial, .ptr = NULL) {
                if (!is.null(.ptr)) {
                  private$.ptr <- .ptr
                } else {
                  private$.ptr <- .Call(C_SnapR6Counter__new, .call = match.call(), initial)
                }
              },
              get = function() {
                .Call(C_SnapR6Counter__get, .call = match.call(), private$.ptr)
              }
            ),
            private = list(
              .ptr = NULL
            ),
            lock_objects = TRUE,
            lock_class = FALSE,
            cloneable = FALSE
          )"##]]
    .assert_eq(wrapper.trim());
}
