//! ALTREP implementation utilities.
//!
//! This module provides helper functions for implementing ALTREP classes.
//! The proc-macro uses these to generate trait implementations.
//!
//! Use `crate::altrep_data1_as` (re-exported from externalptr) to extract
//! data from an ALTREP's data1 slot.

// =============================================================================
// Macros for generating trait implementations
// =============================================================================

/// Generate ALTREP trait implementations for a type that implements AltIntegerData.
///
/// This macro generates `impl Altrep`, `impl AltVec`, and `impl AltInteger` for the type,
/// delegating to the high-level `AltIntegerData` trait methods.
///
/// **Requires**: The type must implement `TypedExternal` (use `#[derive(ExternalPtr)]`).
///
/// ## Variants
///
/// ```ignore
/// // Basic (no dataptr, no serialization):
/// impl_altinteger_from_data!(MyType);
///
/// // With dataptr (type must implement AltrepDataptr<i32>):
/// impl_altinteger_from_data!(MyType, dataptr);
///
/// // With serialization (type must implement AltrepSerialize):
/// impl_altinteger_from_data!(MyType, serialize);
///
/// // With subset optimization (type must implement AltrepExtractSubset):
/// impl_altinteger_from_data!(MyType, subset);
///
/// // Combine multiple options:
/// impl_altinteger_from_data!(MyType, dataptr, serialize);
/// impl_altinteger_from_data!(MyType, subset, serialize);
/// ```
#[macro_export]
macro_rules! impl_altinteger_from_data {
    ($ty:ty) => {
        $crate::__impl_altrep_base!($ty);
        impl $crate::altrep_traits::AltVec for $ty {}
        $crate::__impl_altinteger_methods!($ty);
        $crate::impl_inferbase_integer!($ty);
    };
    ($ty:ty, dataptr) => {
        $crate::__impl_altrep_base!($ty);
        $crate::__impl_altvec_dataptr!($ty, i32);
        $crate::__impl_altinteger_methods!($ty);
        $crate::impl_inferbase_integer!($ty);
    };
    ($ty:ty, serialize) => {
        $crate::__impl_altrep_base_with_serialize!($ty);
        impl $crate::altrep_traits::AltVec for $ty {}
        $crate::__impl_altinteger_methods!($ty);
        $crate::impl_inferbase_integer!($ty);
    };
    ($ty:ty, subset) => {
        $crate::__impl_altrep_base!($ty);
        $crate::__impl_altvec_extract_subset!($ty);
        $crate::__impl_altinteger_methods!($ty);
        $crate::impl_inferbase_integer!($ty);
    };
    ($ty:ty, dataptr, serialize) => {
        $crate::__impl_altrep_base_with_serialize!($ty);
        $crate::__impl_altvec_dataptr!($ty, i32);
        $crate::__impl_altinteger_methods!($ty);
        $crate::impl_inferbase_integer!($ty);
    };
    ($ty:ty, serialize, dataptr) => {
        $crate::impl_altinteger_from_data!($ty, dataptr, serialize);
    };
    ($ty:ty, subset, serialize) => {
        $crate::__impl_altrep_base_with_serialize!($ty);
        $crate::__impl_altvec_extract_subset!($ty);
        $crate::__impl_altinteger_methods!($ty);
        $crate::impl_inferbase_integer!($ty);
    };
    ($ty:ty, serialize, subset) => {
        $crate::impl_altinteger_from_data!($ty, subset, serialize);
    };
}

/// Internal macro: impl Altrep with just length
#[macro_export]
#[doc(hidden)]
macro_rules! __impl_altrep_base {
    ($ty:ty) => {
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::Altrep for $ty {
            fn length(x: $crate::ffi::SEXP) -> $crate::ffi::R_xlen_t {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltrepLen>::len(&*d) as $crate::ffi::R_xlen_t)
                    .unwrap_or(0)
            }
        }
    };
}

/// Internal macro: impl Altrep with length + serialization
///
/// Note: This only implements `serialized_state`. The `unserialize` method must be
/// provided by the wrapper class (generated by proc-macro) since it needs to create
/// a new ALTREP instance using the class-specific `into_altrep` method.
#[macro_export]
#[doc(hidden)]
macro_rules! __impl_altrep_base_with_serialize {
    ($ty:ty) => {
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::Altrep for $ty {
            fn length(x: $crate::ffi::SEXP) -> $crate::ffi::R_xlen_t {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltrepLen>::len(&*d) as $crate::ffi::R_xlen_t)
                    .unwrap_or(0)
            }

            const HAS_SERIALIZED_STATE: bool = true;

            fn serialized_state(x: $crate::ffi::SEXP) -> $crate::ffi::SEXP {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltrepSerialize>::serialized_state(&*d))
                    .unwrap_or(unsafe { $crate::ffi::R_NilValue })
            }

            // Note: HAS_UNSERIALIZE is left as default (false) here.
            // The wrapper class (via proc-macro) will register its own unserialize
            // callback that knows how to call into_altrep.
        }
    };
}

/// Internal macro: impl AltVec with dataptr support
#[macro_export]
#[doc(hidden)]
macro_rules! __impl_altvec_dataptr {
    ($ty:ty, $elem:ty) => {
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::AltVec for $ty {
            const HAS_DATAPTR: bool = true;

            fn dataptr(x: $crate::ffi::SEXP, writable: bool) -> *mut core::ffi::c_void {
                unsafe { $crate::altrep_data1_mut::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltrepDataptr<$elem>>::dataptr(d, writable))
                    .map(|p| p as *mut core::ffi::c_void)
                    .unwrap_or(core::ptr::null_mut())
            }

            const HAS_DATAPTR_OR_NULL: bool = true;

            fn dataptr_or_null(x: $crate::ffi::SEXP) -> *const core::ffi::c_void {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltrepDataptr<$elem>>::dataptr_or_null(&*d))
                    .map(|p| p as *const core::ffi::c_void)
                    .unwrap_or(core::ptr::null())
            }
        }
    };
}

/// Internal macro: impl AltVec with extract_subset support
#[macro_export]
#[doc(hidden)]
macro_rules! __impl_altvec_extract_subset {
    ($ty:ty) => {
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::AltVec for $ty {
            const HAS_EXTRACT_SUBSET: bool = true;

            fn extract_subset(
                x: $crate::ffi::SEXP,
                indx: $crate::ffi::SEXP,
                _call: $crate::ffi::SEXP,
            ) -> $crate::ffi::SEXP {
                // Convert indx SEXP to slice
                let len = unsafe { $crate::ffi::Rf_xlength(indx) } as usize;
                let indices = unsafe {
                    std::slice::from_raw_parts($crate::ffi::INTEGER(indx), len)
                };

                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltrepExtractSubset>::extract_subset(&*d, indices))
                    .unwrap_or(unsafe { $crate::ffi::R_NilValue })
            }
        }
    };
}

/// Internal macro for AltInteger method implementations.
#[macro_export]
#[doc(hidden)]
macro_rules! __impl_altinteger_methods {
    ($ty:ty) => {

        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::AltInteger for $ty {
            const HAS_ELT: bool = true;

            fn elt(x: $crate::ffi::SEXP, i: $crate::ffi::R_xlen_t) -> i32 {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltIntegerData>::elt(&*d, i as usize))
                    .unwrap_or(i32::MIN)
            }

            const HAS_GET_REGION: bool = true;

            fn get_region(
                x: $crate::ffi::SEXP,
                start: $crate::ffi::R_xlen_t,
                len: $crate::ffi::R_xlen_t,
                buf: *mut i32,
            ) -> $crate::ffi::R_xlen_t {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| {
                        let slice = unsafe { std::slice::from_raw_parts_mut(buf, len as usize) };
                        <$ty as $crate::altrep_data::AltIntegerData>::get_region(
                            &*d,
                            start as usize,
                            len as usize,
                            slice,
                        ) as $crate::ffi::R_xlen_t
                    })
                    .unwrap_or(0)
            }

            const HAS_IS_SORTED: bool = true;

            fn is_sorted(x: $crate::ffi::SEXP) -> i32 {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltIntegerData>::is_sorted(&*d))
                    .map(|s| s.to_r_int())
                    .unwrap_or(i32::MIN)
            }

            const HAS_NO_NA: bool = true;

            fn no_na(x: $crate::ffi::SEXP) -> i32 {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltIntegerData>::no_na(&*d))
                    .map(|b| if b { 1 } else { 0 })
                    .unwrap_or(0)
            }

            const HAS_SUM: bool = true;

            fn sum(x: $crate::ffi::SEXP, narm: bool) -> $crate::ffi::SEXP {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltIntegerData>::sum(&*d, narm))
                    .map(|s| {
                        if s >= i32::MIN as i64 && s <= i32::MAX as i64 {
                            unsafe { $crate::ffi::Rf_ScalarInteger(s as i32) }
                        } else {
                            unsafe { $crate::ffi::Rf_ScalarReal(s as f64) }
                        }
                    })
                    .unwrap_or(unsafe { $crate::ffi::R_NilValue })
            }

            const HAS_MIN: bool = true;

            fn min(x: $crate::ffi::SEXP, narm: bool) -> $crate::ffi::SEXP {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltIntegerData>::min(&*d, narm))
                    .map(|m| unsafe { $crate::ffi::Rf_ScalarInteger(m) })
                    .unwrap_or(unsafe { $crate::ffi::R_NilValue })
            }

            const HAS_MAX: bool = true;

            fn max(x: $crate::ffi::SEXP, narm: bool) -> $crate::ffi::SEXP {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltIntegerData>::max(&*d, narm))
                    .map(|m| unsafe { $crate::ffi::Rf_ScalarInteger(m) })
                    .unwrap_or(unsafe { $crate::ffi::R_NilValue })
            }
        }
    };
}

/// Generate ALTREP trait implementations for a type that implements AltRealData.
///
/// ## Variants
///
/// ```ignore
/// // Basic (no dataptr, no serialization):
/// impl_altreal_from_data!(MyType);
///
/// // With dataptr (type must implement AltrepDataptr<f64>):
/// impl_altreal_from_data!(MyType, dataptr);
///
/// // With serialization (type must implement AltrepSerialize):
/// impl_altreal_from_data!(MyType, serialize);
///
/// // With both dataptr and serialization:
/// impl_altreal_from_data!(MyType, dataptr, serialize);
/// ```
#[macro_export]
macro_rules! impl_altreal_from_data {
    ($ty:ty) => {
        $crate::__impl_altrep_base!($ty);
        impl $crate::altrep_traits::AltVec for $ty {}
        $crate::__impl_altreal_methods!($ty);
        $crate::impl_inferbase_real!($ty);
    };
    ($ty:ty, dataptr) => {
        $crate::__impl_altrep_base!($ty);
        $crate::__impl_altvec_dataptr!($ty, f64);
        $crate::__impl_altreal_methods!($ty);
        $crate::impl_inferbase_real!($ty);
    };
    ($ty:ty, serialize) => {
        $crate::__impl_altrep_base_with_serialize!($ty);
        impl $crate::altrep_traits::AltVec for $ty {}
        $crate::__impl_altreal_methods!($ty);
        $crate::impl_inferbase_real!($ty);
    };
    ($ty:ty, dataptr, serialize) => {
        $crate::__impl_altrep_base_with_serialize!($ty);
        $crate::__impl_altvec_dataptr!($ty, f64);
        $crate::__impl_altreal_methods!($ty);
        $crate::impl_inferbase_real!($ty);
    };
    ($ty:ty, serialize, dataptr) => {
        $crate::impl_altreal_from_data!($ty, dataptr, serialize);
    };
}

/// Internal macro for AltReal method implementations.
#[macro_export]
#[doc(hidden)]
macro_rules! __impl_altreal_methods {
    ($ty:ty) => {
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::AltReal for $ty {
            const HAS_ELT: bool = true;

            fn elt(x: $crate::ffi::SEXP, i: $crate::ffi::R_xlen_t) -> f64 {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltRealData>::elt(&*d, i as usize))
                    .unwrap_or(f64::NAN)
            }

            const HAS_GET_REGION: bool = true;

            fn get_region(
                x: $crate::ffi::SEXP,
                start: $crate::ffi::R_xlen_t,
                len: $crate::ffi::R_xlen_t,
                buf: *mut f64,
            ) -> $crate::ffi::R_xlen_t {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| {
                        let slice = unsafe { std::slice::from_raw_parts_mut(buf, len as usize) };
                        <$ty as $crate::altrep_data::AltRealData>::get_region(
                            &*d,
                            start as usize,
                            len as usize,
                            slice,
                        ) as $crate::ffi::R_xlen_t
                    })
                    .unwrap_or(0)
            }

            const HAS_IS_SORTED: bool = true;

            fn is_sorted(x: $crate::ffi::SEXP) -> i32 {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltRealData>::is_sorted(&*d))
                    .map(|s| s.to_r_int())
                    .unwrap_or(i32::MIN)
            }

            const HAS_NO_NA: bool = true;

            fn no_na(x: $crate::ffi::SEXP) -> i32 {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltRealData>::no_na(&*d))
                    .map(|b| if b { 1 } else { 0 })
                    .unwrap_or(0)
            }

            const HAS_SUM: bool = true;

            fn sum(x: $crate::ffi::SEXP, narm: bool) -> $crate::ffi::SEXP {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltRealData>::sum(&*d, narm))
                    .map(|s| unsafe { $crate::ffi::Rf_ScalarReal(s) })
                    .unwrap_or(unsafe { $crate::ffi::R_NilValue })
            }

            const HAS_MIN: bool = true;

            fn min(x: $crate::ffi::SEXP, narm: bool) -> $crate::ffi::SEXP {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltRealData>::min(&*d, narm))
                    .map(|m| unsafe { $crate::ffi::Rf_ScalarReal(m) })
                    .unwrap_or(unsafe { $crate::ffi::R_NilValue })
            }

            const HAS_MAX: bool = true;

            fn max(x: $crate::ffi::SEXP, narm: bool) -> $crate::ffi::SEXP {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltRealData>::max(&*d, narm))
                    .map(|m| unsafe { $crate::ffi::Rf_ScalarReal(m) })
                    .unwrap_or(unsafe { $crate::ffi::R_NilValue })
            }
        }
    };
}

/// Generate ALTREP trait implementations for a type that implements AltLogicalData.
#[macro_export]
macro_rules! impl_altlogical_from_data {
    ($ty:ty) => {
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::Altrep for $ty {
            fn length(x: $crate::ffi::SEXP) -> $crate::ffi::R_xlen_t {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltrepLen>::len(&*d) as $crate::ffi::R_xlen_t)
                    .unwrap_or(0)
            }
        }

        impl $crate::altrep_traits::AltVec for $ty {}

        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::AltLogical for $ty {
            const HAS_ELT: bool = true;

            fn elt(x: $crate::ffi::SEXP, i: $crate::ffi::R_xlen_t) -> i32 {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltLogicalData>::elt(&*d, i as usize).to_r_int())
                    .unwrap_or(i32::MIN)
            }

            const HAS_GET_REGION: bool = true;

            fn get_region(
                x: $crate::ffi::SEXP,
                start: $crate::ffi::R_xlen_t,
                len: $crate::ffi::R_xlen_t,
                buf: *mut i32,
            ) -> $crate::ffi::R_xlen_t {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| {
                        let slice = unsafe { std::slice::from_raw_parts_mut(buf, len as usize) };
                        <$ty as $crate::altrep_data::AltLogicalData>::get_region(
                            &*d,
                            start as usize,
                            len as usize,
                            slice,
                        ) as $crate::ffi::R_xlen_t
                    })
                    .unwrap_or(0)
            }

            const HAS_IS_SORTED: bool = true;

            fn is_sorted(x: $crate::ffi::SEXP) -> i32 {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltLogicalData>::is_sorted(&*d))
                    .map(|s| s.to_r_int())
                    .unwrap_or(i32::MIN)
            }

            const HAS_NO_NA: bool = true;

            fn no_na(x: $crate::ffi::SEXP) -> i32 {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltLogicalData>::no_na(&*d))
                    .map(|b| if b { 1 } else { 0 })
                    .unwrap_or(0)
            }

            const HAS_SUM: bool = true;

            fn sum(x: $crate::ffi::SEXP, narm: bool) -> $crate::ffi::SEXP {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltLogicalData>::sum(&*d, narm))
                    .map(|s| {
                        if s >= i32::MIN as i64 && s <= i32::MAX as i64 {
                            unsafe { $crate::ffi::Rf_ScalarInteger(s as i32) }
                        } else {
                            unsafe { $crate::ffi::Rf_ScalarReal(s as f64) }
                        }
                    })
                    .unwrap_or(unsafe { $crate::ffi::R_NilValue })
            }
        }

        $crate::impl_inferbase_logical!($ty);
    };
}

/// Generate ALTREP trait implementations for a type that implements AltRawData.
#[macro_export]
macro_rules! impl_altraw_from_data {
    ($ty:ty) => {
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::Altrep for $ty {
            fn length(x: $crate::ffi::SEXP) -> $crate::ffi::R_xlen_t {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltrepLen>::len(&*d) as $crate::ffi::R_xlen_t)
                    .unwrap_or(0)
            }
        }

        impl $crate::altrep_traits::AltVec for $ty {}

        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::AltRaw for $ty {
            const HAS_ELT: bool = true;

            fn elt(x: $crate::ffi::SEXP, i: $crate::ffi::R_xlen_t) -> u8 {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltRawData>::elt(&*d, i as usize))
                    .unwrap_or(0)
            }

            const HAS_GET_REGION: bool = true;

            fn get_region(
                x: $crate::ffi::SEXP,
                start: $crate::ffi::R_xlen_t,
                len: $crate::ffi::R_xlen_t,
                buf: *mut u8,
            ) -> $crate::ffi::R_xlen_t {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| {
                        let slice = unsafe { std::slice::from_raw_parts_mut(buf, len as usize) };
                        <$ty as $crate::altrep_data::AltRawData>::get_region(
                            &*d,
                            start as usize,
                            len as usize,
                            slice,
                        ) as $crate::ffi::R_xlen_t
                    })
                    .unwrap_or(0)
            }
        }

        $crate::impl_inferbase_raw!($ty);
    };
}

/// Generate ALTREP trait implementations for a type that implements AltStringData.
#[macro_export]
macro_rules! impl_altstring_from_data {
    ($ty:ty) => {
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::Altrep for $ty {
            fn length(x: $crate::ffi::SEXP) -> $crate::ffi::R_xlen_t {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltrepLen>::len(&*d) as $crate::ffi::R_xlen_t)
                    .unwrap_or(0)
            }
        }

        impl $crate::altrep_traits::AltVec for $ty {}

        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::AltString for $ty {
            fn elt(x: $crate::ffi::SEXP, i: $crate::ffi::R_xlen_t) -> $crate::ffi::SEXP {
                // Keep ExternalPtr alive while we use the string reference
                match unsafe { $crate::altrep_data1_as::<$ty>(x) } {
                    Some(d) => {
                        match <$ty as $crate::altrep_data::AltStringData>::elt(&*d, i as usize) {
                            Some(s) => unsafe {
                                $crate::ffi::Rf_mkCharLenCE(
                                    s.as_ptr().cast(),
                                    s.len() as i32,
                                    $crate::ffi::cetype_t::CE_UTF8,
                                )
                            },
                            None => unsafe { $crate::ffi::R_NaString },
                        }
                    }
                    None => unsafe { $crate::ffi::R_NaString },
                }
            }

            const HAS_IS_SORTED: bool = true;

            fn is_sorted(x: $crate::ffi::SEXP) -> i32 {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltStringData>::is_sorted(&*d))
                    .map(|s| s.to_r_int())
                    .unwrap_or(i32::MIN)
            }

            const HAS_NO_NA: bool = true;

            fn no_na(x: $crate::ffi::SEXP) -> i32 {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .and_then(|d| <$ty as $crate::altrep_data::AltStringData>::no_na(&*d))
                    .map(|b| if b { 1 } else { 0 })
                    .unwrap_or(0)
            }
        }

        $crate::impl_inferbase_string!($ty);
    };
}

/// Generate ALTREP trait implementations for a type that implements AltListData.
#[macro_export]
macro_rules! impl_altlist_from_data {
    ($ty:ty) => {
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::Altrep for $ty {
            fn length(x: $crate::ffi::SEXP) -> $crate::ffi::R_xlen_t {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltrepLen>::len(&*d) as $crate::ffi::R_xlen_t)
                    .unwrap_or(0)
            }
        }

        impl $crate::altrep_traits::AltVec for $ty {}

        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::AltList for $ty {
            fn elt(x: $crate::ffi::SEXP, i: $crate::ffi::R_xlen_t) -> $crate::ffi::SEXP {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltListData>::elt(&*d, i as usize))
                    .unwrap_or(unsafe { $crate::ffi::R_NilValue })
            }
        }

        $crate::impl_inferbase_list!($ty);
    };
}

/// Generate ALTREP trait implementations for a type that implements AltComplexData.
#[macro_export]
macro_rules! impl_altcomplex_from_data {
    ($ty:ty) => {
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::Altrep for $ty {
            fn length(x: $crate::ffi::SEXP) -> $crate::ffi::R_xlen_t {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltrepLen>::len(&*d) as $crate::ffi::R_xlen_t)
                    .unwrap_or(0)
            }
        }

        impl $crate::altrep_traits::AltVec for $ty {}

        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        impl $crate::altrep_traits::AltComplex for $ty {
            const HAS_ELT: bool = true;

            fn elt(x: $crate::ffi::SEXP, i: $crate::ffi::R_xlen_t) -> $crate::ffi::Rcomplex {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| <$ty as $crate::altrep_data::AltComplexData>::elt(&*d, i as usize))
                    .unwrap_or($crate::ffi::Rcomplex { r: f64::NAN, i: f64::NAN })
            }

            const HAS_GET_REGION: bool = true;

            fn get_region(
                x: $crate::ffi::SEXP,
                start: $crate::ffi::R_xlen_t,
                len: $crate::ffi::R_xlen_t,
                buf: *mut $crate::ffi::Rcomplex,
            ) -> $crate::ffi::R_xlen_t {
                unsafe { $crate::altrep_data1_as::<$ty>(x) }
                    .map(|d| {
                        let slice = unsafe { std::slice::from_raw_parts_mut(buf, len as usize) };
                        <$ty as $crate::altrep_data::AltComplexData>::get_region(
                            &*d,
                            start as usize,
                            len as usize,
                            slice,
                        ) as $crate::ffi::R_xlen_t
                    })
                    .unwrap_or(0)
            }
        }

        $crate::impl_inferbase_complex!($ty);
    };
}

// =============================================================================
// Built-in implementations for standard types
// =============================================================================
// These implementations are provided here to satisfy the orphan rules.
// User crates can use these types directly with delegate_data.

// Integer types - Vec<i32> supports dataptr, ranges don't (computed on demand)
impl_altinteger_from_data!(Vec<i32>, dataptr);
impl_altinteger_from_data!(std::ops::Range<i32>);
impl_altinteger_from_data!(std::ops::Range<i64>);

// Real types - Vec<f64> supports dataptr, ranges don't
impl_altreal_from_data!(Vec<f64>, dataptr);
impl_altreal_from_data!(std::ops::Range<f64>);

// Logical types
impl_altlogical_from_data!(Vec<bool>);

// Raw types
impl_altraw_from_data!(Vec<u8>);

// String types
impl_altstring_from_data!(Vec<String>);

// NOTE: Box<[T]> (owned slices) cannot be used directly with ALTREP because
// slices are DSTs (dynamically sized types) and ExternalPtr requires Sized.
// Users should use Vec<T> instead, which is semantically equivalent.
// The data trait impls in altrep_data.rs are still available for custom wrappers.

// =============================================================================
// Array implementations (const generics - can't use macros)
// =============================================================================

// Integer arrays
impl<const N: usize> crate::altrep_traits::Altrep for [i32; N] {
    fn length(x: crate::ffi::SEXP) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<[i32; N]>(x) }
            .map(|d| crate::altrep_data::AltrepLen::len(&*d) as crate::ffi::R_xlen_t)
            .unwrap_or(0)
    }
}

impl<const N: usize> crate::altrep_traits::AltVec for [i32; N] {
    const HAS_DATAPTR: bool = true;

    fn dataptr(x: crate::ffi::SEXP, _writable: bool) -> *mut std::ffi::c_void {
        unsafe { crate::altrep_data1_as::<[i32; N]>(x) }
            .and_then(|d| {
                <[i32; N] as crate::altrep_data::AltIntegerData>::as_slice(&*d)
                    .map(|s| s.as_ptr() as *mut std::ffi::c_void)
            })
            .unwrap_or(std::ptr::null_mut())
    }
}

impl<const N: usize> crate::altrep_traits::AltInteger for [i32; N] {
    const HAS_ELT: bool = true;

    fn elt(x: crate::ffi::SEXP, i: crate::ffi::R_xlen_t) -> i32 {
        unsafe { crate::altrep_data1_as::<[i32; N]>(x) }
            .map(|d| <[i32; N] as crate::altrep_data::AltIntegerData>::elt(&*d, i as usize))
            .unwrap_or(i32::MIN)
    }

    const HAS_GET_REGION: bool = true;

    fn get_region(
        x: crate::ffi::SEXP,
        start: crate::ffi::R_xlen_t,
        len: crate::ffi::R_xlen_t,
        buf: *mut i32,
    ) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<[i32; N]>(x) }
            .map(|d| {
                let slice = unsafe { std::slice::from_raw_parts_mut(buf, len as usize) };
                <[i32; N] as crate::altrep_data::AltIntegerData>::get_region(
                    &*d,
                    start as usize,
                    len as usize,
                    slice,
                ) as crate::ffi::R_xlen_t
            })
            .unwrap_or(0)
    }

    const HAS_NO_NA: bool = true;

    fn no_na(x: crate::ffi::SEXP) -> i32 {
        unsafe { crate::altrep_data1_as::<[i32; N]>(x) }
            .and_then(|d| <[i32; N] as crate::altrep_data::AltIntegerData>::no_na(&*d))
            .map(|b| if b { 1 } else { 0 })
            .unwrap_or(0)
    }
}

// Real arrays
impl<const N: usize> crate::altrep_traits::Altrep for [f64; N] {
    fn length(x: crate::ffi::SEXP) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<[f64; N]>(x) }
            .map(|d| crate::altrep_data::AltrepLen::len(&*d) as crate::ffi::R_xlen_t)
            .unwrap_or(0)
    }
}

impl<const N: usize> crate::altrep_traits::AltVec for [f64; N] {
    const HAS_DATAPTR: bool = true;

    fn dataptr(x: crate::ffi::SEXP, _writable: bool) -> *mut std::ffi::c_void {
        unsafe { crate::altrep_data1_as::<[f64; N]>(x) }
            .and_then(|d| {
                <[f64; N] as crate::altrep_data::AltRealData>::as_slice(&*d)
                    .map(|s| s.as_ptr() as *mut std::ffi::c_void)
            })
            .unwrap_or(std::ptr::null_mut())
    }
}

impl<const N: usize> crate::altrep_traits::AltReal for [f64; N] {
    const HAS_ELT: bool = true;

    fn elt(x: crate::ffi::SEXP, i: crate::ffi::R_xlen_t) -> f64 {
        unsafe { crate::altrep_data1_as::<[f64; N]>(x) }
            .map(|d| <[f64; N] as crate::altrep_data::AltRealData>::elt(&*d, i as usize))
            .unwrap_or(f64::NAN)
    }

    const HAS_GET_REGION: bool = true;

    fn get_region(
        x: crate::ffi::SEXP,
        start: crate::ffi::R_xlen_t,
        len: crate::ffi::R_xlen_t,
        buf: *mut f64,
    ) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<[f64; N]>(x) }
            .map(|d| {
                let slice = unsafe { std::slice::from_raw_parts_mut(buf, len as usize) };
                <[f64; N] as crate::altrep_data::AltRealData>::get_region(
                    &*d,
                    start as usize,
                    len as usize,
                    slice,
                ) as crate::ffi::R_xlen_t
            })
            .unwrap_or(0)
    }

    const HAS_NO_NA: bool = true;

    fn no_na(x: crate::ffi::SEXP) -> i32 {
        unsafe { crate::altrep_data1_as::<[f64; N]>(x) }
            .and_then(|d| <[f64; N] as crate::altrep_data::AltRealData>::no_na(&*d))
            .map(|b| if b { 1 } else { 0 })
            .unwrap_or(0)
    }
}

// Logical arrays
impl<const N: usize> crate::altrep_traits::Altrep for [bool; N] {
    fn length(x: crate::ffi::SEXP) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<[bool; N]>(x) }
            .map(|d| crate::altrep_data::AltrepLen::len(&*d) as crate::ffi::R_xlen_t)
            .unwrap_or(0)
    }
}

impl<const N: usize> crate::altrep_traits::AltVec for [bool; N] {}

impl<const N: usize> crate::altrep_traits::AltLogical for [bool; N] {
    const HAS_ELT: bool = true;

    fn elt(x: crate::ffi::SEXP, i: crate::ffi::R_xlen_t) -> i32 {
        unsafe { crate::altrep_data1_as::<[bool; N]>(x) }
            .map(|d| {
                <[bool; N] as crate::altrep_data::AltLogicalData>::elt(&*d, i as usize).to_r_int()
            })
            .unwrap_or(crate::altrep_traits::NA_LOGICAL)
    }

    const HAS_NO_NA: bool = true;

    fn no_na(x: crate::ffi::SEXP) -> i32 {
        unsafe { crate::altrep_data1_as::<[bool; N]>(x) }
            .and_then(|d| <[bool; N] as crate::altrep_data::AltLogicalData>::no_na(&*d))
            .map(|b| if b { 1 } else { 0 })
            .unwrap_or(0)
    }
}

// Raw arrays
impl<const N: usize> crate::altrep_traits::Altrep for [u8; N] {
    fn length(x: crate::ffi::SEXP) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<[u8; N]>(x) }
            .map(|d| crate::altrep_data::AltrepLen::len(&*d) as crate::ffi::R_xlen_t)
            .unwrap_or(0)
    }
}

impl<const N: usize> crate::altrep_traits::AltVec for [u8; N] {
    const HAS_DATAPTR: bool = true;

    fn dataptr(x: crate::ffi::SEXP, _writable: bool) -> *mut std::ffi::c_void {
        unsafe { crate::altrep_data1_as::<[u8; N]>(x) }
            .and_then(|d| {
                <[u8; N] as crate::altrep_data::AltRawData>::as_slice(&*d)
                    .map(|s| s.as_ptr() as *mut std::ffi::c_void)
            })
            .unwrap_or(std::ptr::null_mut())
    }
}

impl<const N: usize> crate::altrep_traits::AltRaw for [u8; N] {
    const HAS_ELT: bool = true;

    fn elt(x: crate::ffi::SEXP, i: crate::ffi::R_xlen_t) -> crate::ffi::Rbyte {
        unsafe { crate::altrep_data1_as::<[u8; N]>(x) }
            .map(|d| <[u8; N] as crate::altrep_data::AltRawData>::elt(&*d, i as usize))
            .unwrap_or(0)
    }

    const HAS_GET_REGION: bool = true;

    fn get_region(
        x: crate::ffi::SEXP,
        start: crate::ffi::R_xlen_t,
        len: crate::ffi::R_xlen_t,
        buf: *mut crate::ffi::Rbyte,
    ) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<[u8; N]>(x) }
            .map(|d| {
                let slice = unsafe { std::slice::from_raw_parts_mut(buf, len as usize) };
                <[u8; N] as crate::altrep_data::AltRawData>::get_region(
                    &*d,
                    start as usize,
                    len as usize,
                    slice,
                ) as crate::ffi::R_xlen_t
            })
            .unwrap_or(0)
    }
}

// String arrays
impl<const N: usize> crate::altrep_traits::Altrep for [String; N] {
    fn length(x: crate::ffi::SEXP) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<[String; N]>(x) }
            .map(|d| crate::altrep_data::AltrepLen::len(&*d) as crate::ffi::R_xlen_t)
            .unwrap_or(0)
    }
}

impl<const N: usize> crate::altrep_traits::AltVec for [String; N] {}

impl<const N: usize> crate::altrep_traits::AltString for [String; N] {
    fn elt(x: crate::ffi::SEXP, i: crate::ffi::R_xlen_t) -> crate::ffi::SEXP {
        match unsafe { crate::altrep_data1_as::<[String; N]>(x) } {
            Some(d) => {
                match <[String; N] as crate::altrep_data::AltStringData>::elt(&*d, i as usize) {
                    Some(s) => unsafe {
                        crate::ffi::Rf_mkCharLenCE(
                            s.as_ptr().cast(),
                            s.len() as i32,
                            crate::ffi::cetype_t::CE_UTF8,
                        )
                    },
                    None => unsafe { crate::ffi::R_NaString },
                }
            }
            None => unsafe { crate::ffi::R_NaString },
        }
    }
}

// =============================================================================
// Static slice implementations (&'static [T])
// =============================================================================
//
// `&'static [T]` is Sized (fat pointer: ptr + len) and satisfies 'static,
// so it can be used DIRECTLY with ALTREP via ExternalPtr.
//
// Use cases:
// - Const arrays: `static DATA: [i32; 5] = [1, 2, 3, 4, 5]; create_altrep(&DATA[..])`
// - Leaked data: `let s: &'static [i32] = Box::leak(vec.into_boxed_slice());`
// - Memory-mapped files with 'static lifetime

// Integer static slices
impl crate::altrep_traits::Altrep for &'static [i32] {
    fn length(x: crate::ffi::SEXP) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<&'static [i32]>(x) }
            .map(|d| crate::altrep_data::AltrepLen::len(&*d) as crate::ffi::R_xlen_t)
            .unwrap_or(0)
    }
}

impl crate::altrep_traits::AltVec for &'static [i32] {
    const HAS_DATAPTR: bool = true;

    fn dataptr(x: crate::ffi::SEXP, _writable: bool) -> *mut std::ffi::c_void {
        // Note: Returns pointer to static data. This is safe for read-only access.
        // R may request writable=true but static data cannot be modified.
        unsafe { crate::altrep_data1_as::<&'static [i32]>(x) }
            .map(|d| d.as_ptr() as *mut std::ffi::c_void)
            .unwrap_or(std::ptr::null_mut())
    }

    const HAS_DATAPTR_OR_NULL: bool = true;

    fn dataptr_or_null(x: crate::ffi::SEXP) -> *const std::ffi::c_void {
        unsafe { crate::altrep_data1_as::<&'static [i32]>(x) }
            .map(|d| d.as_ptr() as *const std::ffi::c_void)
            .unwrap_or(std::ptr::null())
    }
}

impl crate::altrep_traits::AltInteger for &'static [i32] {
    const HAS_ELT: bool = true;

    fn elt(x: crate::ffi::SEXP, i: crate::ffi::R_xlen_t) -> i32 {
        unsafe { crate::altrep_data1_as::<&'static [i32]>(x) }
            .map(|d| crate::altrep_data::AltIntegerData::elt(&*d, i as usize))
            .unwrap_or(i32::MIN)
    }

    const HAS_GET_REGION: bool = true;

    fn get_region(
        x: crate::ffi::SEXP,
        start: crate::ffi::R_xlen_t,
        len: crate::ffi::R_xlen_t,
        buf: *mut i32,
    ) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<&'static [i32]>(x) }
            .map(|d| {
                let slice = unsafe { std::slice::from_raw_parts_mut(buf, len as usize) };
                crate::altrep_data::AltIntegerData::get_region(&*d, start as usize, len as usize, slice)
                    as crate::ffi::R_xlen_t
            })
            .unwrap_or(0)
    }

    const HAS_NO_NA: bool = true;

    fn no_na(x: crate::ffi::SEXP) -> i32 {
        unsafe { crate::altrep_data1_as::<&'static [i32]>(x) }
            .and_then(|d| crate::altrep_data::AltIntegerData::no_na(&*d))
            .map(|b| if b { 1 } else { 0 })
            .unwrap_or(0)
    }

    const HAS_SUM: bool = true;

    fn sum(x: crate::ffi::SEXP, narm: bool) -> crate::ffi::SEXP {
        unsafe { crate::altrep_data1_as::<&'static [i32]>(x) }
            .and_then(|d| crate::altrep_data::AltIntegerData::sum(&*d, narm))
            .map(|s| {
                if s >= i32::MIN as i64 && s <= i32::MAX as i64 {
                    unsafe { crate::ffi::Rf_ScalarInteger(s as i32) }
                } else {
                    unsafe { crate::ffi::Rf_ScalarReal(s as f64) }
                }
            })
            .unwrap_or(unsafe { crate::ffi::R_NilValue })
    }

    const HAS_MIN: bool = true;

    fn min(x: crate::ffi::SEXP, narm: bool) -> crate::ffi::SEXP {
        unsafe { crate::altrep_data1_as::<&'static [i32]>(x) }
            .and_then(|d| crate::altrep_data::AltIntegerData::min(&*d, narm))
            .map(|m| unsafe { crate::ffi::Rf_ScalarInteger(m) })
            .unwrap_or(unsafe { crate::ffi::R_NilValue })
    }

    const HAS_MAX: bool = true;

    fn max(x: crate::ffi::SEXP, narm: bool) -> crate::ffi::SEXP {
        unsafe { crate::altrep_data1_as::<&'static [i32]>(x) }
            .and_then(|d| crate::altrep_data::AltIntegerData::max(&*d, narm))
            .map(|m| unsafe { crate::ffi::Rf_ScalarInteger(m) })
            .unwrap_or(unsafe { crate::ffi::R_NilValue })
    }
}

crate::impl_inferbase_integer!(&'static [i32]);

// Real static slices
impl crate::altrep_traits::Altrep for &'static [f64] {
    fn length(x: crate::ffi::SEXP) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<&'static [f64]>(x) }
            .map(|d| crate::altrep_data::AltrepLen::len(&*d) as crate::ffi::R_xlen_t)
            .unwrap_or(0)
    }
}

impl crate::altrep_traits::AltVec for &'static [f64] {
    const HAS_DATAPTR: bool = true;

    fn dataptr(x: crate::ffi::SEXP, _writable: bool) -> *mut std::ffi::c_void {
        unsafe { crate::altrep_data1_as::<&'static [f64]>(x) }
            .map(|d| d.as_ptr() as *mut std::ffi::c_void)
            .unwrap_or(std::ptr::null_mut())
    }

    const HAS_DATAPTR_OR_NULL: bool = true;

    fn dataptr_or_null(x: crate::ffi::SEXP) -> *const std::ffi::c_void {
        unsafe { crate::altrep_data1_as::<&'static [f64]>(x) }
            .map(|d| d.as_ptr() as *const std::ffi::c_void)
            .unwrap_or(std::ptr::null())
    }
}

impl crate::altrep_traits::AltReal for &'static [f64] {
    const HAS_ELT: bool = true;

    fn elt(x: crate::ffi::SEXP, i: crate::ffi::R_xlen_t) -> f64 {
        unsafe { crate::altrep_data1_as::<&'static [f64]>(x) }
            .map(|d| crate::altrep_data::AltRealData::elt(&*d, i as usize))
            .unwrap_or(f64::NAN)
    }

    const HAS_GET_REGION: bool = true;

    fn get_region(
        x: crate::ffi::SEXP,
        start: crate::ffi::R_xlen_t,
        len: crate::ffi::R_xlen_t,
        buf: *mut f64,
    ) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<&'static [f64]>(x) }
            .map(|d| {
                let slice = unsafe { std::slice::from_raw_parts_mut(buf, len as usize) };
                crate::altrep_data::AltRealData::get_region(&*d, start as usize, len as usize, slice)
                    as crate::ffi::R_xlen_t
            })
            .unwrap_or(0)
    }

    const HAS_NO_NA: bool = true;

    fn no_na(x: crate::ffi::SEXP) -> i32 {
        unsafe { crate::altrep_data1_as::<&'static [f64]>(x) }
            .and_then(|d| crate::altrep_data::AltRealData::no_na(&*d))
            .map(|b| if b { 1 } else { 0 })
            .unwrap_or(0)
    }

    const HAS_SUM: bool = true;

    fn sum(x: crate::ffi::SEXP, narm: bool) -> crate::ffi::SEXP {
        unsafe { crate::altrep_data1_as::<&'static [f64]>(x) }
            .and_then(|d| crate::altrep_data::AltRealData::sum(&*d, narm))
            .map(|s| unsafe { crate::ffi::Rf_ScalarReal(s) })
            .unwrap_or(unsafe { crate::ffi::R_NilValue })
    }

    const HAS_MIN: bool = true;

    fn min(x: crate::ffi::SEXP, narm: bool) -> crate::ffi::SEXP {
        unsafe { crate::altrep_data1_as::<&'static [f64]>(x) }
            .and_then(|d| crate::altrep_data::AltRealData::min(&*d, narm))
            .map(|m| unsafe { crate::ffi::Rf_ScalarReal(m) })
            .unwrap_or(unsafe { crate::ffi::R_NilValue })
    }

    const HAS_MAX: bool = true;

    fn max(x: crate::ffi::SEXP, narm: bool) -> crate::ffi::SEXP {
        unsafe { crate::altrep_data1_as::<&'static [f64]>(x) }
            .and_then(|d| crate::altrep_data::AltRealData::max(&*d, narm))
            .map(|m| unsafe { crate::ffi::Rf_ScalarReal(m) })
            .unwrap_or(unsafe { crate::ffi::R_NilValue })
    }
}

crate::impl_inferbase_real!(&'static [f64]);

// Logical static slices
impl crate::altrep_traits::Altrep for &'static [bool] {
    fn length(x: crate::ffi::SEXP) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<&'static [bool]>(x) }
            .map(|d| crate::altrep_data::AltrepLen::len(&*d) as crate::ffi::R_xlen_t)
            .unwrap_or(0)
    }
}

impl crate::altrep_traits::AltVec for &'static [bool] {}

impl crate::altrep_traits::AltLogical for &'static [bool] {
    const HAS_ELT: bool = true;

    fn elt(x: crate::ffi::SEXP, i: crate::ffi::R_xlen_t) -> i32 {
        unsafe { crate::altrep_data1_as::<&'static [bool]>(x) }
            .map(|d| crate::altrep_data::AltLogicalData::elt(&*d, i as usize).to_r_int())
            .unwrap_or(crate::altrep_traits::NA_LOGICAL)
    }

    const HAS_NO_NA: bool = true;

    fn no_na(x: crate::ffi::SEXP) -> i32 {
        unsafe { crate::altrep_data1_as::<&'static [bool]>(x) }
            .and_then(|d| crate::altrep_data::AltLogicalData::no_na(&*d))
            .map(|b| if b { 1 } else { 0 })
            .unwrap_or(0)
    }

    const HAS_SUM: bool = true;

    fn sum(x: crate::ffi::SEXP, narm: bool) -> crate::ffi::SEXP {
        unsafe { crate::altrep_data1_as::<&'static [bool]>(x) }
            .and_then(|d| crate::altrep_data::AltLogicalData::sum(&*d, narm))
            .map(|s| {
                if s >= i32::MIN as i64 && s <= i32::MAX as i64 {
                    unsafe { crate::ffi::Rf_ScalarInteger(s as i32) }
                } else {
                    unsafe { crate::ffi::Rf_ScalarReal(s as f64) }
                }
            })
            .unwrap_or(unsafe { crate::ffi::R_NilValue })
    }
}

crate::impl_inferbase_logical!(&'static [bool]);

// Raw static slices
impl crate::altrep_traits::Altrep for &'static [u8] {
    fn length(x: crate::ffi::SEXP) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<&'static [u8]>(x) }
            .map(|d| crate::altrep_data::AltrepLen::len(&*d) as crate::ffi::R_xlen_t)
            .unwrap_or(0)
    }
}

impl crate::altrep_traits::AltVec for &'static [u8] {
    const HAS_DATAPTR: bool = true;

    fn dataptr(x: crate::ffi::SEXP, _writable: bool) -> *mut std::ffi::c_void {
        unsafe { crate::altrep_data1_as::<&'static [u8]>(x) }
            .map(|d| d.as_ptr() as *mut std::ffi::c_void)
            .unwrap_or(std::ptr::null_mut())
    }

    const HAS_DATAPTR_OR_NULL: bool = true;

    fn dataptr_or_null(x: crate::ffi::SEXP) -> *const std::ffi::c_void {
        unsafe { crate::altrep_data1_as::<&'static [u8]>(x) }
            .map(|d| d.as_ptr() as *const std::ffi::c_void)
            .unwrap_or(std::ptr::null())
    }
}

impl crate::altrep_traits::AltRaw for &'static [u8] {
    const HAS_ELT: bool = true;

    fn elt(x: crate::ffi::SEXP, i: crate::ffi::R_xlen_t) -> crate::ffi::Rbyte {
        unsafe { crate::altrep_data1_as::<&'static [u8]>(x) }
            .map(|d| crate::altrep_data::AltRawData::elt(&*d, i as usize))
            .unwrap_or(0)
    }

    const HAS_GET_REGION: bool = true;

    fn get_region(
        x: crate::ffi::SEXP,
        start: crate::ffi::R_xlen_t,
        len: crate::ffi::R_xlen_t,
        buf: *mut crate::ffi::Rbyte,
    ) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<&'static [u8]>(x) }
            .map(|d| {
                let slice = unsafe { std::slice::from_raw_parts_mut(buf, len as usize) };
                crate::altrep_data::AltRawData::get_region(&*d, start as usize, len as usize, slice)
                    as crate::ffi::R_xlen_t
            })
            .unwrap_or(0)
    }
}

crate::impl_inferbase_raw!(&'static [u8]);

// String static slices (owned strings)
impl crate::altrep_traits::Altrep for &'static [String] {
    fn length(x: crate::ffi::SEXP) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<&'static [String]>(x) }
            .map(|d| crate::altrep_data::AltrepLen::len(&*d) as crate::ffi::R_xlen_t)
            .unwrap_or(0)
    }
}

impl crate::altrep_traits::AltVec for &'static [String] {}

impl crate::altrep_traits::AltString for &'static [String] {
    fn elt(x: crate::ffi::SEXP, i: crate::ffi::R_xlen_t) -> crate::ffi::SEXP {
        match unsafe { crate::altrep_data1_as::<&'static [String]>(x) } {
            Some(d) => {
                match crate::altrep_data::AltStringData::elt(&*d, i as usize) {
                    Some(s) => unsafe {
                        crate::ffi::Rf_mkCharLenCE(
                            s.as_ptr().cast(),
                            s.len() as i32,
                            crate::ffi::cetype_t::CE_UTF8,
                        )
                    },
                    None => unsafe { crate::ffi::R_NaString },
                }
            }
            None => unsafe { crate::ffi::R_NaString },
        }
    }

    const HAS_NO_NA: bool = true;

    fn no_na(x: crate::ffi::SEXP) -> i32 {
        unsafe { crate::altrep_data1_as::<&'static [String]>(x) }
            .and_then(|d| crate::altrep_data::AltStringData::no_na(&*d))
            .map(|b| if b { 1 } else { 0 })
            .unwrap_or(0)
    }
}

crate::impl_inferbase_string!(&'static [String]);

// String static slices (str references)
impl crate::altrep_traits::Altrep for &'static [&'static str] {
    fn length(x: crate::ffi::SEXP) -> crate::ffi::R_xlen_t {
        unsafe { crate::altrep_data1_as::<&'static [&'static str]>(x) }
            .map(|d| crate::altrep_data::AltrepLen::len(&*d) as crate::ffi::R_xlen_t)
            .unwrap_or(0)
    }
}

impl crate::altrep_traits::AltVec for &'static [&'static str] {}

impl crate::altrep_traits::AltString for &'static [&'static str] {
    fn elt(x: crate::ffi::SEXP, i: crate::ffi::R_xlen_t) -> crate::ffi::SEXP {
        match unsafe { crate::altrep_data1_as::<&'static [&'static str]>(x) } {
            Some(d) => {
                match crate::altrep_data::AltStringData::elt(&*d, i as usize) {
                    Some(s) => unsafe {
                        crate::ffi::Rf_mkCharLenCE(
                            s.as_ptr().cast(),
                            s.len() as i32,
                            crate::ffi::cetype_t::CE_UTF8,
                        )
                    },
                    None => unsafe { crate::ffi::R_NaString },
                }
            }
            None => unsafe { crate::ffi::R_NaString },
        }
    }

    const HAS_NO_NA: bool = true;

    fn no_na(x: crate::ffi::SEXP) -> i32 {
        unsafe { crate::altrep_data1_as::<&'static [&'static str]>(x) }
            .and_then(|d| crate::altrep_data::AltStringData::no_na(&*d))
            .map(|b| if b { 1 } else { 0 })
            .unwrap_or(0)
    }
}

crate::impl_inferbase_string!(&'static [&'static str]);
