//! Marker traits for proc-macro derived types.
//!
//! These marker traits identify types that have been derived with specific proc-macros.
//! They enable compile-time type checking and blanket implementations.
//!
//! # Pattern
//!
//! Each derive macro generates an impl of its corresponding marker trait:
//!
//! | Derive Macro | Marker Trait |
//! |--------------|--------------|
//! | `#[derive(DataFrameRow)]` | [`DataFrameRow`] |
//! | `#[derive(PreferList)]` | [`crate::markers::PrefersList`] |
//! | `#[derive(PreferExternalPtr)]` | [`crate::markers::PrefersExternalPtr`] |
//! | `#[derive(PreferRNativeType)]` | [`crate::markers::PrefersRNativeType`] |
//! | `#[derive(PreferDataFrame)]` | [`crate::markers::PrefersDataFrame`] |

/// Marker trait for types generated by `#[derive(DataFrameRow)]`.
///
/// Automatically implemented by the `DataFrameRow` derive macro. The derive
/// macro emits a compile-time assertion against this trait for every struct-typed
/// variant field, giving users a clear error when the inner type is missing the
/// derive.
///
/// This trait has no supertrait — the actual data-frame conversion contract is on the
/// generated companion `{Name}DataFrame` struct (which implements `IntoDataFrame`).
/// The marker is used solely for compile-time assertions via
/// `_assert_inner_is_dataframe_row::<T>()` generated by the outer derive.
///
/// You should not implement this trait manually.
#[diagnostic::on_unimplemented(
    message = "the trait `DataFrameRow` is not implemented for `{Self}`",
    label = "add `#[derive(DataFrameRow)]` to `{Self}`, annotate the field \
             with `#[dataframe(as_list)]` to keep it as an opaque list-column, \
             or annotate with `#[dataframe(as_factor)]` for unit-only enums",
    note = "struct- and enum-typed variant fields are flattened by default into prefixed \
            columns; the inner type must implement `DataFrameRow` for this to work"
)]
pub trait DataFrameRow {}

/// Reflection trait for `#[derive(DataFrameRow)]` types, used for compile-time
/// collision detection in outer `DataFrameRow` enums.
///
/// Automatically emitted by the `DataFrameRow` derive macro alongside `DataFrameRow`.
/// The outer enum's codegen generates a `const _: ()` assertion that calls
/// [`assert_no_payload_field_collision`] using these associated constants, producing
/// a clear compile error when an inner payload field name (after outer prefix expansion)
/// would produce the same R column as the outer discriminant column.
///
/// # Constants
///
/// - `FIELDS`: the resolved column names (after `#[dataframe(rename = "...")]`) that
///   this type contributes directly. For structs: each column name. For enums: every
///   payload field name across all variants (deduplicated).
/// - `TAG`: the value of `#[dataframe(tag = "...")]` on this type, or `""` if absent.
///   The outer macro uses this as the discriminant suffix for inner-enum nested fields.
///
/// You should not implement this trait manually.
pub trait DataFramePayloadFields {
    /// Resolved column names contributed by this type (post-rename, pre-prefix).
    const FIELDS: &'static [&'static str];
    /// Value of `#[dataframe(tag = "...")]` on this type, or `""` if absent.
    const TAG: &'static str;
}

// region: const-eval collision helper

/// Const-eval equality check for two `&str` values (stable since Rust 1.46).
///
/// Used by [`assert_no_payload_field_collision`] inside a `const {}` block.
const fn const_str_eq(a: &str, b: &str) -> bool {
    let a = a.as_bytes();
    let b = b.as_bytes();
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        if a[i] != b[i] {
            return false;
        }
        i += 1;
    }
    true
}

/// Compile-time assertion: no element of `fields` equals `discriminant_suffix`
/// (the inner-enum's `#[dataframe(tag)]` value).
///
/// Called from `const _: ()` blocks emitted by the outer `DataFrameRow` derive for
/// every `EnumResolvedField::Struct` nested-enum field:
///
/// ```rust,ignore
/// const _: () = ::miniextendr_api::markers::assert_no_payload_field_collision(
///     <Inner as ::miniextendr_api::markers::DataFramePayloadFields>::FIELDS,
///     <Inner as ::miniextendr_api::markers::DataFramePayloadFields>::TAG,
/// );
/// ```
///
/// `fields` contains the resolved column names the inner type emits directly (not prefixed).
/// `discriminant_suffix` is the inner enum's tag value (e.g. `"variant"`).
///
/// If any field name equals the discriminant suffix, the const evaluation panics with a
/// message explaining the collision and suggesting a rename.
pub const fn assert_no_payload_field_collision(fields: &[&str], discriminant_suffix: &str) {
    let mut i = 0;
    while i < fields.len() {
        if const_str_eq(fields[i], discriminant_suffix) {
            panic!(
                "DataFrameRow inner-payload field collision: an inner enum payload field \
                 has the same name as the inner enum's discriminant tag. After outer prefix \
                 expansion this produces two columns with identical names, causing silent \
                 data corruption. Rename the inner payload field or add \
                 `#[dataframe(rename = \"...\")]` on it to use a different column name."
            );
        }
        i += 1;
    }
}
// endregion

/// Marker trait for types that should be converted to R lists via `IntoR`.
///
/// Implemented by the `PreferList` derive; you can also implement it manually.
pub trait PrefersList: crate::list::IntoList {}

/// Marker trait for types that should be converted to R data frames via `IntoR`.
///
/// Implemented by the `PreferDataFrame` derive; you can also implement it manually.
pub trait PrefersDataFrame: crate::convert::IntoDataFrame {}

/// Marker trait for types that prefer `ExternalPtr` conversion.
///
/// Implemented by the `PreferExternalPtr` derive; currently informational.
pub trait PrefersExternalPtr: crate::externalptr::IntoExternalPtr {}

/// Marker trait for types that prefer native SEXP conversion.
///
/// Implemented by the `PreferRNativeType` derive; currently informational.
pub trait PrefersRNativeType: crate::ffi::RNativeType {}

// region: Coercion marker traits

/// Marker trait for types that can widen to `i32` without loss.
///
/// Manually implemented for specific types to avoid conflicts with identity/
/// special-case conversions. Used by blanket Coerce implementations.
pub trait WidensToI32: Into<i32> + Copy {}

/// Marker trait for types that can widen to `f64` without loss.
///
/// Manually implemented for specific types to avoid conflicts with identity/
/// special-case conversions. Used by blanket Coerce implementations.
pub trait WidensToF64: Into<f64> + Copy {}

// Explicit marker impls for widening conversions (no blanket impl to avoid conflicts)
impl WidensToI32 for i8 {}
impl WidensToI32 for i16 {}
impl WidensToI32 for u8 {}
impl WidensToI32 for u16 {}

impl WidensToF64 for f32 {}
impl WidensToF64 for i8 {}
impl WidensToF64 for i16 {}
impl WidensToF64 for i32 {}
impl WidensToF64 for u8 {}
impl WidensToF64 for u16 {}
impl WidensToF64 for u32 {}
// endregion
