//! Marker traits for proc-macro derived types.
//!
//! These marker traits identify types that have been derived with specific proc-macros.
//! They enable compile-time type checking and blanket implementations.
//!
//! # Pattern
//!
//! Each derive macro generates an impl of its corresponding marker trait:
//!
//! | Derive Macro | Marker Trait |
//! |--------------|--------------|
//! | `#[derive(DataFrameRow)]` | [`DataFrameRow`] |
//! | `#[derive(PreferList)]` | [`crate::markers::PrefersList`] |
//! | `#[derive(PreferExternalPtr)]` | [`crate::markers::PrefersExternalPtr`] |
//! | `#[derive(PreferRNativeType)]` | [`crate::markers::PrefersRNativeType`] |
//! | `#[derive(PreferDataFrame)]` | [`crate::markers::PrefersDataFrame`] |

/// Marker trait for types generated by `#[derive(DataFrameRow)]`.
///
/// Automatically implemented by the `DataFrameRow` derive macro. The derive
/// macro emits a compile-time assertion against this trait for every struct-typed
/// variant field, giving users a clear error when the inner type is missing the
/// derive.
///
/// This trait has no supertrait — the actual data-frame conversion contract is on the
/// generated companion `{Name}DataFrame` struct (which implements `IntoDataFrame`).
/// The marker is used solely for compile-time assertions via
/// `_assert_inner_is_dataframe_row::<T>()` generated by the outer derive.
///
/// You should not implement this trait manually.
#[diagnostic::on_unimplemented(
    message = "the trait `DataFrameRow` is not implemented for `{Self}`",
    label = "add `#[derive(DataFrameRow)]` to `{Self}`, annotate the field \
             with `#[dataframe(as_list)]` to keep it as an opaque list-column, \
             or annotate with `#[dataframe(as_factor)]` for unit-only enums",
    note = "struct- and enum-typed variant fields are flattened by default into prefixed \
            columns; the inner type must implement `DataFrameRow` for this to work"
)]
pub trait DataFrameRow {}

/// Marker trait for types that should be converted to R lists via `IntoR`.
///
/// Implemented by the `PreferList` derive; you can also implement it manually.
pub trait PrefersList: crate::list::IntoList {}

/// Marker trait for types that should be converted to R data frames via `IntoR`.
///
/// Implemented by the `PreferDataFrame` derive; you can also implement it manually.
pub trait PrefersDataFrame: crate::convert::IntoDataFrame {}

/// Marker trait for types that prefer `ExternalPtr` conversion.
///
/// Implemented by the `PreferExternalPtr` derive; currently informational.
pub trait PrefersExternalPtr: crate::externalptr::IntoExternalPtr {}

/// Marker trait for types that prefer native SEXP conversion.
///
/// Implemented by the `PreferRNativeType` derive; currently informational.
pub trait PrefersRNativeType: crate::ffi::RNativeType {}

// region: Coercion marker traits

/// Marker trait for types that can widen to `i32` without loss.
///
/// Manually implemented for specific types to avoid conflicts with identity/
/// special-case conversions. Used by blanket Coerce implementations.
pub trait WidensToI32: Into<i32> + Copy {}

/// Marker trait for types that can widen to `f64` without loss.
///
/// Manually implemented for specific types to avoid conflicts with identity/
/// special-case conversions. Used by blanket Coerce implementations.
pub trait WidensToF64: Into<f64> + Copy {}

// Explicit marker impls for widening conversions (no blanket impl to avoid conflicts)
impl WidensToI32 for i8 {}
impl WidensToI32 for i16 {}
impl WidensToI32 for u8 {}
impl WidensToI32 for u16 {}

impl WidensToF64 for f32 {}
impl WidensToF64 for i8 {}
impl WidensToF64 for i16 {}
impl WidensToF64 for i32 {}
impl WidensToF64 for u8 {}
impl WidensToF64 for u16 {}
impl WidensToF64 for u32 {}
// endregion
