fn main() {
    miniextendr_lint::build_script();

    println!("cargo:rerun-if-changed=wasm_registry.rs");

    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    if target_arch != "wasm32" {
        return;
    }

    let path = std::path::Path::new("wasm_registry.rs");
    let content = std::fs::read_to_string(path).unwrap_or_else(|_| {
        panic!(
            "wasm32 build requires src/rust/wasm_registry.rs, which is absent.\n\
             \n\
             This crate is NOT directly installable on wasm32. wasm_registry.rs\n\
             (and R/<pkg>-wrappers.R) are generated by a host cdylib pass and are\n\
             NOT tracked in git — they must be produced by a native build first.\n\
             The wasm32 build is a TWO-STEP process:\n\
             \n\
               1. Host build:  R CMD INSTALL <pkg>   (or `just rcmdinstall`)\n\
                  — runs the cdylib pass that writes src/rust/wasm_registry.rs.\n\
               2. wasm32 build: cross-compile, which reads the file from step 1.\n\
             \n\
             For a wasm install from a CRAN tarball, the tarball must already\n\
             contain wasm_registry.rs (produced by `R CMD build` on the host —\n\
             see `just r-cmd-build`). The wasm cdylib is a SIDE_MODULE that host\n\
             R cannot dyn.load, so there is no wasm-side regeneration fallback."
        )
    });

    let header_version: u32 = content
        .lines()
        .find_map(|l| l.strip_prefix("// generator-version: "))
        .and_then(|v| v.trim().parse().ok())
        .expect("wasm_registry.rs is missing or malformed `// generator-version: N` header");

    // Mirror miniextendr-api/src/wasm_registry_writer.rs GENERATOR_VERSION.
    // Bump both together when the generated-file shape changes.
    const EXPECTED_VERSION: u32 = 1;
    if header_version != EXPECTED_VERSION {
        panic!(
            "wasm_registry.rs was generated by miniextendr generator-version {header_version}, \
             but this build expects version {EXPECTED_VERSION}. \
             Run `just rcmdinstall` on the host to regenerate it."
        );
    }
}
