//! Test fixtures for macro bidirectional equivalence.
//!
//! These demonstrate that `#[miniextendr]` on structs/enums produces the same
//! trait implementations as the equivalent derive macros.

use miniextendr_api::miniextendr;

// region: 1. #[miniextendr] on multi-field struct → ExternalPtr

/// Multi-field struct: `#[miniextendr]` generates ExternalPtr + TypedExternal.
#[miniextendr]
pub struct MxPoint {
    pub x: f64,
    pub y: f64,
}

/// Test creating an MxPoint via ExternalPtr generated by #[miniextendr] on struct.
/// @param x Numeric x-coordinate.
/// @param y Numeric y-coordinate.
#[miniextendr]
pub fn mx_point_new(x: f64, y: f64) -> MxPoint {
    MxPoint { x, y }
}

/// Test summing fields of an MxPoint ExternalPtr.
/// @param p An ExternalPtr wrapping an MxPoint.
#[miniextendr]
pub fn mx_point_sum(p: miniextendr_api::externalptr::ExternalPtr<MxPoint>) -> f64 {
    p.x + p.y
}
// endregion

// region: 2. #[miniextendr(list)] on struct → IntoList + TryFromList + PreferList

/// Struct with list mode: generates IntoList + TryFromList + PreferList.
/// PreferList includes IntoR that routes through IntoList, so this type
/// can be returned directly from #[miniextendr] functions.
#[miniextendr(list)]
pub struct MxRecord {
    pub name: String,
    pub value: i32,
}

/// Test creating an MxRecord and returning as list via PreferList.
/// @param name Character name field.
/// @param value Integer value field.
#[miniextendr]
pub fn mx_record_create(name: String, value: i32) -> MxRecord {
    MxRecord { name, value }
}

/// Regression fixture for #861: a list-mode struct with a `Vec<f64>` field.
///
/// `Vec<f64>` implements `TryFromSexp` with `Error = SexpTypeError`, not
/// `SexpError`. The `TryFromList` derive used to pin `Error = SexpError`, so
/// this struct failed to compile with E0271. It now compiles, round-trips, and
/// is returnable via `PreferList`.
#[miniextendr(list)]
pub struct MxFit {
    pub estimate: Vec<f64>,
    pub sigma: f64,
}

/// Construct an `MxFit` and return it as an R list (exercises `IntoList`).
/// @param estimate Numeric vector of parameter estimates.
/// @param sigma Numeric residual scale.
#[miniextendr]
pub fn mx_fit_create(estimate: Vec<f64>, sigma: f64) -> MxFit {
    MxFit { estimate, sigma }
}

/// Round-trip an `MxFit` through `IntoList` and the (fixed) `TryFromList`
/// derive, returning the reconstructed `estimate` vector. This is the only
/// path that exercises the `Vec<f64>` field's `try_from_sexp` extraction at
/// runtime — list-mode structs are not generated as `#[miniextendr]` argument
/// types, so they cannot be reconstructed directly from an R call.
/// @param estimate Numeric vector of parameter estimates.
/// @param sigma Numeric residual scale.
#[miniextendr]
pub fn mx_fit_roundtrip(estimate: Vec<f64>, sigma: f64) -> Vec<f64> {
    use miniextendr_api::from_r::TryFromSexp;
    use miniextendr_api::into_r::IntoR;
    use miniextendr_api::list::{IntoList, List, TryFromList};

    let fit = MxFit { estimate, sigma };
    // SAFETY: `#[miniextendr]` fns run on the R main thread. Protect the
    // intermediate list SEXP across the read-back so GC cannot collect it.
    unsafe {
        let scope = miniextendr_api::gc_protect::ProtectScope::new();
        let list_sexp = scope.protect_raw(fit.into_list().into_sexp());
        let list = List::try_from_sexp(list_sexp).expect("into_list produces a VECSXP");
        let restored = MxFit::try_from_list(list).expect("MxFit round-trip should succeed");
        restored.estimate
    }
}
// endregion

// region: 3. #[miniextendr(dataframe)] on struct → DataFrameRow + PreferDataFrame

/// Struct with dataframe mode: generates IntoList + DataFrameRow + IntoR on companion.
/// The companion MxObsDataFrame type can be returned directly from #[miniextendr] functions.
#[miniextendr(dataframe)]
pub struct MxObs {
    pub id: i32,
    pub score: f64,
}

/// Test creating an MxObs dataframe with two sample rows.
#[miniextendr]
pub fn mx_obs_create() -> MxObsDataFrame {
    MxObs::to_dataframe(vec![
        MxObs { id: 1, score: 0.5 },
        MxObs { id: 2, score: 0.8 },
    ])
}
// endregion

// region: 4. #[miniextendr] on fieldless enum → RFactor

/// Fieldless enum: `#[miniextendr]` generates RFactor + IntoR + TryFromSexp.
#[miniextendr]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum MxSeason {
    Spring,
    Summer,
    Autumn,
    Winter,
}

/// Test returning the Summer variant of MxSeason as an R factor.
#[miniextendr]
pub fn mx_season_summer() -> MxSeason {
    MxSeason::Summer
}

/// Test converting an MxSeason factor back to its debug string.
/// @param s An MxSeason factor value.
#[miniextendr]
pub fn mx_season_name(s: MxSeason) -> String {
    format!("{:?}", s)
}
// endregion

// region: 5. #[miniextendr(match_arg)] on fieldless enum → MatchArg

/// Fieldless enum with match_arg: generates MatchArg + IntoR + TryFromSexp.
#[miniextendr(match_arg)]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum MxVerbosity {
    Quiet,
    Normal,
    Verbose,
}

/// Test converting an MxVerbosity match_arg enum to its debug string.
/// @param v An MxVerbosity enum value.
#[miniextendr]
pub fn mx_verbosity_check(v: MxVerbosity) -> String {
    format!("{:?}", v)
}
// endregion

// region: 6. #[derive(Altrep)] on data struct → ALTREP registration (direct pattern)

/// Data struct via derive: generates full ALTREP registration.
#[derive(miniextendr_api::AltrepInteger)]
#[altrep(class = "MxDerivedInts", manual, dataptr)]
pub struct MxDerivedIntsData {
    data: Vec<i32>,
}

impl miniextendr_api::altrep_data::AltrepLen for MxDerivedIntsData {
    fn len(&self) -> usize {
        self.data.len()
    }
}

impl miniextendr_api::altrep_data::AltIntegerData for MxDerivedIntsData {
    fn elt(&self, i: usize) -> i32 {
        self.data[i]
    }
    fn as_slice(&self) -> Option<&[i32]> {
        Some(&self.data)
    }
}

impl miniextendr_api::altrep_data::AltrepDataptr<i32> for MxDerivedIntsData {
    fn dataptr(&mut self, _writable: bool) -> Option<*mut i32> {
        Some(self.data.as_mut_ptr())
    }
    fn dataptr_or_null(&self) -> Option<*const i32> {
        Some(self.data.as_ptr())
    }
}

/// Test creating an ALTREP integer vector via derive(Altrep).
#[miniextendr]
pub fn mx_derived_ints() -> MxDerivedIntsData {
    MxDerivedIntsData {
        data: vec![10, 20, 30],
    }
}
// endregion

// region: Module registration
// endregion
