//! Test fixtures for macro bidirectional equivalence.
//!
//! These demonstrate that `#[miniextendr]` on structs/enums produces the same
//! trait implementations as the equivalent derive macros.

use miniextendr_api::miniextendr;

// region: 1. #[miniextendr] on multi-field struct → ExternalPtr

/// Multi-field struct: `#[miniextendr]` generates ExternalPtr + TypedExternal.
#[miniextendr]
pub struct MxPoint {
    pub x: f64,
    pub y: f64,
}

/// Test creating an MxPoint via ExternalPtr generated by #[miniextendr] on struct.
/// @param x Numeric x-coordinate.
/// @param y Numeric y-coordinate.
#[miniextendr]
pub fn mx_point_new(x: f64, y: f64) -> MxPoint {
    MxPoint { x, y }
}

/// Test summing fields of an MxPoint ExternalPtr.
/// @param p An ExternalPtr wrapping an MxPoint.
#[miniextendr]
pub fn mx_point_sum(p: miniextendr_api::externalptr::ExternalPtr<MxPoint>) -> f64 {
    p.x + p.y
}
// endregion

// region: 2. #[miniextendr(list)] on struct → IntoList + TryFromList + PreferList

/// Struct with list mode: generates IntoList + TryFromList + PreferList.
/// PreferList includes IntoR that routes through IntoList, so this type
/// can be returned directly from #[miniextendr] functions.
#[miniextendr(list)]
pub struct MxRecord {
    pub name: String,
    pub value: i32,
}

/// Test creating an MxRecord and returning as list via PreferList.
/// @param name Character name field.
/// @param value Integer value field.
#[miniextendr]
pub fn mx_record_create(name: String, value: i32) -> MxRecord {
    MxRecord { name, value }
}
// endregion

// region: 3. #[miniextendr(dataframe)] on struct → DataFrameRow + PreferDataFrame

/// Struct with dataframe mode: generates IntoList + DataFrameRow + IntoR on companion.
/// The companion MxObsDataFrame type can be returned directly from #[miniextendr] functions.
#[miniextendr(dataframe)]
pub struct MxObs {
    pub id: i32,
    pub score: f64,
}

/// Test creating an MxObs dataframe with two sample rows.
#[miniextendr]
pub fn mx_obs_create() -> MxObsDataFrame {
    MxObs::to_dataframe(vec![
        MxObs { id: 1, score: 0.5 },
        MxObs { id: 2, score: 0.8 },
    ])
}
// endregion

// region: 4. #[miniextendr] on fieldless enum → RFactor

/// Fieldless enum: `#[miniextendr]` generates RFactor + IntoR + TryFromSexp.
#[miniextendr]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum MxSeason {
    Spring,
    Summer,
    Autumn,
    Winter,
}

/// Test returning the Summer variant of MxSeason as an R factor.
#[miniextendr]
pub fn mx_season_summer() -> MxSeason {
    MxSeason::Summer
}

/// Test converting an MxSeason factor back to its debug string.
/// @param s An MxSeason factor value.
#[miniextendr]
pub fn mx_season_name(s: MxSeason) -> String {
    format!("{:?}", s)
}
// endregion

// region: 5. #[miniextendr(match_arg)] on fieldless enum → MatchArg

/// Fieldless enum with match_arg: generates MatchArg + IntoR + TryFromSexp.
#[miniextendr(match_arg)]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum MxVerbosity {
    Quiet,
    Normal,
    Verbose,
}

/// Test converting an MxVerbosity match_arg enum to its debug string.
/// @param v An MxVerbosity enum value.
#[miniextendr]
pub fn mx_verbosity_check(v: MxVerbosity) -> String {
    format!("{:?}", v)
}
// endregion

// region: 6. #[derive(Altrep)] on data struct → ALTREP registration (direct pattern)

/// Data struct via derive: generates full ALTREP registration.
#[derive(miniextendr_api::AltrepInteger)]
#[altrep(class = "MxDerivedInts", manual, dataptr)]
pub struct MxDerivedIntsData {
    data: Vec<i32>,
}

impl miniextendr_api::altrep_data::AltrepLen for MxDerivedIntsData {
    fn len(&self) -> usize {
        self.data.len()
    }
}

impl miniextendr_api::altrep_data::AltIntegerData for MxDerivedIntsData {
    fn elt(&self, i: usize) -> i32 {
        self.data[i]
    }
    fn as_slice(&self) -> Option<&[i32]> {
        Some(&self.data)
    }
}

impl miniextendr_api::altrep_data::AltrepDataptr<i32> for MxDerivedIntsData {
    fn dataptr(&mut self, _writable: bool) -> Option<*mut i32> {
        Some(self.data.as_mut_ptr())
    }
    fn dataptr_or_null(&self) -> Option<*const i32> {
        Some(self.data.as_ptr())
    }
}

/// Test creating an ALTREP integer vector via derive(Altrep).
#[miniextendr]
pub fn mx_derived_ints() -> MxDerivedIntsData {
    MxDerivedIntsData {
        data: vec![10, 20, 30],
    }
}
// endregion

// region: Module registration
// endregion
