//! UUID adapter tests
use miniextendr_api::uuid_impl::Uuid;
use miniextendr_api::{IntoR, TryFromSexp, miniextendr};

/// A newtype over `Uuid` whose R↔Rust conversions are generated by
/// `#[derive(TryFromSexp, IntoR)]`. The scalar impls forward to `Uuid`, so
/// `DocId` inherits the inner type's character-string round-trip and its
/// "invalid UUID" parse error verbatim. The container blankets in
/// `miniextendr_api::newtype` then light up `Vec<DocId>` / `Option<DocId>`
/// (R → Rust) and `Vec<Option<DocId>>` automatically — see issue #844.
#[derive(TryFromSexp, IntoR)]
pub struct DocId(Uuid);

/// Round-trip a `DocId` newtype through R. Exercises the derived scalar
/// `TryFromSexp` (argument) and `IntoR` (return value).
/// @param id A UUID string parsed into the `DocId` newtype.
#[miniextendr]
pub fn docid_roundtrip(id: DocId) -> DocId {
    id
}

/// Round-trip a `Vec<DocId>` through R. Exercises the derived `TryFromSexp for
/// Vec<DocId>` (argument) and the `IntoRVecElement`-backed `IntoR for Vec<DocId>`
/// (return value) — both forward to the inner `Vec<Uuid>` conversions.
/// @param ids A character vector of UUID strings, each parsed into a `DocId`.
#[miniextendr]
pub fn docid_roundtrip_vec(ids: Vec<DocId>) -> Vec<DocId> {
    ids
}

/// Round-trip a `Vec<Option<DocId>>` through R, preserving `NA`. Exercises the
/// derived `TryFromSexp for Vec<Option<DocId>>` (argument) and `IntoR for
/// Vec<Option<DocId>>` (return value); `NA_character_` maps to `None` and back.
/// @param ids A character vector of UUID strings (or `NA`) parsed into `DocId`s.
#[miniextendr]
pub fn docid_roundtrip_opt_vec(ids: Vec<Option<DocId>>) -> Vec<Option<DocId>> {
    ids
}

/// Whether an optional `DocId` argument is present. Exercises the derived
/// `TryFromSexp for Option<DocId>` (R → Rust): `NA_character_` parses to `None`,
/// a valid UUID string to `Some`. (`Option<DocId>` → R is intentionally not
/// granted — see the `newtype` module docs — so this returns a `bool`.)
/// @param id A UUID string or `NA`, parsed into `Option<DocId>`.
#[miniextendr]
pub fn docid_is_present(id: Option<DocId>) -> bool {
    id.is_some()
}

/// Test UUID roundtrip through R string.
/// @param uuid UUID parsed from R string.
#[miniextendr]
pub fn uuid_roundtrip(uuid: Uuid) -> Uuid {
    uuid
}

/// Test Vec<Uuid> roundtrip through R character vector.
/// @param uuids Character vector of UUIDs from R.
#[miniextendr]
pub fn uuid_roundtrip_vec(uuids: Vec<Uuid>) -> Vec<Uuid> {
    uuids
}

/// Test generating a new random UUID v4.
#[miniextendr]
pub fn uuid_new_v4() -> Uuid {
    Uuid::new_v4()
}

/// Test creating a nil (all-zeros) UUID.
#[miniextendr]
pub fn uuid_nil() -> Uuid {
    Uuid::nil()
}

/// Test creating a max (all-ones) UUID.
#[miniextendr]
pub fn uuid_max() -> Uuid {
    Uuid::max()
}

/// Test extracting the version number from a UUID.
/// @param uuid UUID parsed from R string.
#[miniextendr]
pub fn uuid_version(uuid: Uuid) -> i32 {
    uuid.get_version_num() as i32
}

/// Test whether a UUID is the nil UUID.
/// @param uuid UUID parsed from R string.
#[miniextendr]
pub fn uuid_is_nil(uuid: Uuid) -> bool {
    uuid.is_nil()
}
