//! # `#[derive(ExternalPtr)]` - ExternalPtr and Trait ABI Generation
//!
//! This module implements the `#[derive(ExternalPtr)]` macro which generates
//! a `TypedExternal` impl for use with `ExternalPtr<T>`.
//!
//! Trait ABI wrapper infrastructure is generated by `miniextendr_module!`
//! when you list `impl Trait for Type;`.
//!
//! ## Usage
//!
//! ### Basic (no traits)
//!
//! ```ignore
//! #[derive(ExternalPtr)]
//! struct MyData {
//!     value: i32,
//! }
//! // Generates: impl TypedExternal for MyData { ... }
//! ```
//!
//! ### Trait ABI wiring
//!
//! ```ignore
//! #[derive(ExternalPtr)]
//! struct MyCounter {
//!     value: i32,
//! }
//!
//! #[miniextendr]
//! impl Counter for MyCounter { /* ... */ }
//!
//! miniextendr_module! {
//!     mod mypkg;
//!     impl Counter for MyCounter;
//! }
//! ```
//!
//! ## Generated Types (trait impls)
//!
//! ### Wrapper Struct
//!
//! ```ignore
//! #[repr(C)]
//! struct __MxWrapperMyCounter {
//!     erased: mx_erased,  // Must be first field
//!     data: MyCounter,
//! }
//! ```
//!
//! ### Base Vtable
//!
//! ```ignore
//! static __MX_BASE_VTABLE_MYCOUNTER: mx_base_vtable = mx_base_vtable {
//!     drop: __mx_drop_mycounter,
//!     concrete_tag: TAG_MYCOUNTER,
//!     query: __mx_query_mycounter,
//! };
//! ```
//!
//! ### Query Function
//!
//! The query function maps trait tags to vtable pointers:
//!
//! ```ignore
//! unsafe extern "C" fn __mx_query_mycounter(
//!     ptr: *mut mx_erased,
//!     trait_tag: mx_tag,
//! ) -> *const c_void {
//!     if trait_tag == TAG_COUNTER {
//!         return &__VTABLE_COUNTER_FOR_MYCOUNTER as *const _ as *const c_void;
//!     }
//!     std::ptr::null()
//! }
//! ```

use proc_macro2::TokenStream;
use syn::DeriveInput;

fn ensure_no_externalptr_attrs(input: &DeriveInput) -> syn::Result<()> {
    for attr in &input.attrs {
        if attr.path().is_ident("externalptr") {
            return Err(syn::Error::new_spanned(
                attr,
                "#[externalptr(...)] is no longer supported; list `impl Trait for Type;` in miniextendr_module! instead",
            ));
        }
    }
    Ok(())
}

/// Generate the basic `TypedExternal` implementation.
fn generate_typed_external(input: &DeriveInput) -> TokenStream {
    let name = &input.ident;
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    let name_str = name.to_string();
    let name_lit = syn::LitStr::new(&name_str, name.span());
    let name_cstr = syn::LitByteStr::new(format!("{}\0", name_str).as_bytes(), name.span());

    quote::quote! {
        impl #impl_generics ::miniextendr_api::externalptr::TypedExternal for #name #ty_generics #where_clause {
            const TYPE_NAME: &'static str = #name_lit;
            const TYPE_NAME_CSTR: &'static [u8] = #name_cstr;
        }
    }
}

/// Main entry point for `#[derive(ExternalPtr)]`.
pub fn derive_external_ptr(input: DeriveInput) -> syn::Result<TokenStream> {
    ensure_no_externalptr_attrs(&input)?;

    let typed_external = generate_typed_external(&input);

    Ok(quote::quote! {
        #typed_external
    })
}
