//! # `#[miniextendr_impl_trait]` - Trait Implementation Registration
//!
//! This module handles `#[miniextendr_impl_trait]` applied to trait implementations,
//! generating the vtable static for cross-package trait dispatch.
//!
//! ## Overview
//!
//! When `#[miniextendr_impl_trait]` is applied to an `impl Trait for Type` block, it:
//!
//! 1. **Detects the trait** from the impl syntax (no attribute args needed)
//! 2. **Generates vtable static** using the trait's `__<trait>_build_vtable` function
//! 3. **Passes through** the original impl block unchanged
//!
//! ## Usage
//!
//! ```ignore
//! use miniextendr_macros::miniextendr_impl_trait;
//!
//! // The trait must have been defined with #[miniextendr]
//! // which generates __counter_build_vtable::<T>()
//!
//! struct MyCounter { value: i32 }
//!
//! #[miniextendr_impl_trait]
//! impl Counter for MyCounter {
//!     fn value(&self) -> i32 {
//!         self.value
//!     }
//!     fn increment(&mut self) {
//!         self.value += 1;
//!     }
//!     fn add(&mut self, n: i32) {
//!         self.value += n;
//!     }
//! }
//! ```
//!
//! Generates (conceptually):
//!
//! ```ignore
//! // Original impl block (passed through)
//! impl Counter for MyCounter {
//!     fn value(&self) -> i32 { self.value }
//!     fn increment(&mut self) { self.value += 1; }
//!     fn add(&mut self, n: i32) { self.value += n; }
//! }
//!
//! // Generated vtable static
//! pub static __VTABLE_COUNTER_FOR_MYCOUNTER: CounterVTable =
//!     __counter_build_vtable::<MyCounter>();
//! ```
//!
//! ## How It Works
//!
//! 1. Parse `impl Trait for Type` to extract trait path and concrete type
//! 2. Generate vtable static name: `__VTABLE_{TRAIT}_FOR_{TYPE}`
//! 3. Generate vtable builder call: `__{trait}_build_vtable::<Type>()`
//! 4. The vtable builder was generated by `#[miniextendr]` on the trait
//!
//! ## Trait Detection
//!
//! The macro reads the trait directly from the impl syntax:
//!
//! ```ignore
//! #[miniextendr_impl_trait]
//! impl path::to::Counter for MyType { ... }
//! //   ^^^^^^^^^^^^^^^^^ detected automatically
//! ```
//!
//! No need for `#[miniextendr_impl_trait(trait = "...")]` - the trait is always explicit in Rust's impl syntax.
//!
//! ## Name Generation
//!
//! - **Vtable static**: `__VTABLE_{TRAIT}_FOR_{TYPE}` (uppercase, underscores)
//! - **Vtable builder**: `__{trait}_build_vtable` (lowercase)
//!
//! For `impl foo::Counter for my_mod::MyType`:
//! - Static: `__VTABLE_COUNTER_FOR_MYTYPE`
//! - Builder call: `foo::__counter_build_vtable::<my_mod::MyType>()`
//!
//! ## Integration with ExternalPtr / TypedExternal
//!
//! The generated vtable static is referenced by the `ExternalPtr` derive
//! when generating the type-erased wrapper. Users list which traits are implemented:
//!
//! ```ignore
//! #[derive(ExternalPtr)]
//! #[externalptr(traits = [Counter, Display])]  // Future: trait ABI support
//! struct MyCounter { value: i32 }
//! ```
//!
//! This tells ExternalPtr to include Counter and Display in the query function.
//! `ExternalPtr<T>` without trait attributes serves as the "traitless" case,
//! equivalent to `Any` in dynamic typing.
//!
//! ## Thread Safety
//!
//! The generated vtable is a static constant, safe to access from any thread.
//! However, the methods themselves are main-thread only (shims don't route).

use proc_macro2::TokenStream;
use syn::ItemImpl;

/// Expand `#[miniextendr_impl_trait]` applied to a trait implementation.
///
/// # Arguments
///
/// * `attr` - Attribute arguments (currently unused)
/// * `item` - The impl block token stream
///
/// # Returns
///
/// Expanded token stream containing:
/// - Original impl block
/// - Vtable static constant
///
/// # Errors
///
/// Returns a compile error if:
/// - Not applied to a trait impl (`impl Trait for Type`)
/// - Applied to an inherent impl (`impl Type`)
pub fn expand_miniextendr_impl_trait(
    _attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    let impl_item = syn::parse_macro_input!(item as ItemImpl);

    // Validate: must be a trait impl, not inherent impl
    let (trait_path, concrete_type) = match extract_trait_and_type(&impl_item) {
        Ok(result) => result,
        Err(e) => return e.into_compile_error().into(),
    };

    // Generate the vtable static
    let expanded = generate_vtable_static(&impl_item, &trait_path, &concrete_type);

    expanded.into()
}

/// Extract the trait path and concrete type from an impl block.
///
/// For `impl path::Trait for concrete::Type`, returns:
/// - trait_path: `path::Trait`
/// - concrete_type: `concrete::Type`
fn extract_trait_and_type(impl_item: &ItemImpl) -> syn::Result<(syn::Path, syn::Type)> {
    // Check for trait impl
    let (_, trait_path, _) = impl_item.trait_.as_ref().ok_or_else(|| {
        syn::Error::new_spanned(
            impl_item,
            "#[miniextendr_impl_trait] must be applied to a trait implementation (impl Trait for Type), \
             not an inherent impl (impl Type)",
        )
    })?;

    let concrete_type = (*impl_item.self_ty).clone();

    Ok((trait_path.clone(), concrete_type))
}

/// Generate the vtable static for a trait implementation.
fn generate_vtable_static(
    impl_item: &ItemImpl,
    trait_path: &syn::Path,
    concrete_type: &syn::Type,
) -> TokenStream {
    // Extract trait name for naming
    let trait_name = trait_path
        .segments
        .last()
        .map(|s| &s.ident)
        .expect("trait path has at least one segment");

    // Extract type name for naming (simplified - handles Path types)
    let type_name_str = type_to_uppercase_name(concrete_type);
    let trait_name_upper = trait_name.to_string().to_uppercase();
    let trait_name_lower = trait_name.to_string().to_lowercase();

    // Generate names
    let vtable_static_name =
        quote::format_ident!("__VTABLE_{}_FOR_{}", trait_name_upper, type_name_str);
    let vtable_type_name = quote::format_ident!("{}VTable", trait_name);

    // Build path to vtable builder function
    // If trait is `foo::Counter`, builder is `foo::__counter_build_vtable`
    let mut builder_path = trait_path.clone();
    if let Some(last) = builder_path.segments.last_mut() {
        last.ident = quote::format_ident!("__{}_build_vtable", trait_name_lower);
    }

    // Build the vtable type path (same module as trait)
    let mut vtable_type_path = trait_path.clone();
    if let Some(last) = vtable_type_path.segments.last_mut() {
        last.ident = vtable_type_name.clone();
    }

    quote::quote! {
        // Pass through the original impl block
        #impl_item

        /// Vtable for `#concrete_type` implementing `#trait_path`.
        ///
        /// Generated by `#[miniextendr]` on the trait impl block.
        #[doc(hidden)]
        pub static #vtable_static_name: #vtable_type_path =
            #builder_path::<#concrete_type>();
    }
}

/// Convert a type to an uppercase identifier-safe name.
///
/// Examples:
/// - `MyType` → `MYTYPE`
/// - `path::to::MyType` → `MYTYPE` (uses last segment)
/// - `MyType<T>` → `MYTYPE` (strips generics)
fn type_to_uppercase_name(ty: &syn::Type) -> String {
    match ty {
        syn::Type::Path(type_path) => {
            // Use last segment, strip generics
            type_path
                .path
                .segments
                .last()
                .map(|s| s.ident.to_string().to_uppercase())
                .unwrap_or_else(|| "UNKNOWN".to_string())
        }
        _ => "UNKNOWN".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_type_to_uppercase_name() {
        // Simple type
        let ty: syn::Type = syn::parse_quote!(MyType);
        assert_eq!(type_to_uppercase_name(&ty), "MYTYPE");

        // Path type
        let ty: syn::Type = syn::parse_quote!(path::to::MyType);
        assert_eq!(type_to_uppercase_name(&ty), "MYTYPE");
    }
}
