# R package setup functions

#' Add package documentation file
#'
#' Creates R/<package>-package.R with the package docstring and
#' useDynLib directive for loading the shared library.
#'
#' @param path Path to the R package root, or `"."` to use the current directory.
#' @return Invisibly returns TRUE if file was created
#' @keywords internal
use_miniextendr_package_doc <- function(path = ".") {
  with_project(path)
  data <- template_data()
  ensure_dir(usethis::proj_path("R"))

  save_as <- paste0("R/", data$package, "-package.R")
  use_template("package.R", save_as = save_as, data = data)

  cli::cli_alert_info("Run {.code devtools::document()} to update NAMESPACE with useDynLib")
  invisible(TRUE)
}

#' Ensure a minimal roxygen2-compatible NAMESPACE exists
#'
#' `usethis::create_package()` normally seeds a `NAMESPACE`, but
#' `use_miniextendr()` may be run against a package that was set up some other
#' way (e.g. via `usethis::use_description()` in an existing repo). Without a
#' `NAMESPACE` the first build fails on the configure-time guard. This seeds a
#' minimal `NAMESPACE` carrying the roxygen2 header plus the
#' `useDynLib(<pkg>, .registration = TRUE)` directive, so the shared library
#' loads and a later `devtools::document()` manages (rather than clobbers) the
#' file. No-op when a `NAMESPACE` already exists.
#'
#' @param path Path to the R package root, or `"."` to use the current directory.
#' @return Invisibly returns TRUE if a NAMESPACE was created, FALSE if one
#'   already existed.
#' @keywords internal
use_miniextendr_namespace <- function(path = ".") {
  with_project(path)
  namespace_path <- usethis::proj_path("NAMESPACE")

  if (fs::file_exists(namespace_path)) {
    return(invisible(FALSE))
  }

  pkg_name <- get_package_name()
  # Mirror the header roxygen2 writes so a later devtools::document() treats
  # this as a roxygen-managed file and overwrites it cleanly. The useDynLib
  # line matches the `@useDynLib <pkg>, .registration = TRUE` tag in the
  # generated R/<pkg>-package.R doc file.
  namespace_content <- sprintf(
    "# Generated by roxygen2: do not edit by hand\n\nuseDynLib(%s, .registration = TRUE)\n",
    pkg_name
  )
  writeLines(namespace_content, namespace_path)
  cli::cli_alert_warning(
    "No {.path NAMESPACE} found; created a minimal one with {.code useDynLib({pkg_name}, .registration = TRUE)}."
  )
  cli::cli_alert_info("Run {.code devtools::document()} to populate it from your roxygen comments.")
  invisible(TRUE)
}

#' Configure DESCRIPTION for miniextendr
#'
#' Ensures a `DESCRIPTION` exists, then applies the miniextendr config fields.
#' When `DESCRIPTION` is absent, a minimal one is created by delegating to
#' [usethis::use_description()] (so `use_miniextendr()` works in a fresh
#' directory); when it already exists, only the miniextendr fields are updated.
#'
#' Adds the required Config/* fields to DESCRIPTION for miniextendr:
#' - Config/build/bootstrap: TRUE
#' - Config/build/never-clean: true
#' - Config/build/extra-sources: src/rust/Cargo.lock
#'
#' Also adds SystemRequirements for Rust.
#'
#' @param path Path to the R package root, or `"."` to use the current directory.
#' @return Invisibly returns TRUE
#' @keywords internal
use_miniextendr_description <- function(path = ".") {
  with_project(path)
  desc_path <- usethis::proj_path("DESCRIPTION")

  if (!fs::file_exists(desc_path)) {
    # No DESCRIPTION yet: a `use_*` helper should create the thing it names.
    # Delegate to usethis::use_description(), which derives the package name
    # from the (already active) project directory and writes a minimal,
    # well-formed DESCRIPTION. Run it deterministically for scripted use:
    # check_name = FALSE skips the interactive name check, and usethis.quiet
    # suppresses bullets so nested scaffolding output stays tidy.
    cli::cli_alert_info("No {.path DESCRIPTION} found; creating a minimal one")
    old_quiet <- getOption("usethis.quiet", default = NULL)
    options(usethis.quiet = TRUE)
    on.exit(options(usethis.quiet = old_quiet), add = TRUE)
    usethis::use_description(check_name = FALSE, roxygen = FALSE)
  }

  # Set Config fields
  mx_desc_set(desc_path,
    "Config/build/bootstrap" = "TRUE",
    "Config/build/never-clean" = "true",
    "Config/build/extra-sources" = "src/rust/Cargo.lock"
  )

  # Set License if not already set to something meaningful. A freshly created
  # DESCRIPTION (from usethis::use_description()) carries a placeholder License
  # like "`use_mit_license()`, `use_gpl3_license()` or friends ..."; treat any
  # such "use_*_license()" placeholder as unset so we fill in MIT + file LICENSE.
  license <- mx_desc_get_field("License", file = desc_path, default = "")
  if (!nzchar(license) || grepl("use_[a-z0-9]+_license\\(\\)", license)) {
    mx_desc_set(desc_path, "License" = "MIT + file LICENSE")
  }

  # Add SystemRequirements if not present
  sys_req <- mx_desc_get_field("SystemRequirements", file = desc_path, default = "")
  if (!grepl("Rust", sys_req, ignore.case = TRUE)) {
    if (nzchar(sys_req)) {
      sys_req <- paste0(sys_req, ", Rust (>= 1.85)")
    } else {
      sys_req <- "Rust (>= 1.85)"
    }
    mx_desc_set(desc_path, "SystemRequirements" = sys_req)
  }

  # Create LICENSE file if it doesn't exist (required by License: MIT + file LICENSE)
  license_path <- usethis::proj_path("LICENSE")
  if (!fs::file_exists(license_path)) {
    pkg_name <- mx_desc_get_field("Package", file = desc_path)
    license_content <- sprintf("YEAR: %s\nCOPYRIGHT HOLDER: %s authors\n",
                               format(Sys.Date(), "%Y"), pkg_name)
    writeLines(license_content, license_path)
    cli::cli_alert_success("Created {.path LICENSE}")
  }

  cli::cli_alert_success("Updated DESCRIPTION with miniextendr config fields")
  invisible(TRUE)
}

#' Add .Rbuildignore patterns for miniextendr
#'
#' Appends miniextendr-specific ignore patterns to .Rbuildignore,
#' or creates the file if it doesn't exist.
#'
#' @param path Path to the R package root, or `"."` to use the current directory.
#' @return Invisibly returns TRUE
#' @keywords internal
use_miniextendr_rbuildignore <- function(path = ".") {
  with_project(path)
  # Read template content (already regex patterns, skip escaping)
  template_content <- readLines(template_path("Rbuildignore"))

  # Filter out empty lines and comments for usethis
  patterns <- template_content[nzchar(template_content) & !grepl("^#", template_content)]

  # usethis handles deduplication and file creation automatically
  # escape = FALSE because our template already contains regex patterns
  usethis::use_build_ignore(patterns, escape = FALSE)

  invisible(TRUE)
}

#' Add .gitignore patterns for miniextendr
#'
#' Appends miniextendr-specific ignore patterns to .gitignore,
#' or creates the file if it doesn't exist.
#'
#' @param path Path to the R package root, or `"."` to use the current directory.
#' @return Invisibly returns TRUE
#' @keywords internal
use_miniextendr_gitignore <- function(path = ".") {
  with_project(path)
  # Read template content
  template_content <- readLines(template_path("gitignore"))

  # Filter out empty lines and comments for usethis
  patterns <- template_content[nzchar(template_content) & !grepl("^#", template_content)]

  # usethis handles deduplication and file creation automatically
  usethis::use_git_ignore(patterns, directory = ".")

  invisible(TRUE)
}
